// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_ST_fsm_state1 = "1";
const sc_lv<3> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_ST_fsm_state2 = "10";
const sc_lv<3> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_ST_fsm_state3 = "100";
const sc_lv<32> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv32_1 = "1";
const sc_lv<2> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv2_0 = "00";
const sc_lv<11> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv11_0 = "00000000000";
const sc_lv<32> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv32_A = "1010";
const sc_lv<32> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv32_7 = "111";
const sc_lv<13> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv13_1D = "11101";
const sc_lv<32> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv32_C = "1100";
const sc_lv<13> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv13_17 = "10111";
const sc_lv<13> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv13_16 = "10110";
const sc_lv<12> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv12_D = "1101";
const sc_lv<32> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv32_B = "1011";
const sc_lv<5> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv5_0 = "00000";
const sc_lv<3> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv3_0 = "000";
const sc_lv<32> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv32_D = "1101";
const sc_lv<4> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv4_0 = "0000";
const sc_lv<13> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv13_1FF5 = "1111111110101";
const sc_lv<14> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv14_3FE5 = "11111111100101";
const sc_lv<13> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv13_1A = "11010";
const sc_lv<12> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv12_FC0 = "111111000000";
const sc_lv<14> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv14_3FEA = "11111111101010";
const sc_lv<12> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv12_180 = "110000000";
const sc_lv<14> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv14_0 = "00000000000000";
const sc_lv<32> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv32_E = "1110";
const sc_lv<12> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv12_1C0 = "111000000";
const sc_lv<6> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv6_0 = "000000";
const sc_lv<10> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv10_2C0 = "1011000000";
const sc_lv<13> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv13_0 = "0000000000000";
const sc_lv<1> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv1_0 = "0";
const sc_lv<12> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv12_E0 = "11100000";
const sc_lv<10> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv10_0 = "0000000000";
const sc_lv<32> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv32_9 = "1001";
const sc_lv<14> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv14_26 = "100110";
const sc_lv<9> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv9_140 = "101000000";
const sc_lv<32> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_lv32_2 = "10";
const bool dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::ap_const_boolean_1 = true;

dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_acc_1_V_fu_981_p2);
    sensitive << ( sext_ln703_28_fu_967_p1 );
    sensitive << ( sext_ln703_29_fu_977_p1 );

    SC_METHOD(thread_acc_2_V_fu_999_p2);
    sensitive << ( add_ln703_36_fu_990_p2 );
    sensitive << ( sext_ln703_30_fu_996_p1 );

    SC_METHOD(thread_acc_3_V_fu_1024_p2);
    sensitive << ( sext_ln703_31_fu_1017_p1 );
    sensitive << ( zext_ln703_16_fu_1021_p1 );

    SC_METHOD(thread_acc_4_V_fu_1045_p2);
    sensitive << ( sext_ln703_33_fu_1033_p1 );
    sensitive << ( add_ln703_46_fu_1039_p2 );

    SC_METHOD(thread_acc_5_V_fu_1066_p2);
    sensitive << ( add_ln703_48_fu_1057_p2 );
    sensitive << ( sext_ln703_36_fu_1063_p1 );

    SC_METHOD(thread_acc_6_V_fu_1087_p2);
    sensitive << ( add_ln703_52_fu_1078_p2 );
    sensitive << ( sext_ln703_38_fu_1084_p1 );

    SC_METHOD(thread_acc_7_V_fu_1112_p2);
    sensitive << ( sext_ln703_39_fu_1096_p1 );
    sensitive << ( sext_ln703_5_fu_1108_p1 );

    SC_METHOD(thread_add_ln1118_5_fu_200_p2);
    sensitive << ( zext_ln1118_47_fu_154_p1 );
    sensitive << ( zext_ln703_fu_142_p1 );

    SC_METHOD(thread_add_ln1118_6_fu_870_p2);
    sensitive << ( zext_ln1118_38_fu_286_p1 );
    sensitive << ( zext_ln1118_57_fu_768_p1 );

    SC_METHOD(thread_add_ln1118_fu_345_p2);
    sensitive << ( zext_ln1118_43_fu_330_p1 );
    sensitive << ( zext_ln1118_44_fu_341_p1 );

    SC_METHOD(thread_add_ln703_31_fu_364_p2);
    sensitive << ( zext_ln703_10_fu_361_p1 );
    sensitive << ( trunc_ln_fu_351_p4 );

    SC_METHOD(thread_add_ln703_33_fu_961_p2);
    sensitive << ( sext_ln1118_17_fu_946_p1 );
    sensitive << ( sext_ln1118_18_fu_949_p1 );

    SC_METHOD(thread_add_ln703_34_fu_971_p2);
    sensitive << ( sext_ln703_27_fu_958_p1 );
    sensitive << ( sext_ln1118_19_fu_952_p1 );

    SC_METHOD(thread_add_ln703_36_fu_990_p2);
    sensitive << ( zext_ln708_fu_987_p1 );
    sensitive << ( sext_ln703_26_fu_955_p1 );

    SC_METHOD(thread_add_ln703_37_fu_454_p2);
    sensitive << ( zext_ln703_12_fu_450_p1 );

    SC_METHOD(thread_add_ln703_38_fu_464_p2);
    sensitive << ( zext_ln1118_48_fu_440_p1 );
    sensitive << ( sext_ln703_fu_460_p1 );

    SC_METHOD(thread_add_ln703_40_fu_1011_p2);
    sensitive << ( sext_ln1118_20_fu_1008_p1 );
    sensitive << ( sext_ln708_fu_1005_p1 );

    SC_METHOD(thread_add_ln703_41_fu_505_p2);
    sensitive << ( trunc_ln1_reg_1312 );

    SC_METHOD(thread_add_ln703_42_fu_514_p2);
    sensitive << ( zext_ln703_13_fu_502_p1 );
    sensitive << ( zext_ln703_14_fu_510_p1 );

    SC_METHOD(thread_add_ln703_44_fu_619_p2);
    sensitive << ( sext_ln708_1_fu_578_p1 );
    sensitive << ( sext_ln1118_21_fu_548_p1 );

    SC_METHOD(thread_add_ln703_45_fu_625_p2);
    sensitive << ( trunc_ln1118_6_reg_1323 );

    SC_METHOD(thread_add_ln703_46_fu_1039_p2);
    sensitive << ( sext_ln703_32_fu_1030_p1 );
    sensitive << ( zext_ln703_17_fu_1036_p1 );

    SC_METHOD(thread_add_ln703_48_fu_1057_p2);
    sensitive << ( sext_ln1118_23_fu_1054_p1 );
    sensitive << ( sext_ln1118_22_fu_1051_p1 );

    SC_METHOD(thread_add_ln703_49_fu_720_p2);
    sensitive << ( lshr_ln708_6_reg_1317 );

    SC_METHOD(thread_add_ln703_50_fu_729_p2);
    sensitive << ( sext_ln703_34_fu_716_p1 );
    sensitive << ( sext_ln703_35_fu_725_p1 );

    SC_METHOD(thread_add_ln703_52_fu_1078_p2);
    sensitive << ( sext_ln708_2_fu_1075_p1 );
    sensitive << ( sext_ln1118_24_fu_1072_p1 );

    SC_METHOD(thread_add_ln703_53_fu_823_p2);
    sensitive << ( trunc_ln1118_7_reg_1328 );

    SC_METHOD(thread_add_ln703_54_fu_832_p2);
    sensitive << ( sext_ln703_37_fu_819_p1 );
    sensitive << ( zext_ln703_18_fu_828_p1 );

    SC_METHOD(thread_add_ln703_56_fu_909_p2);
    sensitive << ( zext_ln708_7_fu_886_p1 );
    sensitive << ( sext_ln1118_25_fu_866_p1 );

    SC_METHOD(thread_add_ln703_57_fu_915_p2);
    sensitive << ( zext_ln1118_40_fu_317_p1 );

    SC_METHOD(thread_add_ln703_58_fu_1102_p2);
    sensitive << ( zext_ln708_9_fu_1093_p1 );
    sensitive << ( sext_ln703_4_fu_1099_p1 );

    SC_METHOD(thread_add_ln703_fu_927_p2);
    sensitive << ( zext_ln1118_55_fu_921_p1 );
    sensitive << ( sext_ln1118_16_fu_924_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( sext_ln728_fu_1126_p1 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( sext_ln728_4_fu_1138_p1 );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( sext_ln728_5_fu_1150_p1 );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( sext_ln728_6_fu_1162_p1 );

    SC_METHOD(thread_ap_return_4);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( sext_ln728_7_fu_1174_p1 );

    SC_METHOD(thread_ap_return_5);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( sext_ln728_8_fu_1186_p1 );

    SC_METHOD(thread_ap_return_6);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( sext_ln728_9_fu_1198_p1 );

    SC_METHOD(thread_ap_return_7);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( res_7_V_write_assign_fu_1202_p3 );

    SC_METHOD(thread_mul_ln1118_3_fu_386_p0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( mul_ln1118_3_fu_386_p00 );

    SC_METHOD(thread_mul_ln1118_3_fu_386_p00);
    sensitive << ( p_read1 );

    SC_METHOD(thread_mul_ln1118_3_fu_386_p2);
    sensitive << ( mul_ln1118_3_fu_386_p0 );

    SC_METHOD(thread_mul_ln1118_4_fu_470_p0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( mul_ln1118_4_fu_470_p00 );

    SC_METHOD(thread_mul_ln1118_4_fu_470_p00);
    sensitive << ( p_read );

    SC_METHOD(thread_mul_ln1118_4_fu_470_p2);
    sensitive << ( mul_ln1118_4_fu_470_p0 );

    SC_METHOD(thread_mul_ln1118_5_fu_486_p0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( mul_ln1118_5_fu_486_p00 );

    SC_METHOD(thread_mul_ln1118_5_fu_486_p00);
    sensitive << ( p_read2 );

    SC_METHOD(thread_mul_ln1118_5_fu_486_p2);
    sensitive << ( mul_ln1118_5_fu_486_p0 );

    SC_METHOD(thread_mul_ln1118_fu_370_p0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln1118_fu_248_p1 );

    SC_METHOD(thread_mul_ln1118_fu_370_p2);
    sensitive << ( mul_ln1118_fu_370_p0 );

    SC_METHOD(thread_mul_ln708_2_fu_424_p0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln1118_fu_248_p1 );

    SC_METHOD(thread_mul_ln708_2_fu_424_p2);
    sensitive << ( mul_ln708_2_fu_424_p0 );

    SC_METHOD(thread_mul_ln708_3_fu_184_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mul_ln708_3_fu_184_p00 );

    SC_METHOD(thread_mul_ln708_3_fu_184_p00);
    sensitive << ( p_read1 );

    SC_METHOD(thread_mul_ln708_3_fu_184_p2);
    sensitive << ( mul_ln708_3_fu_184_p0 );

    SC_METHOD(thread_mul_ln708_4_fu_216_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( zext_ln1118_42_fu_138_p1 );

    SC_METHOD(thread_mul_ln708_4_fu_216_p2);
    sensitive << ( mul_ln708_4_fu_216_p0 );

    SC_METHOD(thread_mul_ln708_5_fu_232_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( zext_ln1118_42_fu_138_p1 );

    SC_METHOD(thread_mul_ln708_5_fu_232_p2);
    sensitive << ( mul_ln708_5_fu_232_p0 );

    SC_METHOD(thread_mul_ln708_6_fu_893_p0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( mul_ln708_6_fu_893_p00 );

    SC_METHOD(thread_mul_ln708_6_fu_893_p00);
    sensitive << ( p_read3 );

    SC_METHOD(thread_mul_ln708_6_fu_893_p2);
    sensitive << ( mul_ln708_6_fu_893_p0 );

    SC_METHOD(thread_mul_ln708_fu_260_p0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln1118_34_fu_252_p1 );

    SC_METHOD(thread_mul_ln708_fu_260_p2);
    sensitive << ( mul_ln708_fu_260_p0 );

    SC_METHOD(thread_p_Val2_s_fu_940_p2);
    sensitive << ( sext_ln703_25_fu_933_p1 );
    sensitive << ( zext_ln703_15_fu_937_p1 );

    SC_METHOD(thread_res_7_V_write_assign_fu_1202_p3);
    sensitive << ( acc_7_V_fu_1112_p2 );

    SC_METHOD(thread_sext_ln1118_16_fu_924_p1);
    sensitive << ( tmp_155_reg_1338 );

    SC_METHOD(thread_sext_ln1118_17_fu_946_p1);
    sensitive << ( tmp_156_reg_1348 );

    SC_METHOD(thread_sext_ln1118_18_fu_949_p1);
    sensitive << ( tmp_157_reg_1353 );

    SC_METHOD(thread_sext_ln1118_19_fu_952_p1);
    sensitive << ( tmp_158_reg_1358 );

    SC_METHOD(thread_sext_ln1118_1_fu_757_p1);
    sensitive << ( sub_ln1118_23_fu_751_p2 );

    SC_METHOD(thread_sext_ln1118_20_fu_1008_p1);
    sensitive << ( tmp_162_reg_1378 );

    SC_METHOD(thread_sext_ln1118_21_fu_548_p1);
    sensitive << ( tmp_163_fu_538_p4 );

    SC_METHOD(thread_sext_ln1118_22_fu_1051_p1);
    sensitive << ( tmp_166_reg_1403 );

    SC_METHOD(thread_sext_ln1118_23_fu_1054_p1);
    sensitive << ( tmp_167_reg_1408 );

    SC_METHOD(thread_sext_ln1118_24_fu_1072_p1);
    sensitive << ( tmp_169_reg_1418 );

    SC_METHOD(thread_sext_ln1118_25_fu_866_p1);
    sensitive << ( tmp_172_fu_856_p4 );

    SC_METHOD(thread_sext_ln1118_fu_599_p1);
    sensitive << ( sub_ln1118_17_fu_593_p2 );

    SC_METHOD(thread_sext_ln703_25_fu_933_p1);
    sensitive << ( add_ln703_fu_927_p2 );

    SC_METHOD(thread_sext_ln703_26_fu_955_p1);
    sensitive << ( tmp_159_reg_1301 );

    SC_METHOD(thread_sext_ln703_27_fu_958_p1);
    sensitive << ( tmp_159_reg_1301 );

    SC_METHOD(thread_sext_ln703_28_fu_967_p1);
    sensitive << ( add_ln703_33_fu_961_p2 );

    SC_METHOD(thread_sext_ln703_29_fu_977_p1);
    sensitive << ( add_ln703_34_fu_971_p2 );

    SC_METHOD(thread_sext_ln703_30_fu_996_p1);
    sensitive << ( add_ln703_38_reg_1368 );

    SC_METHOD(thread_sext_ln703_31_fu_1017_p1);
    sensitive << ( add_ln703_40_fu_1011_p2 );

    SC_METHOD(thread_sext_ln703_32_fu_1030_p1);
    sensitive << ( tmp_165_reg_1388 );

    SC_METHOD(thread_sext_ln703_33_fu_1033_p1);
    sensitive << ( add_ln703_44_reg_1393 );

    SC_METHOD(thread_sext_ln703_34_fu_716_p1);
    sensitive << ( tmp_168_fu_706_p4 );

    SC_METHOD(thread_sext_ln703_35_fu_725_p1);
    sensitive << ( add_ln703_49_fu_720_p2 );

    SC_METHOD(thread_sext_ln703_36_fu_1063_p1);
    sensitive << ( add_ln703_50_reg_1413 );

    SC_METHOD(thread_sext_ln703_37_fu_819_p1);
    sensitive << ( tmp_171_fu_809_p4 );

    SC_METHOD(thread_sext_ln703_38_fu_1084_p1);
    sensitive << ( add_ln703_54_reg_1428 );

    SC_METHOD(thread_sext_ln703_39_fu_1096_p1);
    sensitive << ( add_ln703_56_reg_1438 );

    SC_METHOD(thread_sext_ln703_4_fu_1099_p1);
    sensitive << ( add_ln703_57_reg_1443 );

    SC_METHOD(thread_sext_ln703_5_fu_1108_p1);
    sensitive << ( add_ln703_58_fu_1102_p2 );

    SC_METHOD(thread_sext_ln703_fu_460_p1);
    sensitive << ( add_ln703_37_fu_454_p2 );

    SC_METHOD(thread_sext_ln708_1_fu_578_p1);
    sensitive << ( tmp_164_fu_568_p4 );

    SC_METHOD(thread_sext_ln708_2_fu_1075_p1);
    sensitive << ( tmp_170_reg_1423 );

    SC_METHOD(thread_sext_ln708_fu_1005_p1);
    sensitive << ( tmp_161_reg_1373 );

    SC_METHOD(thread_sext_ln728_4_fu_1138_p1);
    sensitive << ( tmp_175_fu_1130_p3 );

    SC_METHOD(thread_sext_ln728_5_fu_1150_p1);
    sensitive << ( tmp_176_fu_1142_p3 );

    SC_METHOD(thread_sext_ln728_6_fu_1162_p1);
    sensitive << ( tmp_177_fu_1154_p3 );

    SC_METHOD(thread_sext_ln728_7_fu_1174_p1);
    sensitive << ( tmp_178_fu_1166_p3 );

    SC_METHOD(thread_sext_ln728_8_fu_1186_p1);
    sensitive << ( tmp_179_fu_1178_p3 );

    SC_METHOD(thread_sext_ln728_9_fu_1198_p1);
    sensitive << ( tmp_180_fu_1190_p3 );

    SC_METHOD(thread_sext_ln728_fu_1126_p1);
    sensitive << ( tmp_174_fu_1118_p3 );

    SC_METHOD(thread_shl_ln1118_11_fu_323_p3);
    sensitive << ( p_read2 );

    SC_METHOD(thread_shl_ln1118_12_fu_334_p3);
    sensitive << ( p_read2 );

    SC_METHOD(thread_shl_ln1118_13_fu_146_p3);
    sensitive << ( p_read3 );

    SC_METHOD(thread_shl_ln1118_14_fu_582_p3);
    sensitive << ( p_read3 );

    SC_METHOD(thread_shl_ln1118_15_fu_630_p3);
    sensitive << ( p_read );

    SC_METHOD(thread_shl_ln1118_16_fu_642_p3);
    sensitive << ( p_read );

    SC_METHOD(thread_shl_ln1118_17_fu_674_p3);
    sensitive << ( p_read1 );

    SC_METHOD(thread_shl_ln1118_18_fu_761_p3);
    sensitive << ( p_read1 );

    SC_METHOD(thread_shl_ln1118_19_fu_792_p3);
    sensitive << ( p_read3 );

    SC_METHOD(thread_shl_ln1118_20_fu_838_p3);
    sensitive << ( p_read );

    SC_METHOD(thread_shl_ln1118_s_fu_290_p3);
    sensitive << ( p_read1 );

    SC_METHOD(thread_shl_ln3_fu_443_p3);
    sensitive << ( p_read2 );

    SC_METHOD(thread_shl_ln_fu_279_p3);
    sensitive << ( p_read1 );

    SC_METHOD(thread_sub_ln1118_13_fu_402_p2);
    sensitive << ( zext_ln1118_43_fu_330_p1 );
    sensitive << ( zext_ln1118_44_fu_341_p1 );

    SC_METHOD(thread_sub_ln1118_14_fu_158_p2);
    sensitive << ( zext_ln1118_47_fu_154_p1 );

    SC_METHOD(thread_sub_ln1118_15_fu_532_p2);
    sensitive << ( zext_ln1118_34_fu_252_p1 );
    sensitive << ( zext_ln1118_49_fu_528_p1 );

    SC_METHOD(thread_sub_ln1118_16_fu_563_p2);
    sensitive << ( zext_ln1118_37_reg_1285 );
    sensitive << ( zext_ln1118_50_fu_559_p1 );

    SC_METHOD(thread_sub_ln1118_17_fu_593_p2);
    sensitive << ( zext_ln1118_51_fu_589_p1 );

    SC_METHOD(thread_sub_ln1118_18_fu_603_p2);
    sensitive << ( sext_ln1118_fu_599_p1 );
    sensitive << ( zext_ln1118_46_fu_421_p1 );

    SC_METHOD(thread_sub_ln1118_19_fu_658_p2);
    sensitive << ( zext_ln1118_52_fu_638_p1 );
    sensitive << ( zext_ln1118_54_fu_654_p1 );

    SC_METHOD(thread_sub_ln1118_20_fu_685_p2);
    sensitive << ( zext_ln1118_50_fu_559_p1 );
    sensitive << ( zext_ln1118_56_fu_681_p1 );

    SC_METHOD(thread_sub_ln1118_21_fu_701_p2);
    sensitive << ( zext_ln1118_42_reg_1290 );
    sensitive << ( zext_ln1118_43_fu_330_p1 );

    SC_METHOD(thread_sub_ln1118_22_fu_735_p2);
    sensitive << ( zext_ln1118_53_fu_650_p1 );

    SC_METHOD(thread_sub_ln1118_23_fu_751_p2);
    sensitive << ( zext_ln1118_38_fu_286_p1 );

    SC_METHOD(thread_sub_ln1118_24_fu_776_p2);
    sensitive << ( sext_ln1118_1_fu_757_p1 );
    sensitive << ( zext_ln1118_58_fu_772_p1 );

    SC_METHOD(thread_sub_ln1118_25_fu_803_p2);
    sensitive << ( zext_ln1118_59_fu_799_p1 );
    sensitive << ( zext_ln1118_45_fu_418_p1 );

    SC_METHOD(thread_sub_ln1118_26_fu_850_p2);
    sensitive << ( zext_ln1118_60_fu_846_p1 );

    SC_METHOD(thread_sub_ln1118_fu_301_p2);
    sensitive << ( zext_ln1118_39_fu_297_p1 );
    sensitive << ( zext_ln1118_38_fu_286_p1 );

    SC_METHOD(thread_tmp_163_fu_538_p4);
    sensitive << ( sub_ln1118_15_fu_532_p2 );

    SC_METHOD(thread_tmp_164_fu_568_p4);
    sensitive << ( sub_ln1118_16_fu_563_p2 );

    SC_METHOD(thread_tmp_168_fu_706_p4);
    sensitive << ( sub_ln1118_21_fu_701_p2 );

    SC_METHOD(thread_tmp_171_fu_809_p4);
    sensitive << ( sub_ln1118_25_fu_803_p2 );

    SC_METHOD(thread_tmp_172_fu_856_p4);
    sensitive << ( sub_ln1118_26_fu_850_p2 );

    SC_METHOD(thread_tmp_173_fu_876_p4);
    sensitive << ( add_ln1118_6_fu_870_p2 );

    SC_METHOD(thread_tmp_174_fu_1118_p3);
    sensitive << ( p_Val2_s_fu_940_p2 );

    SC_METHOD(thread_tmp_175_fu_1130_p3);
    sensitive << ( acc_1_V_fu_981_p2 );

    SC_METHOD(thread_tmp_176_fu_1142_p3);
    sensitive << ( acc_2_V_fu_999_p2 );

    SC_METHOD(thread_tmp_177_fu_1154_p3);
    sensitive << ( acc_3_V_fu_1024_p2 );

    SC_METHOD(thread_tmp_178_fu_1166_p3);
    sensitive << ( acc_4_V_fu_1045_p2 );

    SC_METHOD(thread_tmp_179_fu_1178_p3);
    sensitive << ( acc_5_V_fu_1066_p2 );

    SC_METHOD(thread_tmp_180_fu_1190_p3);
    sensitive << ( acc_6_V_fu_1087_p2 );

    SC_METHOD(thread_tmp_4_fu_552_p3);
    sensitive << ( p_read1 );

    SC_METHOD(thread_tmp_fu_520_p3);
    sensitive << ( p_read );

    SC_METHOD(thread_trunc_ln_fu_351_p4);
    sensitive << ( add_ln1118_fu_345_p2 );

    SC_METHOD(thread_zext_ln1118_34_fu_252_p1);
    sensitive << ( p_read );

    SC_METHOD(thread_zext_ln1118_37_fu_134_p1);
    sensitive << ( p_read1 );

    SC_METHOD(thread_zext_ln1118_38_fu_286_p1);
    sensitive << ( shl_ln_fu_279_p3 );

    SC_METHOD(thread_zext_ln1118_39_fu_297_p1);
    sensitive << ( shl_ln1118_s_fu_290_p3 );

    SC_METHOD(thread_zext_ln1118_40_fu_317_p1);
    sensitive << ( p_read2 );

    SC_METHOD(thread_zext_ln1118_42_fu_138_p1);
    sensitive << ( p_read2 );

    SC_METHOD(thread_zext_ln1118_43_fu_330_p1);
    sensitive << ( shl_ln1118_11_fu_323_p3 );

    SC_METHOD(thread_zext_ln1118_44_fu_341_p1);
    sensitive << ( shl_ln1118_12_fu_334_p3 );

    SC_METHOD(thread_zext_ln1118_45_fu_418_p1);
    sensitive << ( shl_ln1118_13_reg_1295 );

    SC_METHOD(thread_zext_ln1118_46_fu_421_p1);
    sensitive << ( shl_ln1118_13_reg_1295 );

    SC_METHOD(thread_zext_ln1118_47_fu_154_p1);
    sensitive << ( shl_ln1118_13_fu_146_p3 );

    SC_METHOD(thread_zext_ln1118_48_fu_440_p1);
    sensitive << ( lshr_ln708_5_reg_1307 );

    SC_METHOD(thread_zext_ln1118_49_fu_528_p1);
    sensitive << ( tmp_fu_520_p3 );

    SC_METHOD(thread_zext_ln1118_50_fu_559_p1);
    sensitive << ( tmp_4_fu_552_p3 );

    SC_METHOD(thread_zext_ln1118_51_fu_589_p1);
    sensitive << ( shl_ln1118_14_fu_582_p3 );

    SC_METHOD(thread_zext_ln1118_52_fu_638_p1);
    sensitive << ( shl_ln1118_15_fu_630_p3 );

    SC_METHOD(thread_zext_ln1118_53_fu_650_p1);
    sensitive << ( shl_ln1118_16_fu_642_p3 );

    SC_METHOD(thread_zext_ln1118_54_fu_654_p1);
    sensitive << ( shl_ln1118_16_fu_642_p3 );

    SC_METHOD(thread_zext_ln1118_55_fu_921_p1);
    sensitive << ( tmp_154_reg_1333 );

    SC_METHOD(thread_zext_ln1118_56_fu_681_p1);
    sensitive << ( shl_ln1118_17_fu_674_p3 );

    SC_METHOD(thread_zext_ln1118_57_fu_768_p1);
    sensitive << ( shl_ln1118_18_fu_761_p3 );

    SC_METHOD(thread_zext_ln1118_58_fu_772_p1);
    sensitive << ( shl_ln1118_18_fu_761_p3 );

    SC_METHOD(thread_zext_ln1118_59_fu_799_p1);
    sensitive << ( shl_ln1118_19_fu_792_p3 );

    SC_METHOD(thread_zext_ln1118_60_fu_846_p1);
    sensitive << ( shl_ln1118_20_fu_838_p3 );

    SC_METHOD(thread_zext_ln1118_fu_248_p1);
    sensitive << ( p_read );

    SC_METHOD(thread_zext_ln703_10_fu_361_p1);
    sensitive << ( p_read3 );

    SC_METHOD(thread_zext_ln703_12_fu_450_p1);
    sensitive << ( shl_ln3_fu_443_p3 );

    SC_METHOD(thread_zext_ln703_13_fu_502_p1);
    sensitive << ( lshr_ln708_6_reg_1317 );

    SC_METHOD(thread_zext_ln703_14_fu_510_p1);
    sensitive << ( add_ln703_41_fu_505_p2 );

    SC_METHOD(thread_zext_ln703_15_fu_937_p1);
    sensitive << ( add_ln703_31_reg_1343 );

    SC_METHOD(thread_zext_ln703_16_fu_1021_p1);
    sensitive << ( add_ln703_42_reg_1383 );

    SC_METHOD(thread_zext_ln703_17_fu_1036_p1);
    sensitive << ( add_ln703_45_reg_1398 );

    SC_METHOD(thread_zext_ln703_18_fu_828_p1);
    sensitive << ( add_ln703_53_fu_823_p2 );

    SC_METHOD(thread_zext_ln703_fu_142_p1);
    sensitive << ( p_read3 );

    SC_METHOD(thread_zext_ln708_7_fu_886_p1);
    sensitive << ( tmp_173_fu_876_p4 );

    SC_METHOD(thread_zext_ln708_9_fu_1093_p1);
    sensitive << ( lshr_ln708_8_reg_1433 );

    SC_METHOD(thread_zext_ln708_fu_987_p1);
    sensitive << ( tmp_160_reg_1363 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, p_read, "(port)p_read");
    sc_trace(mVcdFile, p_read1, "(port)p_read1");
    sc_trace(mVcdFile, p_read2, "(port)p_read2");
    sc_trace(mVcdFile, p_read3, "(port)p_read3");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_return_4, "(port)ap_return_4");
    sc_trace(mVcdFile, ap_return_5, "(port)ap_return_5");
    sc_trace(mVcdFile, ap_return_6, "(port)ap_return_6");
    sc_trace(mVcdFile, ap_return_7, "(port)ap_return_7");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, zext_ln1118_37_fu_134_p1, "zext_ln1118_37_fu_134_p1");
    sc_trace(mVcdFile, zext_ln1118_37_reg_1285, "zext_ln1118_37_reg_1285");
    sc_trace(mVcdFile, zext_ln1118_42_fu_138_p1, "zext_ln1118_42_fu_138_p1");
    sc_trace(mVcdFile, zext_ln1118_42_reg_1290, "zext_ln1118_42_reg_1290");
    sc_trace(mVcdFile, shl_ln1118_13_fu_146_p3, "shl_ln1118_13_fu_146_p3");
    sc_trace(mVcdFile, shl_ln1118_13_reg_1295, "shl_ln1118_13_reg_1295");
    sc_trace(mVcdFile, tmp_159_reg_1301, "tmp_159_reg_1301");
    sc_trace(mVcdFile, lshr_ln708_5_reg_1307, "lshr_ln708_5_reg_1307");
    sc_trace(mVcdFile, trunc_ln1_reg_1312, "trunc_ln1_reg_1312");
    sc_trace(mVcdFile, lshr_ln708_6_reg_1317, "lshr_ln708_6_reg_1317");
    sc_trace(mVcdFile, trunc_ln1118_6_reg_1323, "trunc_ln1118_6_reg_1323");
    sc_trace(mVcdFile, trunc_ln1118_7_reg_1328, "trunc_ln1118_7_reg_1328");
    sc_trace(mVcdFile, tmp_154_reg_1333, "tmp_154_reg_1333");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_155_reg_1338, "tmp_155_reg_1338");
    sc_trace(mVcdFile, add_ln703_31_fu_364_p2, "add_ln703_31_fu_364_p2");
    sc_trace(mVcdFile, add_ln703_31_reg_1343, "add_ln703_31_reg_1343");
    sc_trace(mVcdFile, tmp_156_reg_1348, "tmp_156_reg_1348");
    sc_trace(mVcdFile, tmp_157_reg_1353, "tmp_157_reg_1353");
    sc_trace(mVcdFile, tmp_158_reg_1358, "tmp_158_reg_1358");
    sc_trace(mVcdFile, tmp_160_reg_1363, "tmp_160_reg_1363");
    sc_trace(mVcdFile, add_ln703_38_fu_464_p2, "add_ln703_38_fu_464_p2");
    sc_trace(mVcdFile, add_ln703_38_reg_1368, "add_ln703_38_reg_1368");
    sc_trace(mVcdFile, tmp_161_reg_1373, "tmp_161_reg_1373");
    sc_trace(mVcdFile, tmp_162_reg_1378, "tmp_162_reg_1378");
    sc_trace(mVcdFile, add_ln703_42_fu_514_p2, "add_ln703_42_fu_514_p2");
    sc_trace(mVcdFile, add_ln703_42_reg_1383, "add_ln703_42_reg_1383");
    sc_trace(mVcdFile, tmp_165_reg_1388, "tmp_165_reg_1388");
    sc_trace(mVcdFile, add_ln703_44_fu_619_p2, "add_ln703_44_fu_619_p2");
    sc_trace(mVcdFile, add_ln703_44_reg_1393, "add_ln703_44_reg_1393");
    sc_trace(mVcdFile, add_ln703_45_fu_625_p2, "add_ln703_45_fu_625_p2");
    sc_trace(mVcdFile, add_ln703_45_reg_1398, "add_ln703_45_reg_1398");
    sc_trace(mVcdFile, tmp_166_reg_1403, "tmp_166_reg_1403");
    sc_trace(mVcdFile, tmp_167_reg_1408, "tmp_167_reg_1408");
    sc_trace(mVcdFile, add_ln703_50_fu_729_p2, "add_ln703_50_fu_729_p2");
    sc_trace(mVcdFile, add_ln703_50_reg_1413, "add_ln703_50_reg_1413");
    sc_trace(mVcdFile, tmp_169_reg_1418, "tmp_169_reg_1418");
    sc_trace(mVcdFile, tmp_170_reg_1423, "tmp_170_reg_1423");
    sc_trace(mVcdFile, add_ln703_54_fu_832_p2, "add_ln703_54_fu_832_p2");
    sc_trace(mVcdFile, add_ln703_54_reg_1428, "add_ln703_54_reg_1428");
    sc_trace(mVcdFile, lshr_ln708_8_reg_1433, "lshr_ln708_8_reg_1433");
    sc_trace(mVcdFile, add_ln703_56_fu_909_p2, "add_ln703_56_fu_909_p2");
    sc_trace(mVcdFile, add_ln703_56_reg_1438, "add_ln703_56_reg_1438");
    sc_trace(mVcdFile, add_ln703_57_fu_915_p2, "add_ln703_57_fu_915_p2");
    sc_trace(mVcdFile, add_ln703_57_reg_1443, "add_ln703_57_reg_1443");
    sc_trace(mVcdFile, zext_ln1118_47_fu_154_p1, "zext_ln1118_47_fu_154_p1");
    sc_trace(mVcdFile, sub_ln1118_14_fu_158_p2, "sub_ln1118_14_fu_158_p2");
    sc_trace(mVcdFile, mul_ln708_3_fu_184_p0, "mul_ln708_3_fu_184_p0");
    sc_trace(mVcdFile, mul_ln708_3_fu_184_p2, "mul_ln708_3_fu_184_p2");
    sc_trace(mVcdFile, zext_ln703_fu_142_p1, "zext_ln703_fu_142_p1");
    sc_trace(mVcdFile, add_ln1118_5_fu_200_p2, "add_ln1118_5_fu_200_p2");
    sc_trace(mVcdFile, mul_ln708_4_fu_216_p0, "mul_ln708_4_fu_216_p0");
    sc_trace(mVcdFile, mul_ln708_4_fu_216_p2, "mul_ln708_4_fu_216_p2");
    sc_trace(mVcdFile, mul_ln708_5_fu_232_p0, "mul_ln708_5_fu_232_p0");
    sc_trace(mVcdFile, mul_ln708_5_fu_232_p2, "mul_ln708_5_fu_232_p2");
    sc_trace(mVcdFile, mul_ln708_fu_260_p0, "mul_ln708_fu_260_p0");
    sc_trace(mVcdFile, zext_ln1118_34_fu_252_p1, "zext_ln1118_34_fu_252_p1");
    sc_trace(mVcdFile, mul_ln708_fu_260_p2, "mul_ln708_fu_260_p2");
    sc_trace(mVcdFile, shl_ln_fu_279_p3, "shl_ln_fu_279_p3");
    sc_trace(mVcdFile, shl_ln1118_s_fu_290_p3, "shl_ln1118_s_fu_290_p3");
    sc_trace(mVcdFile, zext_ln1118_39_fu_297_p1, "zext_ln1118_39_fu_297_p1");
    sc_trace(mVcdFile, zext_ln1118_38_fu_286_p1, "zext_ln1118_38_fu_286_p1");
    sc_trace(mVcdFile, sub_ln1118_fu_301_p2, "sub_ln1118_fu_301_p2");
    sc_trace(mVcdFile, shl_ln1118_11_fu_323_p3, "shl_ln1118_11_fu_323_p3");
    sc_trace(mVcdFile, shl_ln1118_12_fu_334_p3, "shl_ln1118_12_fu_334_p3");
    sc_trace(mVcdFile, zext_ln1118_43_fu_330_p1, "zext_ln1118_43_fu_330_p1");
    sc_trace(mVcdFile, zext_ln1118_44_fu_341_p1, "zext_ln1118_44_fu_341_p1");
    sc_trace(mVcdFile, add_ln1118_fu_345_p2, "add_ln1118_fu_345_p2");
    sc_trace(mVcdFile, zext_ln703_10_fu_361_p1, "zext_ln703_10_fu_361_p1");
    sc_trace(mVcdFile, trunc_ln_fu_351_p4, "trunc_ln_fu_351_p4");
    sc_trace(mVcdFile, mul_ln1118_fu_370_p0, "mul_ln1118_fu_370_p0");
    sc_trace(mVcdFile, zext_ln1118_fu_248_p1, "zext_ln1118_fu_248_p1");
    sc_trace(mVcdFile, mul_ln1118_fu_370_p2, "mul_ln1118_fu_370_p2");
    sc_trace(mVcdFile, mul_ln1118_3_fu_386_p0, "mul_ln1118_3_fu_386_p0");
    sc_trace(mVcdFile, mul_ln1118_3_fu_386_p2, "mul_ln1118_3_fu_386_p2");
    sc_trace(mVcdFile, sub_ln1118_13_fu_402_p2, "sub_ln1118_13_fu_402_p2");
    sc_trace(mVcdFile, mul_ln708_2_fu_424_p0, "mul_ln708_2_fu_424_p0");
    sc_trace(mVcdFile, mul_ln708_2_fu_424_p2, "mul_ln708_2_fu_424_p2");
    sc_trace(mVcdFile, shl_ln3_fu_443_p3, "shl_ln3_fu_443_p3");
    sc_trace(mVcdFile, zext_ln703_12_fu_450_p1, "zext_ln703_12_fu_450_p1");
    sc_trace(mVcdFile, add_ln703_37_fu_454_p2, "add_ln703_37_fu_454_p2");
    sc_trace(mVcdFile, zext_ln1118_48_fu_440_p1, "zext_ln1118_48_fu_440_p1");
    sc_trace(mVcdFile, sext_ln703_fu_460_p1, "sext_ln703_fu_460_p1");
    sc_trace(mVcdFile, mul_ln1118_4_fu_470_p0, "mul_ln1118_4_fu_470_p0");
    sc_trace(mVcdFile, mul_ln1118_4_fu_470_p2, "mul_ln1118_4_fu_470_p2");
    sc_trace(mVcdFile, mul_ln1118_5_fu_486_p0, "mul_ln1118_5_fu_486_p0");
    sc_trace(mVcdFile, mul_ln1118_5_fu_486_p2, "mul_ln1118_5_fu_486_p2");
    sc_trace(mVcdFile, add_ln703_41_fu_505_p2, "add_ln703_41_fu_505_p2");
    sc_trace(mVcdFile, zext_ln703_13_fu_502_p1, "zext_ln703_13_fu_502_p1");
    sc_trace(mVcdFile, zext_ln703_14_fu_510_p1, "zext_ln703_14_fu_510_p1");
    sc_trace(mVcdFile, tmp_fu_520_p3, "tmp_fu_520_p3");
    sc_trace(mVcdFile, zext_ln1118_49_fu_528_p1, "zext_ln1118_49_fu_528_p1");
    sc_trace(mVcdFile, sub_ln1118_15_fu_532_p2, "sub_ln1118_15_fu_532_p2");
    sc_trace(mVcdFile, tmp_163_fu_538_p4, "tmp_163_fu_538_p4");
    sc_trace(mVcdFile, tmp_4_fu_552_p3, "tmp_4_fu_552_p3");
    sc_trace(mVcdFile, zext_ln1118_50_fu_559_p1, "zext_ln1118_50_fu_559_p1");
    sc_trace(mVcdFile, sub_ln1118_16_fu_563_p2, "sub_ln1118_16_fu_563_p2");
    sc_trace(mVcdFile, tmp_164_fu_568_p4, "tmp_164_fu_568_p4");
    sc_trace(mVcdFile, shl_ln1118_14_fu_582_p3, "shl_ln1118_14_fu_582_p3");
    sc_trace(mVcdFile, zext_ln1118_51_fu_589_p1, "zext_ln1118_51_fu_589_p1");
    sc_trace(mVcdFile, sub_ln1118_17_fu_593_p2, "sub_ln1118_17_fu_593_p2");
    sc_trace(mVcdFile, sext_ln1118_fu_599_p1, "sext_ln1118_fu_599_p1");
    sc_trace(mVcdFile, zext_ln1118_46_fu_421_p1, "zext_ln1118_46_fu_421_p1");
    sc_trace(mVcdFile, sub_ln1118_18_fu_603_p2, "sub_ln1118_18_fu_603_p2");
    sc_trace(mVcdFile, sext_ln708_1_fu_578_p1, "sext_ln708_1_fu_578_p1");
    sc_trace(mVcdFile, sext_ln1118_21_fu_548_p1, "sext_ln1118_21_fu_548_p1");
    sc_trace(mVcdFile, shl_ln1118_15_fu_630_p3, "shl_ln1118_15_fu_630_p3");
    sc_trace(mVcdFile, shl_ln1118_16_fu_642_p3, "shl_ln1118_16_fu_642_p3");
    sc_trace(mVcdFile, zext_ln1118_52_fu_638_p1, "zext_ln1118_52_fu_638_p1");
    sc_trace(mVcdFile, zext_ln1118_54_fu_654_p1, "zext_ln1118_54_fu_654_p1");
    sc_trace(mVcdFile, sub_ln1118_19_fu_658_p2, "sub_ln1118_19_fu_658_p2");
    sc_trace(mVcdFile, shl_ln1118_17_fu_674_p3, "shl_ln1118_17_fu_674_p3");
    sc_trace(mVcdFile, zext_ln1118_56_fu_681_p1, "zext_ln1118_56_fu_681_p1");
    sc_trace(mVcdFile, sub_ln1118_20_fu_685_p2, "sub_ln1118_20_fu_685_p2");
    sc_trace(mVcdFile, sub_ln1118_21_fu_701_p2, "sub_ln1118_21_fu_701_p2");
    sc_trace(mVcdFile, tmp_168_fu_706_p4, "tmp_168_fu_706_p4");
    sc_trace(mVcdFile, add_ln703_49_fu_720_p2, "add_ln703_49_fu_720_p2");
    sc_trace(mVcdFile, sext_ln703_34_fu_716_p1, "sext_ln703_34_fu_716_p1");
    sc_trace(mVcdFile, sext_ln703_35_fu_725_p1, "sext_ln703_35_fu_725_p1");
    sc_trace(mVcdFile, zext_ln1118_53_fu_650_p1, "zext_ln1118_53_fu_650_p1");
    sc_trace(mVcdFile, sub_ln1118_22_fu_735_p2, "sub_ln1118_22_fu_735_p2");
    sc_trace(mVcdFile, sub_ln1118_23_fu_751_p2, "sub_ln1118_23_fu_751_p2");
    sc_trace(mVcdFile, shl_ln1118_18_fu_761_p3, "shl_ln1118_18_fu_761_p3");
    sc_trace(mVcdFile, sext_ln1118_1_fu_757_p1, "sext_ln1118_1_fu_757_p1");
    sc_trace(mVcdFile, zext_ln1118_58_fu_772_p1, "zext_ln1118_58_fu_772_p1");
    sc_trace(mVcdFile, sub_ln1118_24_fu_776_p2, "sub_ln1118_24_fu_776_p2");
    sc_trace(mVcdFile, shl_ln1118_19_fu_792_p3, "shl_ln1118_19_fu_792_p3");
    sc_trace(mVcdFile, zext_ln1118_59_fu_799_p1, "zext_ln1118_59_fu_799_p1");
    sc_trace(mVcdFile, zext_ln1118_45_fu_418_p1, "zext_ln1118_45_fu_418_p1");
    sc_trace(mVcdFile, sub_ln1118_25_fu_803_p2, "sub_ln1118_25_fu_803_p2");
    sc_trace(mVcdFile, tmp_171_fu_809_p4, "tmp_171_fu_809_p4");
    sc_trace(mVcdFile, add_ln703_53_fu_823_p2, "add_ln703_53_fu_823_p2");
    sc_trace(mVcdFile, sext_ln703_37_fu_819_p1, "sext_ln703_37_fu_819_p1");
    sc_trace(mVcdFile, zext_ln703_18_fu_828_p1, "zext_ln703_18_fu_828_p1");
    sc_trace(mVcdFile, shl_ln1118_20_fu_838_p3, "shl_ln1118_20_fu_838_p3");
    sc_trace(mVcdFile, zext_ln1118_60_fu_846_p1, "zext_ln1118_60_fu_846_p1");
    sc_trace(mVcdFile, sub_ln1118_26_fu_850_p2, "sub_ln1118_26_fu_850_p2");
    sc_trace(mVcdFile, tmp_172_fu_856_p4, "tmp_172_fu_856_p4");
    sc_trace(mVcdFile, zext_ln1118_57_fu_768_p1, "zext_ln1118_57_fu_768_p1");
    sc_trace(mVcdFile, add_ln1118_6_fu_870_p2, "add_ln1118_6_fu_870_p2");
    sc_trace(mVcdFile, tmp_173_fu_876_p4, "tmp_173_fu_876_p4");
    sc_trace(mVcdFile, mul_ln708_6_fu_893_p0, "mul_ln708_6_fu_893_p0");
    sc_trace(mVcdFile, mul_ln708_6_fu_893_p2, "mul_ln708_6_fu_893_p2");
    sc_trace(mVcdFile, zext_ln708_7_fu_886_p1, "zext_ln708_7_fu_886_p1");
    sc_trace(mVcdFile, sext_ln1118_25_fu_866_p1, "sext_ln1118_25_fu_866_p1");
    sc_trace(mVcdFile, zext_ln1118_40_fu_317_p1, "zext_ln1118_40_fu_317_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, zext_ln1118_55_fu_921_p1, "zext_ln1118_55_fu_921_p1");
    sc_trace(mVcdFile, sext_ln1118_16_fu_924_p1, "sext_ln1118_16_fu_924_p1");
    sc_trace(mVcdFile, add_ln703_fu_927_p2, "add_ln703_fu_927_p2");
    sc_trace(mVcdFile, sext_ln703_25_fu_933_p1, "sext_ln703_25_fu_933_p1");
    sc_trace(mVcdFile, zext_ln703_15_fu_937_p1, "zext_ln703_15_fu_937_p1");
    sc_trace(mVcdFile, sext_ln1118_17_fu_946_p1, "sext_ln1118_17_fu_946_p1");
    sc_trace(mVcdFile, sext_ln1118_18_fu_949_p1, "sext_ln1118_18_fu_949_p1");
    sc_trace(mVcdFile, add_ln703_33_fu_961_p2, "add_ln703_33_fu_961_p2");
    sc_trace(mVcdFile, sext_ln703_27_fu_958_p1, "sext_ln703_27_fu_958_p1");
    sc_trace(mVcdFile, sext_ln1118_19_fu_952_p1, "sext_ln1118_19_fu_952_p1");
    sc_trace(mVcdFile, add_ln703_34_fu_971_p2, "add_ln703_34_fu_971_p2");
    sc_trace(mVcdFile, sext_ln703_28_fu_967_p1, "sext_ln703_28_fu_967_p1");
    sc_trace(mVcdFile, sext_ln703_29_fu_977_p1, "sext_ln703_29_fu_977_p1");
    sc_trace(mVcdFile, zext_ln708_fu_987_p1, "zext_ln708_fu_987_p1");
    sc_trace(mVcdFile, sext_ln703_26_fu_955_p1, "sext_ln703_26_fu_955_p1");
    sc_trace(mVcdFile, add_ln703_36_fu_990_p2, "add_ln703_36_fu_990_p2");
    sc_trace(mVcdFile, sext_ln703_30_fu_996_p1, "sext_ln703_30_fu_996_p1");
    sc_trace(mVcdFile, sext_ln1118_20_fu_1008_p1, "sext_ln1118_20_fu_1008_p1");
    sc_trace(mVcdFile, sext_ln708_fu_1005_p1, "sext_ln708_fu_1005_p1");
    sc_trace(mVcdFile, add_ln703_40_fu_1011_p2, "add_ln703_40_fu_1011_p2");
    sc_trace(mVcdFile, sext_ln703_31_fu_1017_p1, "sext_ln703_31_fu_1017_p1");
    sc_trace(mVcdFile, zext_ln703_16_fu_1021_p1, "zext_ln703_16_fu_1021_p1");
    sc_trace(mVcdFile, sext_ln703_32_fu_1030_p1, "sext_ln703_32_fu_1030_p1");
    sc_trace(mVcdFile, zext_ln703_17_fu_1036_p1, "zext_ln703_17_fu_1036_p1");
    sc_trace(mVcdFile, sext_ln703_33_fu_1033_p1, "sext_ln703_33_fu_1033_p1");
    sc_trace(mVcdFile, add_ln703_46_fu_1039_p2, "add_ln703_46_fu_1039_p2");
    sc_trace(mVcdFile, sext_ln1118_23_fu_1054_p1, "sext_ln1118_23_fu_1054_p1");
    sc_trace(mVcdFile, sext_ln1118_22_fu_1051_p1, "sext_ln1118_22_fu_1051_p1");
    sc_trace(mVcdFile, add_ln703_48_fu_1057_p2, "add_ln703_48_fu_1057_p2");
    sc_trace(mVcdFile, sext_ln703_36_fu_1063_p1, "sext_ln703_36_fu_1063_p1");
    sc_trace(mVcdFile, sext_ln708_2_fu_1075_p1, "sext_ln708_2_fu_1075_p1");
    sc_trace(mVcdFile, sext_ln1118_24_fu_1072_p1, "sext_ln1118_24_fu_1072_p1");
    sc_trace(mVcdFile, add_ln703_52_fu_1078_p2, "add_ln703_52_fu_1078_p2");
    sc_trace(mVcdFile, sext_ln703_38_fu_1084_p1, "sext_ln703_38_fu_1084_p1");
    sc_trace(mVcdFile, zext_ln708_9_fu_1093_p1, "zext_ln708_9_fu_1093_p1");
    sc_trace(mVcdFile, sext_ln703_4_fu_1099_p1, "sext_ln703_4_fu_1099_p1");
    sc_trace(mVcdFile, add_ln703_58_fu_1102_p2, "add_ln703_58_fu_1102_p2");
    sc_trace(mVcdFile, sext_ln703_39_fu_1096_p1, "sext_ln703_39_fu_1096_p1");
    sc_trace(mVcdFile, sext_ln703_5_fu_1108_p1, "sext_ln703_5_fu_1108_p1");
    sc_trace(mVcdFile, p_Val2_s_fu_940_p2, "p_Val2_s_fu_940_p2");
    sc_trace(mVcdFile, tmp_174_fu_1118_p3, "tmp_174_fu_1118_p3");
    sc_trace(mVcdFile, acc_1_V_fu_981_p2, "acc_1_V_fu_981_p2");
    sc_trace(mVcdFile, tmp_175_fu_1130_p3, "tmp_175_fu_1130_p3");
    sc_trace(mVcdFile, acc_2_V_fu_999_p2, "acc_2_V_fu_999_p2");
    sc_trace(mVcdFile, tmp_176_fu_1142_p3, "tmp_176_fu_1142_p3");
    sc_trace(mVcdFile, acc_3_V_fu_1024_p2, "acc_3_V_fu_1024_p2");
    sc_trace(mVcdFile, tmp_177_fu_1154_p3, "tmp_177_fu_1154_p3");
    sc_trace(mVcdFile, acc_4_V_fu_1045_p2, "acc_4_V_fu_1045_p2");
    sc_trace(mVcdFile, tmp_178_fu_1166_p3, "tmp_178_fu_1166_p3");
    sc_trace(mVcdFile, acc_5_V_fu_1066_p2, "acc_5_V_fu_1066_p2");
    sc_trace(mVcdFile, tmp_179_fu_1178_p3, "tmp_179_fu_1178_p3");
    sc_trace(mVcdFile, acc_6_V_fu_1087_p2, "acc_6_V_fu_1087_p2");
    sc_trace(mVcdFile, tmp_180_fu_1190_p3, "tmp_180_fu_1190_p3");
    sc_trace(mVcdFile, acc_7_V_fu_1112_p2, "acc_7_V_fu_1112_p2");
    sc_trace(mVcdFile, sext_ln728_fu_1126_p1, "sext_ln728_fu_1126_p1");
    sc_trace(mVcdFile, sext_ln728_4_fu_1138_p1, "sext_ln728_4_fu_1138_p1");
    sc_trace(mVcdFile, sext_ln728_5_fu_1150_p1, "sext_ln728_5_fu_1150_p1");
    sc_trace(mVcdFile, sext_ln728_6_fu_1162_p1, "sext_ln728_6_fu_1162_p1");
    sc_trace(mVcdFile, sext_ln728_7_fu_1174_p1, "sext_ln728_7_fu_1174_p1");
    sc_trace(mVcdFile, sext_ln728_8_fu_1186_p1, "sext_ln728_8_fu_1186_p1");
    sc_trace(mVcdFile, sext_ln728_9_fu_1198_p1, "sext_ln728_9_fu_1198_p1");
    sc_trace(mVcdFile, res_7_V_write_assign_fu_1202_p3, "res_7_V_write_assign_fu_1202_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, mul_ln1118_3_fu_386_p00, "mul_ln1118_3_fu_386_p00");
    sc_trace(mVcdFile, mul_ln1118_4_fu_470_p00, "mul_ln1118_4_fu_470_p00");
    sc_trace(mVcdFile, mul_ln1118_5_fu_486_p00, "mul_ln1118_5_fu_486_p00");
    sc_trace(mVcdFile, mul_ln708_3_fu_184_p00, "mul_ln708_3_fu_184_p00");
    sc_trace(mVcdFile, mul_ln708_6_fu_893_p00, "mul_ln708_6_fu_893_p00");
#endif

    }
}

dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::~dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        add_ln703_31_reg_1343 = add_ln703_31_fu_364_p2.read();
        add_ln703_38_reg_1368 = add_ln703_38_fu_464_p2.read();
        add_ln703_42_reg_1383 = add_ln703_42_fu_514_p2.read();
        add_ln703_44_reg_1393 = add_ln703_44_fu_619_p2.read();
        add_ln703_45_reg_1398 = add_ln703_45_fu_625_p2.read();
        add_ln703_50_reg_1413 = add_ln703_50_fu_729_p2.read();
        add_ln703_54_reg_1428 = add_ln703_54_fu_832_p2.read();
        add_ln703_56_reg_1438 = add_ln703_56_fu_909_p2.read();
        add_ln703_57_reg_1443 = add_ln703_57_fu_915_p2.read();
        lshr_ln708_8_reg_1433 = mul_ln708_6_fu_893_p2.read().range(13, 1);
        tmp_154_reg_1333 = mul_ln708_fu_260_p2.read().range(11, 1);
        tmp_155_reg_1338 = sub_ln1118_fu_301_p2.read().range(13, 1);
        tmp_156_reg_1348 = mul_ln1118_fu_370_p2.read().range(12, 1);
        tmp_157_reg_1353 = mul_ln1118_3_fu_386_p2.read().range(13, 1);
        tmp_158_reg_1358 = sub_ln1118_13_fu_402_p2.read().range(12, 1);
        tmp_160_reg_1363 = mul_ln708_2_fu_424_p2.read().range(12, 1);
        tmp_161_reg_1373 = mul_ln1118_4_fu_470_p2.read().range(13, 1);
        tmp_162_reg_1378 = mul_ln1118_5_fu_486_p2.read().range(13, 1);
        tmp_165_reg_1388 = sub_ln1118_18_fu_603_p2.read().range(14, 1);
        tmp_166_reg_1403 = sub_ln1118_19_fu_658_p2.read().range(14, 1);
        tmp_167_reg_1408 = sub_ln1118_20_fu_685_p2.read().range(12, 1);
        tmp_169_reg_1418 = sub_ln1118_22_fu_735_p2.read().range(12, 1);
        tmp_170_reg_1423 = sub_ln1118_24_fu_776_p2.read().range(14, 1);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        lshr_ln708_5_reg_1307 = p_read1.read().range(7, 1);
        lshr_ln708_6_reg_1317 = add_ln1118_5_fu_200_p2.read().range(10, 1);
        shl_ln1118_13_reg_1295 = shl_ln1118_13_fu_146_p3.read();
        tmp_159_reg_1301 = sub_ln1118_14_fu_158_p2.read().range(10, 1);
        trunc_ln1118_6_reg_1323 = mul_ln708_4_fu_216_p2.read().range(12, 1);
        trunc_ln1118_7_reg_1328 = mul_ln708_5_fu_232_p2.read().range(12, 1);
        trunc_ln1_reg_1312 = mul_ln708_3_fu_184_p2.read().range(12, 1);
        zext_ln1118_37_reg_1285 = zext_ln1118_37_fu_134_p1.read();
        zext_ln1118_42_reg_1290 = zext_ln1118_42_fu_138_p1.read();
    }
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_acc_1_V_fu_981_p2() {
    acc_1_V_fu_981_p2 = (!sext_ln703_28_fu_967_p1.read().is_01() || !sext_ln703_29_fu_977_p1.read().is_01())? sc_lv<15>(): (sc_bigint<15>(sext_ln703_28_fu_967_p1.read()) + sc_bigint<15>(sext_ln703_29_fu_977_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_acc_2_V_fu_999_p2() {
    acc_2_V_fu_999_p2 = (!add_ln703_36_fu_990_p2.read().is_01() || !sext_ln703_30_fu_996_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(add_ln703_36_fu_990_p2.read()) + sc_bigint<14>(sext_ln703_30_fu_996_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_acc_3_V_fu_1024_p2() {
    acc_3_V_fu_1024_p2 = (!sext_ln703_31_fu_1017_p1.read().is_01() || !zext_ln703_16_fu_1021_p1.read().is_01())? sc_lv<15>(): (sc_bigint<15>(sext_ln703_31_fu_1017_p1.read()) + sc_biguint<15>(zext_ln703_16_fu_1021_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_acc_4_V_fu_1045_p2() {
    acc_4_V_fu_1045_p2 = (!sext_ln703_33_fu_1033_p1.read().is_01() || !add_ln703_46_fu_1039_p2.read().is_01())? sc_lv<15>(): (sc_bigint<15>(sext_ln703_33_fu_1033_p1.read()) + sc_biguint<15>(add_ln703_46_fu_1039_p2.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_acc_5_V_fu_1066_p2() {
    acc_5_V_fu_1066_p2 = (!add_ln703_48_fu_1057_p2.read().is_01() || !sext_ln703_36_fu_1063_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(add_ln703_48_fu_1057_p2.read()) + sc_bigint<15>(sext_ln703_36_fu_1063_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_acc_6_V_fu_1087_p2() {
    acc_6_V_fu_1087_p2 = (!add_ln703_52_fu_1078_p2.read().is_01() || !sext_ln703_38_fu_1084_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(add_ln703_52_fu_1078_p2.read()) + sc_bigint<15>(sext_ln703_38_fu_1084_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_acc_7_V_fu_1112_p2() {
    acc_7_V_fu_1112_p2 = (!sext_ln703_39_fu_1096_p1.read().is_01() || !sext_ln703_5_fu_1108_p1.read().is_01())? sc_lv<16>(): (sc_bigint<16>(sext_ln703_39_fu_1096_p1.read()) + sc_bigint<16>(sext_ln703_5_fu_1108_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_add_ln1118_5_fu_200_p2() {
    add_ln1118_5_fu_200_p2 = (!zext_ln703_fu_142_p1.read().is_01() || !zext_ln1118_47_fu_154_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(zext_ln703_fu_142_p1.read()) + sc_biguint<11>(zext_ln1118_47_fu_154_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_add_ln1118_6_fu_870_p2() {
    add_ln1118_6_fu_870_p2 = (!zext_ln1118_38_fu_286_p1.read().is_01() || !zext_ln1118_57_fu_768_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(zext_ln1118_38_fu_286_p1.read()) + sc_biguint<14>(zext_ln1118_57_fu_768_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_add_ln1118_fu_345_p2() {
    add_ln1118_fu_345_p2 = (!zext_ln1118_43_fu_330_p1.read().is_01() || !zext_ln1118_44_fu_341_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(zext_ln1118_43_fu_330_p1.read()) + sc_biguint<13>(zext_ln1118_44_fu_341_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_add_ln703_31_fu_364_p2() {
    add_ln703_31_fu_364_p2 = (!zext_ln703_10_fu_361_p1.read().is_01() || !trunc_ln_fu_351_p4.read().is_01())? sc_lv<12>(): (sc_biguint<12>(zext_ln703_10_fu_361_p1.read()) + sc_biguint<12>(trunc_ln_fu_351_p4.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_add_ln703_33_fu_961_p2() {
    add_ln703_33_fu_961_p2 = (!sext_ln1118_17_fu_946_p1.read().is_01() || !sext_ln1118_18_fu_949_p1.read().is_01())? sc_lv<14>(): (sc_bigint<14>(sext_ln1118_17_fu_946_p1.read()) + sc_bigint<14>(sext_ln1118_18_fu_949_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_add_ln703_34_fu_971_p2() {
    add_ln703_34_fu_971_p2 = (!sext_ln703_27_fu_958_p1.read().is_01() || !sext_ln1118_19_fu_952_p1.read().is_01())? sc_lv<13>(): (sc_bigint<13>(sext_ln703_27_fu_958_p1.read()) + sc_bigint<13>(sext_ln1118_19_fu_952_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_add_ln703_36_fu_990_p2() {
    add_ln703_36_fu_990_p2 = (!zext_ln708_fu_987_p1.read().is_01() || !sext_ln703_26_fu_955_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(zext_ln708_fu_987_p1.read()) + sc_bigint<14>(sext_ln703_26_fu_955_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_add_ln703_37_fu_454_p2() {
    add_ln703_37_fu_454_p2 = (!zext_ln703_12_fu_450_p1.read().is_01() || !ap_const_lv12_FC0.is_01())? sc_lv<12>(): (sc_biguint<12>(zext_ln703_12_fu_450_p1.read()) + sc_bigint<12>(ap_const_lv12_FC0));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_add_ln703_38_fu_464_p2() {
    add_ln703_38_fu_464_p2 = (!zext_ln1118_48_fu_440_p1.read().is_01() || !sext_ln703_fu_460_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(zext_ln1118_48_fu_440_p1.read()) + sc_bigint<13>(sext_ln703_fu_460_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_add_ln703_40_fu_1011_p2() {
    add_ln703_40_fu_1011_p2 = (!sext_ln1118_20_fu_1008_p1.read().is_01() || !sext_ln708_fu_1005_p1.read().is_01())? sc_lv<14>(): (sc_bigint<14>(sext_ln1118_20_fu_1008_p1.read()) + sc_bigint<14>(sext_ln708_fu_1005_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_add_ln703_41_fu_505_p2() {
    add_ln703_41_fu_505_p2 = (!trunc_ln1_reg_1312.read().is_01() || !ap_const_lv12_180.is_01())? sc_lv<12>(): (sc_biguint<12>(trunc_ln1_reg_1312.read()) + sc_biguint<12>(ap_const_lv12_180));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_add_ln703_42_fu_514_p2() {
    add_ln703_42_fu_514_p2 = (!zext_ln703_13_fu_502_p1.read().is_01() || !zext_ln703_14_fu_510_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(zext_ln703_13_fu_502_p1.read()) + sc_biguint<13>(zext_ln703_14_fu_510_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_add_ln703_44_fu_619_p2() {
    add_ln703_44_fu_619_p2 = (!sext_ln708_1_fu_578_p1.read().is_01() || !sext_ln1118_21_fu_548_p1.read().is_01())? sc_lv<13>(): (sc_bigint<13>(sext_ln708_1_fu_578_p1.read()) + sc_bigint<13>(sext_ln1118_21_fu_548_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_add_ln703_45_fu_625_p2() {
    add_ln703_45_fu_625_p2 = (!trunc_ln1118_6_reg_1323.read().is_01() || !ap_const_lv12_1C0.is_01())? sc_lv<12>(): (sc_biguint<12>(trunc_ln1118_6_reg_1323.read()) + sc_biguint<12>(ap_const_lv12_1C0));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_add_ln703_46_fu_1039_p2() {
    add_ln703_46_fu_1039_p2 = (!sext_ln703_32_fu_1030_p1.read().is_01() || !zext_ln703_17_fu_1036_p1.read().is_01())? sc_lv<15>(): (sc_bigint<15>(sext_ln703_32_fu_1030_p1.read()) + sc_biguint<15>(zext_ln703_17_fu_1036_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_add_ln703_48_fu_1057_p2() {
    add_ln703_48_fu_1057_p2 = (!sext_ln1118_23_fu_1054_p1.read().is_01() || !sext_ln1118_22_fu_1051_p1.read().is_01())? sc_lv<15>(): (sc_bigint<15>(sext_ln1118_23_fu_1054_p1.read()) + sc_bigint<15>(sext_ln1118_22_fu_1051_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_add_ln703_49_fu_720_p2() {
    add_ln703_49_fu_720_p2 = (!lshr_ln708_6_reg_1317.read().is_01() || !ap_const_lv10_2C0.is_01())? sc_lv<10>(): (sc_biguint<10>(lshr_ln708_6_reg_1317.read()) + sc_bigint<10>(ap_const_lv10_2C0));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_add_ln703_50_fu_729_p2() {
    add_ln703_50_fu_729_p2 = (!sext_ln703_34_fu_716_p1.read().is_01() || !sext_ln703_35_fu_725_p1.read().is_01())? sc_lv<13>(): (sc_bigint<13>(sext_ln703_34_fu_716_p1.read()) + sc_bigint<13>(sext_ln703_35_fu_725_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_add_ln703_52_fu_1078_p2() {
    add_ln703_52_fu_1078_p2 = (!sext_ln708_2_fu_1075_p1.read().is_01() || !sext_ln1118_24_fu_1072_p1.read().is_01())? sc_lv<15>(): (sc_bigint<15>(sext_ln708_2_fu_1075_p1.read()) + sc_bigint<15>(sext_ln1118_24_fu_1072_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_add_ln703_53_fu_823_p2() {
    add_ln703_53_fu_823_p2 = (!trunc_ln1118_7_reg_1328.read().is_01() || !ap_const_lv12_E0.is_01())? sc_lv<12>(): (sc_biguint<12>(trunc_ln1118_7_reg_1328.read()) + sc_biguint<12>(ap_const_lv12_E0));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_add_ln703_54_fu_832_p2() {
    add_ln703_54_fu_832_p2 = (!sext_ln703_37_fu_819_p1.read().is_01() || !zext_ln703_18_fu_828_p1.read().is_01())? sc_lv<14>(): (sc_bigint<14>(sext_ln703_37_fu_819_p1.read()) + sc_biguint<14>(zext_ln703_18_fu_828_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_add_ln703_56_fu_909_p2() {
    add_ln703_56_fu_909_p2 = (!zext_ln708_7_fu_886_p1.read().is_01() || !sext_ln1118_25_fu_866_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(zext_ln708_7_fu_886_p1.read()) + sc_bigint<15>(sext_ln1118_25_fu_866_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_add_ln703_57_fu_915_p2() {
    add_ln703_57_fu_915_p2 = (!zext_ln1118_40_fu_317_p1.read().is_01() || !ap_const_lv9_140.is_01())? sc_lv<9>(): (sc_biguint<9>(zext_ln1118_40_fu_317_p1.read()) + sc_bigint<9>(ap_const_lv9_140));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_add_ln703_58_fu_1102_p2() {
    add_ln703_58_fu_1102_p2 = (!zext_ln708_9_fu_1093_p1.read().is_01() || !sext_ln703_4_fu_1099_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(zext_ln708_9_fu_1093_p1.read()) + sc_bigint<14>(sext_ln703_4_fu_1099_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_add_ln703_fu_927_p2() {
    add_ln703_fu_927_p2 = (!zext_ln1118_55_fu_921_p1.read().is_01() || !sext_ln1118_16_fu_924_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(zext_ln1118_55_fu_921_p1.read()) + sc_bigint<14>(sext_ln1118_16_fu_924_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_ap_return_0() {
    ap_return_0 = sext_ln728_fu_1126_p1.read();
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_ap_return_1() {
    ap_return_1 = sext_ln728_4_fu_1138_p1.read();
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_ap_return_2() {
    ap_return_2 = sext_ln728_5_fu_1150_p1.read();
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_ap_return_3() {
    ap_return_3 = sext_ln728_6_fu_1162_p1.read();
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_ap_return_4() {
    ap_return_4 = sext_ln728_7_fu_1174_p1.read();
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_ap_return_5() {
    ap_return_5 = sext_ln728_8_fu_1186_p1.read();
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_ap_return_6() {
    ap_return_6 = sext_ln728_9_fu_1198_p1.read();
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_ap_return_7() {
    ap_return_7 = res_7_V_write_assign_fu_1202_p3.read();
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_3_fu_386_p0() {
    mul_ln1118_3_fu_386_p0 =  (sc_lv<8>) (mul_ln1118_3_fu_386_p00.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_3_fu_386_p00() {
    mul_ln1118_3_fu_386_p00 = esl_zext<14,8>(p_read1.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_3_fu_386_p2() {
    mul_ln1118_3_fu_386_p2 = (!mul_ln1118_3_fu_386_p0.read().is_01() || !ap_const_lv14_3FE5.is_01())? sc_lv<14>(): sc_biguint<8>(mul_ln1118_3_fu_386_p0.read()) * sc_bigint<14>(ap_const_lv14_3FE5);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_4_fu_470_p0() {
    mul_ln1118_4_fu_470_p0 =  (sc_lv<8>) (mul_ln1118_4_fu_470_p00.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_4_fu_470_p00() {
    mul_ln1118_4_fu_470_p00 = esl_zext<14,8>(p_read.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_4_fu_470_p2() {
    mul_ln1118_4_fu_470_p2 = (!mul_ln1118_4_fu_470_p0.read().is_01() || !ap_const_lv14_3FEA.is_01())? sc_lv<14>(): sc_biguint<8>(mul_ln1118_4_fu_470_p0.read()) * sc_bigint<14>(ap_const_lv14_3FEA);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_5_fu_486_p0() {
    mul_ln1118_5_fu_486_p0 =  (sc_lv<8>) (mul_ln1118_5_fu_486_p00.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_5_fu_486_p00() {
    mul_ln1118_5_fu_486_p00 = esl_zext<14,8>(p_read2.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_5_fu_486_p2() {
    mul_ln1118_5_fu_486_p2 = (!mul_ln1118_5_fu_486_p0.read().is_01() || !ap_const_lv14_3FE5.is_01())? sc_lv<14>(): sc_biguint<8>(mul_ln1118_5_fu_486_p0.read()) * sc_bigint<14>(ap_const_lv14_3FE5);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_fu_370_p0() {
    mul_ln1118_fu_370_p0 =  (sc_lv<8>) (zext_ln1118_fu_248_p1.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_fu_370_p2() {
    mul_ln1118_fu_370_p2 = (!mul_ln1118_fu_370_p0.read().is_01() || !ap_const_lv13_1FF5.is_01())? sc_lv<13>(): sc_biguint<8>(mul_ln1118_fu_370_p0.read()) * sc_bigint<13>(ap_const_lv13_1FF5);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_mul_ln708_2_fu_424_p0() {
    mul_ln708_2_fu_424_p0 =  (sc_lv<8>) (zext_ln1118_fu_248_p1.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_mul_ln708_2_fu_424_p2() {
    mul_ln708_2_fu_424_p2 = (!mul_ln708_2_fu_424_p0.read().is_01() || !ap_const_lv13_1A.is_01())? sc_lv<13>(): sc_biguint<8>(mul_ln708_2_fu_424_p0.read()) * sc_biguint<13>(ap_const_lv13_1A);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_mul_ln708_3_fu_184_p0() {
    mul_ln708_3_fu_184_p0 =  (sc_lv<8>) (mul_ln708_3_fu_184_p00.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_mul_ln708_3_fu_184_p00() {
    mul_ln708_3_fu_184_p00 = esl_zext<13,8>(p_read1.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_mul_ln708_3_fu_184_p2() {
    mul_ln708_3_fu_184_p2 = (!mul_ln708_3_fu_184_p0.read().is_01() || !ap_const_lv13_1D.is_01())? sc_lv<13>(): sc_biguint<8>(mul_ln708_3_fu_184_p0.read()) * sc_biguint<13>(ap_const_lv13_1D);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_mul_ln708_4_fu_216_p0() {
    mul_ln708_4_fu_216_p0 =  (sc_lv<8>) (zext_ln1118_42_fu_138_p1.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_mul_ln708_4_fu_216_p2() {
    mul_ln708_4_fu_216_p2 = (!mul_ln708_4_fu_216_p0.read().is_01() || !ap_const_lv13_17.is_01())? sc_lv<13>(): sc_biguint<8>(mul_ln708_4_fu_216_p0.read()) * sc_biguint<13>(ap_const_lv13_17);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_mul_ln708_5_fu_232_p0() {
    mul_ln708_5_fu_232_p0 =  (sc_lv<8>) (zext_ln1118_42_fu_138_p1.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_mul_ln708_5_fu_232_p2() {
    mul_ln708_5_fu_232_p2 = (!mul_ln708_5_fu_232_p0.read().is_01() || !ap_const_lv13_16.is_01())? sc_lv<13>(): sc_biguint<8>(mul_ln708_5_fu_232_p0.read()) * sc_biguint<13>(ap_const_lv13_16);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_mul_ln708_6_fu_893_p0() {
    mul_ln708_6_fu_893_p0 =  (sc_lv<8>) (mul_ln708_6_fu_893_p00.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_mul_ln708_6_fu_893_p00() {
    mul_ln708_6_fu_893_p00 = esl_zext<14,8>(p_read3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_mul_ln708_6_fu_893_p2() {
    mul_ln708_6_fu_893_p2 = (!mul_ln708_6_fu_893_p0.read().is_01() || !ap_const_lv14_26.is_01())? sc_lv<14>(): sc_biguint<8>(mul_ln708_6_fu_893_p0.read()) * sc_biguint<14>(ap_const_lv14_26);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_mul_ln708_fu_260_p0() {
    mul_ln708_fu_260_p0 =  (sc_lv<8>) (zext_ln1118_34_fu_252_p1.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_mul_ln708_fu_260_p2() {
    mul_ln708_fu_260_p2 = (!mul_ln708_fu_260_p0.read().is_01() || !ap_const_lv12_D.is_01())? sc_lv<12>(): sc_biguint<8>(mul_ln708_fu_260_p0.read()) * sc_biguint<12>(ap_const_lv12_D);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_p_Val2_s_fu_940_p2() {
    p_Val2_s_fu_940_p2 = (!sext_ln703_25_fu_933_p1.read().is_01() || !zext_ln703_15_fu_937_p1.read().is_01())? sc_lv<15>(): (sc_bigint<15>(sext_ln703_25_fu_933_p1.read()) + sc_biguint<15>(zext_ln703_15_fu_937_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_res_7_V_write_assign_fu_1202_p3() {
    res_7_V_write_assign_fu_1202_p3 = esl_concat<16,1>(acc_7_V_fu_1112_p2.read(), ap_const_lv1_0);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln1118_16_fu_924_p1() {
    sext_ln1118_16_fu_924_p1 = esl_sext<14,13>(tmp_155_reg_1338.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln1118_17_fu_946_p1() {
    sext_ln1118_17_fu_946_p1 = esl_sext<14,12>(tmp_156_reg_1348.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln1118_18_fu_949_p1() {
    sext_ln1118_18_fu_949_p1 = esl_sext<14,13>(tmp_157_reg_1353.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln1118_19_fu_952_p1() {
    sext_ln1118_19_fu_952_p1 = esl_sext<13,12>(tmp_158_reg_1358.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln1118_1_fu_757_p1() {
    sext_ln1118_1_fu_757_p1 = esl_sext<15,14>(sub_ln1118_23_fu_751_p2.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln1118_20_fu_1008_p1() {
    sext_ln1118_20_fu_1008_p1 = esl_sext<14,13>(tmp_162_reg_1378.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln1118_21_fu_548_p1() {
    sext_ln1118_21_fu_548_p1 = esl_sext<13,11>(tmp_163_fu_538_p4.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln1118_22_fu_1051_p1() {
    sext_ln1118_22_fu_1051_p1 = esl_sext<15,14>(tmp_166_reg_1403.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln1118_23_fu_1054_p1() {
    sext_ln1118_23_fu_1054_p1 = esl_sext<15,12>(tmp_167_reg_1408.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln1118_24_fu_1072_p1() {
    sext_ln1118_24_fu_1072_p1 = esl_sext<15,12>(tmp_169_reg_1418.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln1118_25_fu_866_p1() {
    sext_ln1118_25_fu_866_p1 = esl_sext<15,9>(tmp_172_fu_856_p4.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln1118_fu_599_p1() {
    sext_ln1118_fu_599_p1 = esl_sext<15,14>(sub_ln1118_17_fu_593_p2.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln703_25_fu_933_p1() {
    sext_ln703_25_fu_933_p1 = esl_sext<15,14>(add_ln703_fu_927_p2.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln703_26_fu_955_p1() {
    sext_ln703_26_fu_955_p1 = esl_sext<14,10>(tmp_159_reg_1301.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln703_27_fu_958_p1() {
    sext_ln703_27_fu_958_p1 = esl_sext<13,10>(tmp_159_reg_1301.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln703_28_fu_967_p1() {
    sext_ln703_28_fu_967_p1 = esl_sext<15,14>(add_ln703_33_fu_961_p2.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln703_29_fu_977_p1() {
    sext_ln703_29_fu_977_p1 = esl_sext<15,13>(add_ln703_34_fu_971_p2.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln703_30_fu_996_p1() {
    sext_ln703_30_fu_996_p1 = esl_sext<14,13>(add_ln703_38_reg_1368.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln703_31_fu_1017_p1() {
    sext_ln703_31_fu_1017_p1 = esl_sext<15,14>(add_ln703_40_fu_1011_p2.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln703_32_fu_1030_p1() {
    sext_ln703_32_fu_1030_p1 = esl_sext<15,14>(tmp_165_reg_1388.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln703_33_fu_1033_p1() {
    sext_ln703_33_fu_1033_p1 = esl_sext<15,13>(add_ln703_44_reg_1393.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln703_34_fu_716_p1() {
    sext_ln703_34_fu_716_p1 = esl_sext<13,12>(tmp_168_fu_706_p4.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln703_35_fu_725_p1() {
    sext_ln703_35_fu_725_p1 = esl_sext<13,10>(add_ln703_49_fu_720_p2.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln703_36_fu_1063_p1() {
    sext_ln703_36_fu_1063_p1 = esl_sext<15,13>(add_ln703_50_reg_1413.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln703_37_fu_819_p1() {
    sext_ln703_37_fu_819_p1 = esl_sext<14,12>(tmp_171_fu_809_p4.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln703_38_fu_1084_p1() {
    sext_ln703_38_fu_1084_p1 = esl_sext<15,14>(add_ln703_54_reg_1428.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln703_39_fu_1096_p1() {
    sext_ln703_39_fu_1096_p1 = esl_sext<16,15>(add_ln703_56_reg_1438.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln703_4_fu_1099_p1() {
    sext_ln703_4_fu_1099_p1 = esl_sext<14,9>(add_ln703_57_reg_1443.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln703_5_fu_1108_p1() {
    sext_ln703_5_fu_1108_p1 = esl_sext<16,14>(add_ln703_58_fu_1102_p2.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln703_fu_460_p1() {
    sext_ln703_fu_460_p1 = esl_sext<13,12>(add_ln703_37_fu_454_p2.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln708_1_fu_578_p1() {
    sext_ln708_1_fu_578_p1 = esl_sext<13,12>(tmp_164_fu_568_p4.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln708_2_fu_1075_p1() {
    sext_ln708_2_fu_1075_p1 = esl_sext<15,14>(tmp_170_reg_1423.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln708_fu_1005_p1() {
    sext_ln708_fu_1005_p1 = esl_sext<14,13>(tmp_161_reg_1373.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln728_4_fu_1138_p1() {
    sext_ln728_4_fu_1138_p1 = esl_sext<17,16>(tmp_175_fu_1130_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln728_5_fu_1150_p1() {
    sext_ln728_5_fu_1150_p1 = esl_sext<17,15>(tmp_176_fu_1142_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln728_6_fu_1162_p1() {
    sext_ln728_6_fu_1162_p1 = esl_sext<17,16>(tmp_177_fu_1154_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln728_7_fu_1174_p1() {
    sext_ln728_7_fu_1174_p1 = esl_sext<17,16>(tmp_178_fu_1166_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln728_8_fu_1186_p1() {
    sext_ln728_8_fu_1186_p1 = esl_sext<17,16>(tmp_179_fu_1178_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln728_9_fu_1198_p1() {
    sext_ln728_9_fu_1198_p1 = esl_sext<17,16>(tmp_180_fu_1190_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sext_ln728_fu_1126_p1() {
    sext_ln728_fu_1126_p1 = esl_sext<17,16>(tmp_174_fu_1118_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_shl_ln1118_11_fu_323_p3() {
    shl_ln1118_11_fu_323_p3 = esl_concat<8,4>(p_read2.read(), ap_const_lv4_0);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_shl_ln1118_12_fu_334_p3() {
    shl_ln1118_12_fu_334_p3 = esl_concat<8,2>(p_read2.read(), ap_const_lv2_0);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_shl_ln1118_13_fu_146_p3() {
    shl_ln1118_13_fu_146_p3 = esl_concat<8,2>(p_read3.read(), ap_const_lv2_0);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_shl_ln1118_14_fu_582_p3() {
    shl_ln1118_14_fu_582_p3 = esl_concat<8,5>(p_read3.read(), ap_const_lv5_0);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_shl_ln1118_15_fu_630_p3() {
    shl_ln1118_15_fu_630_p3 = esl_concat<8,6>(p_read.read(), ap_const_lv6_0);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_shl_ln1118_16_fu_642_p3() {
    shl_ln1118_16_fu_642_p3 = esl_concat<8,4>(p_read.read(), ap_const_lv4_0);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_shl_ln1118_17_fu_674_p3() {
    shl_ln1118_17_fu_674_p3 = esl_concat<8,2>(p_read1.read(), ap_const_lv2_0);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_shl_ln1118_18_fu_761_p3() {
    shl_ln1118_18_fu_761_p3 = esl_concat<8,1>(p_read1.read(), ap_const_lv1_0);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_shl_ln1118_19_fu_792_p3() {
    shl_ln1118_19_fu_792_p3 = esl_concat<8,4>(p_read3.read(), ap_const_lv4_0);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_shl_ln1118_20_fu_838_p3() {
    shl_ln1118_20_fu_838_p3 = esl_concat<8,1>(p_read.read(), ap_const_lv1_0);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_shl_ln1118_s_fu_290_p3() {
    shl_ln1118_s_fu_290_p3 = esl_concat<8,3>(p_read1.read(), ap_const_lv3_0);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_shl_ln3_fu_443_p3() {
    shl_ln3_fu_443_p3 = esl_concat<8,3>(p_read2.read(), ap_const_lv3_0);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_shl_ln_fu_279_p3() {
    shl_ln_fu_279_p3 = esl_concat<8,5>(p_read1.read(), ap_const_lv5_0);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_13_fu_402_p2() {
    sub_ln1118_13_fu_402_p2 = (!zext_ln1118_44_fu_341_p1.read().is_01() || !zext_ln1118_43_fu_330_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(zext_ln1118_44_fu_341_p1.read()) - sc_biguint<13>(zext_ln1118_43_fu_330_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_14_fu_158_p2() {
    sub_ln1118_14_fu_158_p2 = (!ap_const_lv11_0.is_01() || !zext_ln1118_47_fu_154_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_0) - sc_biguint<11>(zext_ln1118_47_fu_154_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_15_fu_532_p2() {
    sub_ln1118_15_fu_532_p2 = (!zext_ln1118_34_fu_252_p1.read().is_01() || !zext_ln1118_49_fu_528_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(zext_ln1118_34_fu_252_p1.read()) - sc_biguint<12>(zext_ln1118_49_fu_528_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_16_fu_563_p2() {
    sub_ln1118_16_fu_563_p2 = (!zext_ln1118_37_reg_1285.read().is_01() || !zext_ln1118_50_fu_559_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(zext_ln1118_37_reg_1285.read()) - sc_biguint<13>(zext_ln1118_50_fu_559_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_17_fu_593_p2() {
    sub_ln1118_17_fu_593_p2 = (!ap_const_lv14_0.is_01() || !zext_ln1118_51_fu_589_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(ap_const_lv14_0) - sc_biguint<14>(zext_ln1118_51_fu_589_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_18_fu_603_p2() {
    sub_ln1118_18_fu_603_p2 = (!sext_ln1118_fu_599_p1.read().is_01() || !zext_ln1118_46_fu_421_p1.read().is_01())? sc_lv<15>(): (sc_bigint<15>(sext_ln1118_fu_599_p1.read()) - sc_biguint<15>(zext_ln1118_46_fu_421_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_19_fu_658_p2() {
    sub_ln1118_19_fu_658_p2 = (!zext_ln1118_52_fu_638_p1.read().is_01() || !zext_ln1118_54_fu_654_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(zext_ln1118_52_fu_638_p1.read()) - sc_biguint<15>(zext_ln1118_54_fu_654_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_20_fu_685_p2() {
    sub_ln1118_20_fu_685_p2 = (!zext_ln1118_50_fu_559_p1.read().is_01() || !zext_ln1118_56_fu_681_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(zext_ln1118_50_fu_559_p1.read()) - sc_biguint<13>(zext_ln1118_56_fu_681_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_21_fu_701_p2() {
    sub_ln1118_21_fu_701_p2 = (!zext_ln1118_43_fu_330_p1.read().is_01() || !zext_ln1118_42_reg_1290.read().is_01())? sc_lv<13>(): (sc_biguint<13>(zext_ln1118_43_fu_330_p1.read()) - sc_biguint<13>(zext_ln1118_42_reg_1290.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_22_fu_735_p2() {
    sub_ln1118_22_fu_735_p2 = (!ap_const_lv13_0.is_01() || !zext_ln1118_53_fu_650_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_0) - sc_biguint<13>(zext_ln1118_53_fu_650_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_23_fu_751_p2() {
    sub_ln1118_23_fu_751_p2 = (!ap_const_lv14_0.is_01() || !zext_ln1118_38_fu_286_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(ap_const_lv14_0) - sc_biguint<14>(zext_ln1118_38_fu_286_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_24_fu_776_p2() {
    sub_ln1118_24_fu_776_p2 = (!sext_ln1118_1_fu_757_p1.read().is_01() || !zext_ln1118_58_fu_772_p1.read().is_01())? sc_lv<15>(): (sc_bigint<15>(sext_ln1118_1_fu_757_p1.read()) - sc_biguint<15>(zext_ln1118_58_fu_772_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_25_fu_803_p2() {
    sub_ln1118_25_fu_803_p2 = (!zext_ln1118_59_fu_799_p1.read().is_01() || !zext_ln1118_45_fu_418_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(zext_ln1118_59_fu_799_p1.read()) - sc_biguint<13>(zext_ln1118_45_fu_418_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_26_fu_850_p2() {
    sub_ln1118_26_fu_850_p2 = (!ap_const_lv10_0.is_01() || !zext_ln1118_60_fu_846_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_0) - sc_biguint<10>(zext_ln1118_60_fu_846_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_fu_301_p2() {
    sub_ln1118_fu_301_p2 = (!zext_ln1118_39_fu_297_p1.read().is_01() || !zext_ln1118_38_fu_286_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(zext_ln1118_39_fu_297_p1.read()) - sc_biguint<14>(zext_ln1118_38_fu_286_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_tmp_163_fu_538_p4() {
    tmp_163_fu_538_p4 = sub_ln1118_15_fu_532_p2.read().range(11, 1);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_tmp_164_fu_568_p4() {
    tmp_164_fu_568_p4 = sub_ln1118_16_fu_563_p2.read().range(12, 1);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_tmp_168_fu_706_p4() {
    tmp_168_fu_706_p4 = sub_ln1118_21_fu_701_p2.read().range(12, 1);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_tmp_171_fu_809_p4() {
    tmp_171_fu_809_p4 = sub_ln1118_25_fu_803_p2.read().range(12, 1);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_tmp_172_fu_856_p4() {
    tmp_172_fu_856_p4 = sub_ln1118_26_fu_850_p2.read().range(9, 1);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_tmp_173_fu_876_p4() {
    tmp_173_fu_876_p4 = add_ln1118_6_fu_870_p2.read().range(13, 1);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_tmp_174_fu_1118_p3() {
    tmp_174_fu_1118_p3 = esl_concat<15,1>(p_Val2_s_fu_940_p2.read(), ap_const_lv1_0);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_tmp_175_fu_1130_p3() {
    tmp_175_fu_1130_p3 = esl_concat<15,1>(acc_1_V_fu_981_p2.read(), ap_const_lv1_0);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_tmp_176_fu_1142_p3() {
    tmp_176_fu_1142_p3 = esl_concat<14,1>(acc_2_V_fu_999_p2.read(), ap_const_lv1_0);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_tmp_177_fu_1154_p3() {
    tmp_177_fu_1154_p3 = esl_concat<15,1>(acc_3_V_fu_1024_p2.read(), ap_const_lv1_0);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_tmp_178_fu_1166_p3() {
    tmp_178_fu_1166_p3 = esl_concat<15,1>(acc_4_V_fu_1045_p2.read(), ap_const_lv1_0);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_tmp_179_fu_1178_p3() {
    tmp_179_fu_1178_p3 = esl_concat<15,1>(acc_5_V_fu_1066_p2.read(), ap_const_lv1_0);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_tmp_180_fu_1190_p3() {
    tmp_180_fu_1190_p3 = esl_concat<15,1>(acc_6_V_fu_1087_p2.read(), ap_const_lv1_0);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_tmp_4_fu_552_p3() {
    tmp_4_fu_552_p3 = esl_concat<8,4>(p_read1.read(), ap_const_lv4_0);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_tmp_fu_520_p3() {
    tmp_fu_520_p3 = esl_concat<8,3>(p_read.read(), ap_const_lv3_0);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_trunc_ln_fu_351_p4() {
    trunc_ln_fu_351_p4 = add_ln1118_fu_345_p2.read().range(12, 1);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_34_fu_252_p1() {
    zext_ln1118_34_fu_252_p1 = esl_zext<12,8>(p_read.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_37_fu_134_p1() {
    zext_ln1118_37_fu_134_p1 = esl_zext<13,8>(p_read1.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_38_fu_286_p1() {
    zext_ln1118_38_fu_286_p1 = esl_zext<14,13>(shl_ln_fu_279_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_39_fu_297_p1() {
    zext_ln1118_39_fu_297_p1 = esl_zext<14,11>(shl_ln1118_s_fu_290_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_40_fu_317_p1() {
    zext_ln1118_40_fu_317_p1 = esl_zext<9,8>(p_read2.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_42_fu_138_p1() {
    zext_ln1118_42_fu_138_p1 = esl_zext<13,8>(p_read2.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_43_fu_330_p1() {
    zext_ln1118_43_fu_330_p1 = esl_zext<13,12>(shl_ln1118_11_fu_323_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_44_fu_341_p1() {
    zext_ln1118_44_fu_341_p1 = esl_zext<13,10>(shl_ln1118_12_fu_334_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_45_fu_418_p1() {
    zext_ln1118_45_fu_418_p1 = esl_zext<13,10>(shl_ln1118_13_reg_1295.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_46_fu_421_p1() {
    zext_ln1118_46_fu_421_p1 = esl_zext<15,10>(shl_ln1118_13_reg_1295.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_47_fu_154_p1() {
    zext_ln1118_47_fu_154_p1 = esl_zext<11,10>(shl_ln1118_13_fu_146_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_48_fu_440_p1() {
    zext_ln1118_48_fu_440_p1 = esl_zext<13,7>(lshr_ln708_5_reg_1307.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_49_fu_528_p1() {
    zext_ln1118_49_fu_528_p1 = esl_zext<12,11>(tmp_fu_520_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_50_fu_559_p1() {
    zext_ln1118_50_fu_559_p1 = esl_zext<13,12>(tmp_4_fu_552_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_51_fu_589_p1() {
    zext_ln1118_51_fu_589_p1 = esl_zext<14,13>(shl_ln1118_14_fu_582_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_52_fu_638_p1() {
    zext_ln1118_52_fu_638_p1 = esl_zext<15,14>(shl_ln1118_15_fu_630_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_53_fu_650_p1() {
    zext_ln1118_53_fu_650_p1 = esl_zext<13,12>(shl_ln1118_16_fu_642_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_54_fu_654_p1() {
    zext_ln1118_54_fu_654_p1 = esl_zext<15,12>(shl_ln1118_16_fu_642_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_55_fu_921_p1() {
    zext_ln1118_55_fu_921_p1 = esl_zext<14,11>(tmp_154_reg_1333.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_56_fu_681_p1() {
    zext_ln1118_56_fu_681_p1 = esl_zext<13,10>(shl_ln1118_17_fu_674_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_57_fu_768_p1() {
    zext_ln1118_57_fu_768_p1 = esl_zext<14,9>(shl_ln1118_18_fu_761_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_58_fu_772_p1() {
    zext_ln1118_58_fu_772_p1 = esl_zext<15,9>(shl_ln1118_18_fu_761_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_59_fu_799_p1() {
    zext_ln1118_59_fu_799_p1 = esl_zext<13,12>(shl_ln1118_19_fu_792_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_60_fu_846_p1() {
    zext_ln1118_60_fu_846_p1 = esl_zext<10,9>(shl_ln1118_20_fu_838_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_fu_248_p1() {
    zext_ln1118_fu_248_p1 = esl_zext<13,8>(p_read.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln703_10_fu_361_p1() {
    zext_ln703_10_fu_361_p1 = esl_zext<12,8>(p_read3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln703_12_fu_450_p1() {
    zext_ln703_12_fu_450_p1 = esl_zext<12,11>(shl_ln3_fu_443_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln703_13_fu_502_p1() {
    zext_ln703_13_fu_502_p1 = esl_zext<13,10>(lshr_ln708_6_reg_1317.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln703_14_fu_510_p1() {
    zext_ln703_14_fu_510_p1 = esl_zext<13,12>(add_ln703_41_fu_505_p2.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln703_15_fu_937_p1() {
    zext_ln703_15_fu_937_p1 = esl_zext<15,12>(add_ln703_31_reg_1343.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln703_16_fu_1021_p1() {
    zext_ln703_16_fu_1021_p1 = esl_zext<15,13>(add_ln703_42_reg_1383.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln703_17_fu_1036_p1() {
    zext_ln703_17_fu_1036_p1 = esl_zext<15,12>(add_ln703_45_reg_1398.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln703_18_fu_828_p1() {
    zext_ln703_18_fu_828_p1 = esl_zext<14,12>(add_ln703_53_fu_823_p2.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln703_fu_142_p1() {
    zext_ln703_fu_142_p1 = esl_zext<11,8>(p_read3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln708_7_fu_886_p1() {
    zext_ln708_7_fu_886_p1 = esl_zext<15,13>(tmp_173_fu_876_p4.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln708_9_fu_1093_p1() {
    zext_ln708_9_fu_1093_p1 = esl_zext<14,13>(lshr_ln708_8_reg_1433.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_zext_ln708_fu_987_p1() {
    zext_ln708_fu_987_p1 = esl_zext<14,12>(tmp_160_reg_1363.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

