// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config5_0_0_0_0_0 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] p_read;
input  [7:0] p_read1;
input  [7:0] p_read2;
input  [7:0] p_read3;
input  [7:0] p_read4;
input  [7:0] p_read5;
input  [7:0] p_read6;
input  [7:0] p_read7;
output  [16:0] ap_return_0;
output  [16:0] ap_return_1;
output  [16:0] ap_return_2;
output  [16:0] ap_return_3;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[16:0] ap_return_0;
reg[16:0] ap_return_1;
reg[16:0] ap_return_2;
reg[16:0] ap_return_3;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln46_fu_483_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_11001;
wire   [1:0] w5_V_address0;
reg    w5_V_ce0;
wire   [59:0] w5_V_q0;
reg   [0:0] do_init_reg_177;
reg   [1:0] w_index9_reg_193;
reg   [7:0] p_read10_rewind_reg_208;
reg   [7:0] p_read111_rewind_reg_222;
reg   [7:0] p_read212_rewind_reg_236;
reg   [7:0] p_read313_rewind_reg_250;
reg   [7:0] p_read414_rewind_reg_264;
reg   [7:0] p_read515_rewind_reg_278;
reg   [7:0] p_read616_rewind_reg_292;
reg   [7:0] p_read717_rewind_reg_306;
reg   [7:0] p_read10_phi_reg_320;
reg   [7:0] p_read111_phi_reg_332;
reg   [7:0] p_read212_phi_reg_344;
reg   [7:0] p_read313_phi_reg_356;
reg   [7:0] p_read414_phi_reg_368;
reg   [7:0] p_read515_phi_reg_380;
reg   [7:0] p_read616_phi_reg_392;
reg   [7:0] p_read717_phi_reg_404;
reg   [15:0] p_Val2_8_reg_416;
reg   [15:0] p_Val2_16_reg_430;
reg   [15:0] p_Val2_24_reg_444;
reg   [15:0] p_Val2_32_reg_458;
reg   [0:0] ap_phi_mux_do_init_phi_fu_181_p6;
wire   [1:0] w_index_fu_477_p2;
reg   [1:0] w_index_reg_1104;
reg   [0:0] icmp_ln46_reg_1109;
reg   [0:0] icmp_ln46_reg_1109_pp0_iter1_reg;
reg   [0:0] icmp_ln46_reg_1109_pp0_iter2_reg;
wire   [7:0] phi_ln_fu_493_p10;
reg   [7:0] phi_ln_reg_1113;
wire   [7:0] trunc_ln59_fu_515_p1;
reg   [7:0] trunc_ln59_reg_1118;
wire   [7:0] phi_ln59_1_fu_527_p10;
reg   [7:0] phi_ln59_1_reg_1123;
reg   [7:0] tmp_3_reg_1128;
wire   [7:0] phi_ln59_2_fu_559_p10;
reg   [7:0] phi_ln59_2_reg_1133;
reg   [7:0] tmp_4_reg_1138;
wire   [7:0] phi_ln59_3_fu_591_p10;
reg   [7:0] phi_ln59_3_reg_1143;
reg   [7:0] tmp_5_reg_1148;
wire   [7:0] phi_ln59_4_fu_623_p10;
reg   [7:0] phi_ln59_4_reg_1153;
reg   [7:0] tmp_6_reg_1158;
wire   [7:0] phi_ln59_5_fu_655_p10;
reg   [7:0] phi_ln59_5_reg_1163;
reg   [7:0] tmp_7_reg_1168;
wire   [7:0] phi_ln59_6_fu_687_p10;
reg   [7:0] phi_ln59_6_reg_1173;
reg   [7:0] tmp_8_reg_1178;
wire   [7:0] phi_ln59_7_fu_719_p10;
reg   [7:0] phi_ln59_7_reg_1183;
reg   [3:0] tmp_s_reg_1188;
reg   [14:0] trunc_ln_reg_1193;
reg   [14:0] trunc_ln708_s_reg_1198;
reg   [14:0] trunc_ln708_2_reg_1203;
reg   [14:0] trunc_ln708_3_reg_1208;
reg   [14:0] trunc_ln708_4_reg_1213;
reg   [14:0] trunc_ln708_5_reg_1218;
reg   [14:0] trunc_ln708_6_reg_1223;
reg   [10:0] lshr_ln708_s_reg_1228;
wire   [15:0] acc_0_V_fu_939_p2;
reg    ap_enable_reg_pp0_iter3;
wire   [15:0] acc_1_V_fu_957_p2;
wire   [15:0] acc_2_V_fu_975_p2;
wire   [15:0] acc_3_V_fu_993_p2;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [1:0] ap_phi_mux_w_index9_phi_fu_197_p6;
reg   [7:0] ap_phi_mux_p_read10_rewind_phi_fu_212_p6;
reg   [7:0] ap_phi_mux_p_read111_rewind_phi_fu_226_p6;
reg   [7:0] ap_phi_mux_p_read212_rewind_phi_fu_240_p6;
reg   [7:0] ap_phi_mux_p_read313_rewind_phi_fu_254_p6;
reg   [7:0] ap_phi_mux_p_read414_rewind_phi_fu_268_p6;
reg   [7:0] ap_phi_mux_p_read515_rewind_phi_fu_282_p6;
reg   [7:0] ap_phi_mux_p_read616_rewind_phi_fu_296_p6;
reg   [7:0] ap_phi_mux_p_read717_rewind_phi_fu_310_p6;
reg   [7:0] ap_phi_mux_p_read10_phi_phi_fu_324_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read10_phi_reg_320;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read10_phi_reg_320;
reg   [7:0] ap_phi_mux_p_read111_phi_phi_fu_336_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read111_phi_reg_332;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read111_phi_reg_332;
reg   [7:0] ap_phi_mux_p_read212_phi_phi_fu_348_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read212_phi_reg_344;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read212_phi_reg_344;
reg   [7:0] ap_phi_mux_p_read313_phi_phi_fu_360_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read313_phi_reg_356;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read313_phi_reg_356;
reg   [7:0] ap_phi_mux_p_read414_phi_phi_fu_372_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read414_phi_reg_368;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read414_phi_reg_368;
reg   [7:0] ap_phi_mux_p_read515_phi_phi_fu_384_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read515_phi_reg_380;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read515_phi_reg_380;
reg   [7:0] ap_phi_mux_p_read616_phi_phi_fu_396_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read616_phi_reg_392;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read616_phi_reg_392;
reg   [7:0] ap_phi_mux_p_read717_phi_phi_fu_408_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read717_phi_reg_404;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read717_phi_reg_404;
wire   [63:0] zext_ln59_fu_472_p1;
wire   [2:0] zext_ln46_fu_489_p1;
wire   [2:0] xor_ln_fu_519_p3;
wire   [7:0] mul_ln1118_fu_757_p0;
wire  signed [7:0] mul_ln1118_fu_757_p1;
wire   [15:0] mul_ln1118_fu_757_p2;
wire   [7:0] mul_ln1118_1_fu_779_p0;
wire  signed [7:0] mul_ln1118_1_fu_779_p1;
wire   [15:0] mul_ln1118_1_fu_779_p2;
wire   [7:0] mul_ln1118_2_fu_801_p0;
wire  signed [7:0] mul_ln1118_2_fu_801_p1;
wire   [15:0] mul_ln1118_2_fu_801_p2;
wire   [7:0] mul_ln1118_3_fu_823_p0;
wire  signed [7:0] mul_ln1118_3_fu_823_p1;
wire   [15:0] mul_ln1118_3_fu_823_p2;
wire   [7:0] mul_ln1118_4_fu_845_p0;
wire  signed [7:0] mul_ln1118_4_fu_845_p1;
wire   [15:0] mul_ln1118_4_fu_845_p2;
wire   [7:0] mul_ln1118_5_fu_867_p0;
wire  signed [7:0] mul_ln1118_5_fu_867_p1;
wire   [15:0] mul_ln1118_5_fu_867_p2;
wire   [7:0] mul_ln1118_6_fu_889_p0;
wire  signed [7:0] mul_ln1118_6_fu_889_p1;
wire   [15:0] mul_ln1118_6_fu_889_p2;
wire   [3:0] mul_ln708_fu_911_p0;
wire   [7:0] mul_ln708_fu_911_p1;
wire   [11:0] mul_ln708_fu_911_p2;
wire  signed [15:0] sext_ln708_fu_927_p1;
wire  signed [15:0] sext_ln708_1_fu_930_p1;
wire   [15:0] add_ln703_fu_933_p2;
wire  signed [15:0] sext_ln708_2_fu_945_p1;
wire  signed [15:0] sext_ln708_3_fu_948_p1;
wire   [15:0] add_ln703_2_fu_951_p2;
wire  signed [15:0] sext_ln708_4_fu_963_p1;
wire  signed [15:0] sext_ln708_5_fu_966_p1;
wire   [15:0] add_ln703_4_fu_969_p2;
wire  signed [15:0] sext_ln708_6_fu_981_p1;
wire   [15:0] zext_ln708_2_fu_984_p1;
wire   [15:0] add_ln703_6_fu_987_p2;
wire   [16:0] res_0_V_write_assign_fu_999_p3;
wire   [16:0] res_1_V_write_assign_fu_1007_p3;
wire   [16:0] res_2_V_write_assign_fu_1015_p3;
wire   [16:0] res_3_V_write_assign_fu_1023_p3;
reg   [16:0] ap_return_0_preg;
reg   [16:0] ap_return_1_preg;
reg   [16:0] ap_return_2_preg;
reg   [16:0] ap_return_3_preg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to2;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [15:0] mul_ln1118_1_fu_779_p00;
wire   [15:0] mul_ln1118_2_fu_801_p00;
wire   [15:0] mul_ln1118_3_fu_823_p00;
wire   [15:0] mul_ln1118_4_fu_845_p00;
wire   [15:0] mul_ln1118_5_fu_867_p00;
wire   [15:0] mul_ln1118_6_fu_889_p00;
wire   [15:0] mul_ln1118_fu_757_p00;
wire   [11:0] mul_ln708_fu_911_p00;
wire   [11:0] mul_ln708_fu_911_p10;
reg    ap_condition_218;
reg    ap_condition_44;
reg    ap_condition_212;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_return_0_preg = 17'd0;
#0 ap_return_1_preg = 17'd0;
#0 ap_return_2_preg = 17'd0;
#0 ap_return_3_preg = 17'd0;
end

dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config5_0_0_0_0_0_w5_V #(
    .DataWidth( 60 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
w5_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w5_V_address0),
    .ce0(w5_V_ce0),
    .q0(w5_V_q0)
);

myproject_mux_83_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
myproject_mux_83_8_1_1_U77(
    .din0(ap_phi_mux_p_read10_phi_phi_fu_324_p4),
    .din1(ap_phi_mux_p_read111_phi_phi_fu_336_p4),
    .din2(ap_phi_mux_p_read212_phi_phi_fu_348_p4),
    .din3(ap_phi_mux_p_read313_phi_phi_fu_360_p4),
    .din4(ap_phi_mux_p_read313_phi_phi_fu_360_p4),
    .din5(ap_phi_mux_p_read313_phi_phi_fu_360_p4),
    .din6(ap_phi_mux_p_read313_phi_phi_fu_360_p4),
    .din7(ap_phi_mux_p_read313_phi_phi_fu_360_p4),
    .din8(zext_ln46_fu_489_p1),
    .dout(phi_ln_fu_493_p10)
);

myproject_mux_83_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
myproject_mux_83_8_1_1_U78(
    .din0(ap_phi_mux_p_read717_phi_phi_fu_408_p4),
    .din1(ap_phi_mux_p_read717_phi_phi_fu_408_p4),
    .din2(ap_phi_mux_p_read717_phi_phi_fu_408_p4),
    .din3(ap_phi_mux_p_read717_phi_phi_fu_408_p4),
    .din4(ap_phi_mux_p_read414_phi_phi_fu_372_p4),
    .din5(ap_phi_mux_p_read515_phi_phi_fu_384_p4),
    .din6(ap_phi_mux_p_read616_phi_phi_fu_396_p4),
    .din7(ap_phi_mux_p_read717_phi_phi_fu_408_p4),
    .din8(xor_ln_fu_519_p3),
    .dout(phi_ln59_1_fu_527_p10)
);

myproject_mux_83_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
myproject_mux_83_8_1_1_U79(
    .din0(ap_phi_mux_p_read10_phi_phi_fu_324_p4),
    .din1(ap_phi_mux_p_read111_phi_phi_fu_336_p4),
    .din2(ap_phi_mux_p_read212_phi_phi_fu_348_p4),
    .din3(ap_phi_mux_p_read313_phi_phi_fu_360_p4),
    .din4(ap_phi_mux_p_read313_phi_phi_fu_360_p4),
    .din5(ap_phi_mux_p_read313_phi_phi_fu_360_p4),
    .din6(ap_phi_mux_p_read313_phi_phi_fu_360_p4),
    .din7(ap_phi_mux_p_read313_phi_phi_fu_360_p4),
    .din8(zext_ln46_fu_489_p1),
    .dout(phi_ln59_2_fu_559_p10)
);

myproject_mux_83_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
myproject_mux_83_8_1_1_U80(
    .din0(ap_phi_mux_p_read717_phi_phi_fu_408_p4),
    .din1(ap_phi_mux_p_read717_phi_phi_fu_408_p4),
    .din2(ap_phi_mux_p_read717_phi_phi_fu_408_p4),
    .din3(ap_phi_mux_p_read717_phi_phi_fu_408_p4),
    .din4(ap_phi_mux_p_read414_phi_phi_fu_372_p4),
    .din5(ap_phi_mux_p_read515_phi_phi_fu_384_p4),
    .din6(ap_phi_mux_p_read616_phi_phi_fu_396_p4),
    .din7(ap_phi_mux_p_read717_phi_phi_fu_408_p4),
    .din8(xor_ln_fu_519_p3),
    .dout(phi_ln59_3_fu_591_p10)
);

myproject_mux_83_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
myproject_mux_83_8_1_1_U81(
    .din0(ap_phi_mux_p_read10_phi_phi_fu_324_p4),
    .din1(ap_phi_mux_p_read111_phi_phi_fu_336_p4),
    .din2(ap_phi_mux_p_read212_phi_phi_fu_348_p4),
    .din3(ap_phi_mux_p_read313_phi_phi_fu_360_p4),
    .din4(ap_phi_mux_p_read313_phi_phi_fu_360_p4),
    .din5(ap_phi_mux_p_read313_phi_phi_fu_360_p4),
    .din6(ap_phi_mux_p_read313_phi_phi_fu_360_p4),
    .din7(ap_phi_mux_p_read313_phi_phi_fu_360_p4),
    .din8(zext_ln46_fu_489_p1),
    .dout(phi_ln59_4_fu_623_p10)
);

myproject_mux_83_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
myproject_mux_83_8_1_1_U82(
    .din0(ap_phi_mux_p_read717_phi_phi_fu_408_p4),
    .din1(ap_phi_mux_p_read717_phi_phi_fu_408_p4),
    .din2(ap_phi_mux_p_read717_phi_phi_fu_408_p4),
    .din3(ap_phi_mux_p_read717_phi_phi_fu_408_p4),
    .din4(ap_phi_mux_p_read414_phi_phi_fu_372_p4),
    .din5(ap_phi_mux_p_read515_phi_phi_fu_384_p4),
    .din6(ap_phi_mux_p_read616_phi_phi_fu_396_p4),
    .din7(ap_phi_mux_p_read717_phi_phi_fu_408_p4),
    .din8(xor_ln_fu_519_p3),
    .dout(phi_ln59_5_fu_655_p10)
);

myproject_mux_83_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
myproject_mux_83_8_1_1_U83(
    .din0(ap_phi_mux_p_read10_phi_phi_fu_324_p4),
    .din1(ap_phi_mux_p_read111_phi_phi_fu_336_p4),
    .din2(ap_phi_mux_p_read212_phi_phi_fu_348_p4),
    .din3(ap_phi_mux_p_read313_phi_phi_fu_360_p4),
    .din4(ap_phi_mux_p_read313_phi_phi_fu_360_p4),
    .din5(ap_phi_mux_p_read313_phi_phi_fu_360_p4),
    .din6(ap_phi_mux_p_read313_phi_phi_fu_360_p4),
    .din7(ap_phi_mux_p_read313_phi_phi_fu_360_p4),
    .din8(zext_ln46_fu_489_p1),
    .dout(phi_ln59_6_fu_687_p10)
);

myproject_mux_83_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
myproject_mux_83_8_1_1_U84(
    .din0(ap_phi_mux_p_read717_phi_phi_fu_408_p4),
    .din1(ap_phi_mux_p_read717_phi_phi_fu_408_p4),
    .din2(ap_phi_mux_p_read717_phi_phi_fu_408_p4),
    .din3(ap_phi_mux_p_read717_phi_phi_fu_408_p4),
    .din4(ap_phi_mux_p_read414_phi_phi_fu_372_p4),
    .din5(ap_phi_mux_p_read515_phi_phi_fu_384_p4),
    .din6(ap_phi_mux_p_read616_phi_phi_fu_396_p4),
    .din7(ap_phi_mux_p_read717_phi_phi_fu_408_p4),
    .din8(xor_ln_fu_519_p3),
    .dout(phi_ln59_7_fu_719_p10)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1109_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_0_preg[1] <= 1'b0;
        ap_return_0_preg[2] <= 1'b0;
        ap_return_0_preg[3] <= 1'b0;
        ap_return_0_preg[4] <= 1'b0;
        ap_return_0_preg[5] <= 1'b0;
        ap_return_0_preg[6] <= 1'b0;
        ap_return_0_preg[7] <= 1'b0;
        ap_return_0_preg[8] <= 1'b0;
        ap_return_0_preg[9] <= 1'b0;
        ap_return_0_preg[10] <= 1'b0;
        ap_return_0_preg[11] <= 1'b0;
        ap_return_0_preg[12] <= 1'b0;
        ap_return_0_preg[13] <= 1'b0;
        ap_return_0_preg[14] <= 1'b0;
        ap_return_0_preg[15] <= 1'b0;
        ap_return_0_preg[16] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1109_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
                        ap_return_0_preg[16 : 1] <= res_0_V_write_assign_fu_999_p3[16 : 1];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_1_preg[1] <= 1'b0;
        ap_return_1_preg[2] <= 1'b0;
        ap_return_1_preg[3] <= 1'b0;
        ap_return_1_preg[4] <= 1'b0;
        ap_return_1_preg[5] <= 1'b0;
        ap_return_1_preg[6] <= 1'b0;
        ap_return_1_preg[7] <= 1'b0;
        ap_return_1_preg[8] <= 1'b0;
        ap_return_1_preg[9] <= 1'b0;
        ap_return_1_preg[10] <= 1'b0;
        ap_return_1_preg[11] <= 1'b0;
        ap_return_1_preg[12] <= 1'b0;
        ap_return_1_preg[13] <= 1'b0;
        ap_return_1_preg[14] <= 1'b0;
        ap_return_1_preg[15] <= 1'b0;
        ap_return_1_preg[16] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1109_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
                        ap_return_1_preg[16 : 1] <= res_1_V_write_assign_fu_1007_p3[16 : 1];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_2_preg[1] <= 1'b0;
        ap_return_2_preg[2] <= 1'b0;
        ap_return_2_preg[3] <= 1'b0;
        ap_return_2_preg[4] <= 1'b0;
        ap_return_2_preg[5] <= 1'b0;
        ap_return_2_preg[6] <= 1'b0;
        ap_return_2_preg[7] <= 1'b0;
        ap_return_2_preg[8] <= 1'b0;
        ap_return_2_preg[9] <= 1'b0;
        ap_return_2_preg[10] <= 1'b0;
        ap_return_2_preg[11] <= 1'b0;
        ap_return_2_preg[12] <= 1'b0;
        ap_return_2_preg[13] <= 1'b0;
        ap_return_2_preg[14] <= 1'b0;
        ap_return_2_preg[15] <= 1'b0;
        ap_return_2_preg[16] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1109_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
                        ap_return_2_preg[16 : 1] <= res_2_V_write_assign_fu_1015_p3[16 : 1];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_3_preg[1] <= 1'b0;
        ap_return_3_preg[2] <= 1'b0;
        ap_return_3_preg[3] <= 1'b0;
        ap_return_3_preg[4] <= 1'b0;
        ap_return_3_preg[5] <= 1'b0;
        ap_return_3_preg[6] <= 1'b0;
        ap_return_3_preg[7] <= 1'b0;
        ap_return_3_preg[8] <= 1'b0;
        ap_return_3_preg[9] <= 1'b0;
        ap_return_3_preg[10] <= 1'b0;
        ap_return_3_preg[11] <= 1'b0;
        ap_return_3_preg[12] <= 1'b0;
        ap_return_3_preg[13] <= 1'b0;
        ap_return_3_preg[14] <= 1'b0;
        ap_return_3_preg[15] <= 1'b0;
        ap_return_3_preg[16] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1109_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
                        ap_return_3_preg[16 : 1] <= res_3_V_write_assign_fu_1023_p3[16 : 1];
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_44)) begin
        if ((ap_phi_mux_do_init_phi_fu_181_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read10_phi_reg_320 <= p_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read10_phi_reg_320 <= ap_phi_reg_pp0_iter0_p_read10_phi_reg_320;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_44)) begin
        if ((ap_phi_mux_do_init_phi_fu_181_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read111_phi_reg_332 <= p_read1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read111_phi_reg_332 <= ap_phi_reg_pp0_iter0_p_read111_phi_reg_332;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_44)) begin
        if ((ap_phi_mux_do_init_phi_fu_181_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read212_phi_reg_344 <= p_read2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read212_phi_reg_344 <= ap_phi_reg_pp0_iter0_p_read212_phi_reg_344;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_44)) begin
        if ((ap_phi_mux_do_init_phi_fu_181_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read313_phi_reg_356 <= p_read3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read313_phi_reg_356 <= ap_phi_reg_pp0_iter0_p_read313_phi_reg_356;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_44)) begin
        if ((ap_phi_mux_do_init_phi_fu_181_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read414_phi_reg_368 <= p_read4;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read414_phi_reg_368 <= ap_phi_reg_pp0_iter0_p_read414_phi_reg_368;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_44)) begin
        if ((ap_phi_mux_do_init_phi_fu_181_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read515_phi_reg_380 <= p_read5;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read515_phi_reg_380 <= ap_phi_reg_pp0_iter0_p_read515_phi_reg_380;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_44)) begin
        if ((ap_phi_mux_do_init_phi_fu_181_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read616_phi_reg_392 <= p_read6;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read616_phi_reg_392 <= ap_phi_reg_pp0_iter0_p_read616_phi_reg_392;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_44)) begin
        if ((ap_phi_mux_do_init_phi_fu_181_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read717_phi_reg_404 <= p_read7;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read717_phi_reg_404 <= ap_phi_reg_pp0_iter0_p_read717_phi_reg_404;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_1109 == 1'd0))) begin
        do_init_reg_177 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1109 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        do_init_reg_177 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln46_reg_1109_pp0_iter2_reg == 1'd0))) begin
        p_Val2_16_reg_430 <= acc_1_V_fu_957_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1109_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_16_reg_430 <= 16'd320;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln46_reg_1109_pp0_iter2_reg == 1'd0))) begin
        p_Val2_24_reg_444 <= acc_2_V_fu_975_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1109_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_24_reg_444 <= 16'd65376;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln46_reg_1109_pp0_iter2_reg == 1'd0))) begin
        p_Val2_32_reg_458 <= acc_3_V_fu_993_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1109_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_32_reg_458 <= 16'd288;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln46_reg_1109_pp0_iter2_reg == 1'd0))) begin
        p_Val2_8_reg_416 <= acc_0_V_fu_939_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1109_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_8_reg_416 <= 16'd480;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_212)) begin
        if ((do_init_reg_177 == 1'd0)) begin
            p_read10_phi_reg_320 <= ap_phi_mux_p_read10_rewind_phi_fu_212_p6;
        end else if ((1'b1 == 1'b1)) begin
            p_read10_phi_reg_320 <= ap_phi_reg_pp0_iter1_p_read10_phi_reg_320;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_212)) begin
        if ((do_init_reg_177 == 1'd0)) begin
            p_read111_phi_reg_332 <= ap_phi_mux_p_read111_rewind_phi_fu_226_p6;
        end else if ((1'b1 == 1'b1)) begin
            p_read111_phi_reg_332 <= ap_phi_reg_pp0_iter1_p_read111_phi_reg_332;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_212)) begin
        if ((do_init_reg_177 == 1'd0)) begin
            p_read212_phi_reg_344 <= ap_phi_mux_p_read212_rewind_phi_fu_240_p6;
        end else if ((1'b1 == 1'b1)) begin
            p_read212_phi_reg_344 <= ap_phi_reg_pp0_iter1_p_read212_phi_reg_344;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_212)) begin
        if ((do_init_reg_177 == 1'd0)) begin
            p_read313_phi_reg_356 <= ap_phi_mux_p_read313_rewind_phi_fu_254_p6;
        end else if ((1'b1 == 1'b1)) begin
            p_read313_phi_reg_356 <= ap_phi_reg_pp0_iter1_p_read313_phi_reg_356;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_212)) begin
        if ((do_init_reg_177 == 1'd0)) begin
            p_read414_phi_reg_368 <= ap_phi_mux_p_read414_rewind_phi_fu_268_p6;
        end else if ((1'b1 == 1'b1)) begin
            p_read414_phi_reg_368 <= ap_phi_reg_pp0_iter1_p_read414_phi_reg_368;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_212)) begin
        if ((do_init_reg_177 == 1'd0)) begin
            p_read515_phi_reg_380 <= ap_phi_mux_p_read515_rewind_phi_fu_282_p6;
        end else if ((1'b1 == 1'b1)) begin
            p_read515_phi_reg_380 <= ap_phi_reg_pp0_iter1_p_read515_phi_reg_380;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_212)) begin
        if ((do_init_reg_177 == 1'd0)) begin
            p_read616_phi_reg_392 <= ap_phi_mux_p_read616_rewind_phi_fu_296_p6;
        end else if ((1'b1 == 1'b1)) begin
            p_read616_phi_reg_392 <= ap_phi_reg_pp0_iter1_p_read616_phi_reg_392;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_212)) begin
        if ((do_init_reg_177 == 1'd0)) begin
            p_read717_phi_reg_404 <= ap_phi_mux_p_read717_rewind_phi_fu_310_p6;
        end else if ((1'b1 == 1'b1)) begin
            p_read717_phi_reg_404 <= ap_phi_reg_pp0_iter1_p_read717_phi_reg_404;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_1109 == 1'd0))) begin
        w_index9_reg_193 <= w_index_reg_1104;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1109 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        w_index9_reg_193 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln46_reg_1109 <= icmp_ln46_fu_483_p2;
        icmp_ln46_reg_1109_pp0_iter1_reg <= icmp_ln46_reg_1109;
        phi_ln59_1_reg_1123 <= phi_ln59_1_fu_527_p10;
        phi_ln59_2_reg_1133 <= phi_ln59_2_fu_559_p10;
        phi_ln59_3_reg_1143 <= phi_ln59_3_fu_591_p10;
        phi_ln59_4_reg_1153 <= phi_ln59_4_fu_623_p10;
        phi_ln59_5_reg_1163 <= phi_ln59_5_fu_655_p10;
        phi_ln59_6_reg_1173 <= phi_ln59_6_fu_687_p10;
        phi_ln59_7_reg_1183 <= phi_ln59_7_fu_719_p10;
        phi_ln_reg_1113 <= phi_ln_fu_493_p10;
        tmp_3_reg_1128 <= {{w5_V_q0[15:8]}};
        tmp_4_reg_1138 <= {{w5_V_q0[23:16]}};
        tmp_5_reg_1148 <= {{w5_V_q0[31:24]}};
        tmp_6_reg_1158 <= {{w5_V_q0[39:32]}};
        tmp_7_reg_1168 <= {{w5_V_q0[47:40]}};
        tmp_8_reg_1178 <= {{w5_V_q0[55:48]}};
        tmp_s_reg_1188 <= {{w5_V_q0[59:56]}};
        trunc_ln59_reg_1118 <= trunc_ln59_fu_515_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln46_reg_1109_pp0_iter2_reg <= icmp_ln46_reg_1109_pp0_iter1_reg;
        lshr_ln708_s_reg_1228 <= {{mul_ln708_fu_911_p2[11:1]}};
        trunc_ln708_2_reg_1203 <= {{mul_ln1118_2_fu_801_p2[15:1]}};
        trunc_ln708_3_reg_1208 <= {{mul_ln1118_3_fu_823_p2[15:1]}};
        trunc_ln708_4_reg_1213 <= {{mul_ln1118_4_fu_845_p2[15:1]}};
        trunc_ln708_5_reg_1218 <= {{mul_ln1118_5_fu_867_p2[15:1]}};
        trunc_ln708_6_reg_1223 <= {{mul_ln1118_6_fu_889_p2[15:1]}};
        trunc_ln708_s_reg_1198 <= {{mul_ln1118_1_fu_779_p2[15:1]}};
        trunc_ln_reg_1193 <= {{mul_ln1118_fu_757_p2[15:1]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln46_reg_1109_pp0_iter1_reg == 1'd0))) begin
        p_read10_rewind_reg_208 <= p_read10_phi_reg_320;
        p_read111_rewind_reg_222 <= p_read111_phi_reg_332;
        p_read212_rewind_reg_236 <= p_read212_phi_reg_344;
        p_read313_rewind_reg_250 <= p_read313_phi_reg_356;
        p_read414_rewind_reg_264 <= p_read414_phi_reg_368;
        p_read515_rewind_reg_278 <= p_read515_phi_reg_380;
        p_read616_rewind_reg_292 <= p_read616_phi_reg_392;
        p_read717_rewind_reg_306 <= p_read717_phi_reg_404;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_index_reg_1104 <= w_index_fu_477_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1109_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_218)) begin
        if ((icmp_ln46_reg_1109 == 1'd1)) begin
            ap_phi_mux_do_init_phi_fu_181_p6 = 1'd1;
        end else if ((icmp_ln46_reg_1109 == 1'd0)) begin
            ap_phi_mux_do_init_phi_fu_181_p6 = 1'd0;
        end else begin
            ap_phi_mux_do_init_phi_fu_181_p6 = do_init_reg_177;
        end
    end else begin
        ap_phi_mux_do_init_phi_fu_181_p6 = do_init_reg_177;
    end
end

always @ (*) begin
    if ((do_init_reg_177 == 1'd0)) begin
        ap_phi_mux_p_read10_phi_phi_fu_324_p4 = ap_phi_mux_p_read10_rewind_phi_fu_212_p6;
    end else begin
        ap_phi_mux_p_read10_phi_phi_fu_324_p4 = ap_phi_reg_pp0_iter1_p_read10_phi_reg_320;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln46_reg_1109_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_p_read10_rewind_phi_fu_212_p6 = p_read10_phi_reg_320;
    end else begin
        ap_phi_mux_p_read10_rewind_phi_fu_212_p6 = p_read10_rewind_reg_208;
    end
end

always @ (*) begin
    if ((do_init_reg_177 == 1'd0)) begin
        ap_phi_mux_p_read111_phi_phi_fu_336_p4 = ap_phi_mux_p_read111_rewind_phi_fu_226_p6;
    end else begin
        ap_phi_mux_p_read111_phi_phi_fu_336_p4 = ap_phi_reg_pp0_iter1_p_read111_phi_reg_332;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln46_reg_1109_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_p_read111_rewind_phi_fu_226_p6 = p_read111_phi_reg_332;
    end else begin
        ap_phi_mux_p_read111_rewind_phi_fu_226_p6 = p_read111_rewind_reg_222;
    end
end

always @ (*) begin
    if ((do_init_reg_177 == 1'd0)) begin
        ap_phi_mux_p_read212_phi_phi_fu_348_p4 = ap_phi_mux_p_read212_rewind_phi_fu_240_p6;
    end else begin
        ap_phi_mux_p_read212_phi_phi_fu_348_p4 = ap_phi_reg_pp0_iter1_p_read212_phi_reg_344;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln46_reg_1109_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_p_read212_rewind_phi_fu_240_p6 = p_read212_phi_reg_344;
    end else begin
        ap_phi_mux_p_read212_rewind_phi_fu_240_p6 = p_read212_rewind_reg_236;
    end
end

always @ (*) begin
    if ((do_init_reg_177 == 1'd0)) begin
        ap_phi_mux_p_read313_phi_phi_fu_360_p4 = ap_phi_mux_p_read313_rewind_phi_fu_254_p6;
    end else begin
        ap_phi_mux_p_read313_phi_phi_fu_360_p4 = ap_phi_reg_pp0_iter1_p_read313_phi_reg_356;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln46_reg_1109_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_p_read313_rewind_phi_fu_254_p6 = p_read313_phi_reg_356;
    end else begin
        ap_phi_mux_p_read313_rewind_phi_fu_254_p6 = p_read313_rewind_reg_250;
    end
end

always @ (*) begin
    if ((do_init_reg_177 == 1'd0)) begin
        ap_phi_mux_p_read414_phi_phi_fu_372_p4 = ap_phi_mux_p_read414_rewind_phi_fu_268_p6;
    end else begin
        ap_phi_mux_p_read414_phi_phi_fu_372_p4 = ap_phi_reg_pp0_iter1_p_read414_phi_reg_368;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln46_reg_1109_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_p_read414_rewind_phi_fu_268_p6 = p_read414_phi_reg_368;
    end else begin
        ap_phi_mux_p_read414_rewind_phi_fu_268_p6 = p_read414_rewind_reg_264;
    end
end

always @ (*) begin
    if ((do_init_reg_177 == 1'd0)) begin
        ap_phi_mux_p_read515_phi_phi_fu_384_p4 = ap_phi_mux_p_read515_rewind_phi_fu_282_p6;
    end else begin
        ap_phi_mux_p_read515_phi_phi_fu_384_p4 = ap_phi_reg_pp0_iter1_p_read515_phi_reg_380;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln46_reg_1109_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_p_read515_rewind_phi_fu_282_p6 = p_read515_phi_reg_380;
    end else begin
        ap_phi_mux_p_read515_rewind_phi_fu_282_p6 = p_read515_rewind_reg_278;
    end
end

always @ (*) begin
    if ((do_init_reg_177 == 1'd0)) begin
        ap_phi_mux_p_read616_phi_phi_fu_396_p4 = ap_phi_mux_p_read616_rewind_phi_fu_296_p6;
    end else begin
        ap_phi_mux_p_read616_phi_phi_fu_396_p4 = ap_phi_reg_pp0_iter1_p_read616_phi_reg_392;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln46_reg_1109_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_p_read616_rewind_phi_fu_296_p6 = p_read616_phi_reg_392;
    end else begin
        ap_phi_mux_p_read616_rewind_phi_fu_296_p6 = p_read616_rewind_reg_292;
    end
end

always @ (*) begin
    if ((do_init_reg_177 == 1'd0)) begin
        ap_phi_mux_p_read717_phi_phi_fu_408_p4 = ap_phi_mux_p_read717_rewind_phi_fu_310_p6;
    end else begin
        ap_phi_mux_p_read717_phi_phi_fu_408_p4 = ap_phi_reg_pp0_iter1_p_read717_phi_reg_404;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln46_reg_1109_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_p_read717_rewind_phi_fu_310_p6 = p_read717_phi_reg_404;
    end else begin
        ap_phi_mux_p_read717_rewind_phi_fu_310_p6 = p_read717_rewind_reg_306;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_218)) begin
        if ((icmp_ln46_reg_1109 == 1'd1)) begin
            ap_phi_mux_w_index9_phi_fu_197_p6 = 2'd0;
        end else if ((icmp_ln46_reg_1109 == 1'd0)) begin
            ap_phi_mux_w_index9_phi_fu_197_p6 = w_index_reg_1104;
        end else begin
            ap_phi_mux_w_index9_phi_fu_197_p6 = w_index9_reg_193;
        end
    end else begin
        ap_phi_mux_w_index9_phi_fu_197_p6 = w_index9_reg_193;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_fu_483_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1109_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_0 = res_0_V_write_assign_fu_999_p3;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1109_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_1 = res_1_V_write_assign_fu_1007_p3;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1109_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_2 = res_2_V_write_assign_fu_1015_p3;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1109_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_3 = res_3_V_write_assign_fu_1023_p3;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w5_V_ce0 = 1'b1;
    end else begin
        w5_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_0_V_fu_939_p2 = (add_ln703_fu_933_p2 + p_Val2_8_reg_416);

assign acc_1_V_fu_957_p2 = (add_ln703_2_fu_951_p2 + p_Val2_16_reg_430);

assign acc_2_V_fu_975_p2 = (add_ln703_4_fu_969_p2 + p_Val2_24_reg_444);

assign acc_3_V_fu_993_p2 = (add_ln703_6_fu_987_p2 + p_Val2_32_reg_458);

assign add_ln703_2_fu_951_p2 = ($signed(sext_ln708_2_fu_945_p1) + $signed(sext_ln708_3_fu_948_p1));

assign add_ln703_4_fu_969_p2 = ($signed(sext_ln708_4_fu_963_p1) + $signed(sext_ln708_5_fu_966_p1));

assign add_ln703_6_fu_987_p2 = ($signed(sext_ln708_6_fu_981_p1) + $signed(zext_ln708_2_fu_984_p1));

assign add_ln703_fu_933_p2 = ($signed(sext_ln708_fu_927_p1) + $signed(sext_ln708_1_fu_930_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_212 = ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_218 = ((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_44 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_p_read10_phi_reg_320 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read111_phi_reg_332 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read212_phi_reg_344 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read313_phi_reg_356 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read414_phi_reg_368 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read515_phi_reg_380 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read616_phi_reg_392 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read717_phi_reg_404 = 'bx;

assign icmp_ln46_fu_483_p2 = ((ap_phi_mux_w_index9_phi_fu_197_p6 == 2'd3) ? 1'b1 : 1'b0);

assign mul_ln1118_1_fu_779_p0 = mul_ln1118_1_fu_779_p00;

assign mul_ln1118_1_fu_779_p00 = phi_ln59_1_reg_1123;

assign mul_ln1118_1_fu_779_p1 = tmp_3_reg_1128;

assign mul_ln1118_1_fu_779_p2 = ($signed({{1'b0}, {mul_ln1118_1_fu_779_p0}}) * $signed(mul_ln1118_1_fu_779_p1));

assign mul_ln1118_2_fu_801_p0 = mul_ln1118_2_fu_801_p00;

assign mul_ln1118_2_fu_801_p00 = phi_ln59_2_reg_1133;

assign mul_ln1118_2_fu_801_p1 = tmp_4_reg_1138;

assign mul_ln1118_2_fu_801_p2 = ($signed({{1'b0}, {mul_ln1118_2_fu_801_p0}}) * $signed(mul_ln1118_2_fu_801_p1));

assign mul_ln1118_3_fu_823_p0 = mul_ln1118_3_fu_823_p00;

assign mul_ln1118_3_fu_823_p00 = phi_ln59_3_reg_1143;

assign mul_ln1118_3_fu_823_p1 = tmp_5_reg_1148;

assign mul_ln1118_3_fu_823_p2 = ($signed({{1'b0}, {mul_ln1118_3_fu_823_p0}}) * $signed(mul_ln1118_3_fu_823_p1));

assign mul_ln1118_4_fu_845_p0 = mul_ln1118_4_fu_845_p00;

assign mul_ln1118_4_fu_845_p00 = phi_ln59_4_reg_1153;

assign mul_ln1118_4_fu_845_p1 = tmp_6_reg_1158;

assign mul_ln1118_4_fu_845_p2 = ($signed({{1'b0}, {mul_ln1118_4_fu_845_p0}}) * $signed(mul_ln1118_4_fu_845_p1));

assign mul_ln1118_5_fu_867_p0 = mul_ln1118_5_fu_867_p00;

assign mul_ln1118_5_fu_867_p00 = phi_ln59_5_reg_1163;

assign mul_ln1118_5_fu_867_p1 = tmp_7_reg_1168;

assign mul_ln1118_5_fu_867_p2 = ($signed({{1'b0}, {mul_ln1118_5_fu_867_p0}}) * $signed(mul_ln1118_5_fu_867_p1));

assign mul_ln1118_6_fu_889_p0 = mul_ln1118_6_fu_889_p00;

assign mul_ln1118_6_fu_889_p00 = phi_ln59_6_reg_1173;

assign mul_ln1118_6_fu_889_p1 = tmp_8_reg_1178;

assign mul_ln1118_6_fu_889_p2 = ($signed({{1'b0}, {mul_ln1118_6_fu_889_p0}}) * $signed(mul_ln1118_6_fu_889_p1));

assign mul_ln1118_fu_757_p0 = mul_ln1118_fu_757_p00;

assign mul_ln1118_fu_757_p00 = phi_ln_reg_1113;

assign mul_ln1118_fu_757_p1 = trunc_ln59_reg_1118;

assign mul_ln1118_fu_757_p2 = ($signed({{1'b0}, {mul_ln1118_fu_757_p0}}) * $signed(mul_ln1118_fu_757_p1));

assign mul_ln708_fu_911_p0 = mul_ln708_fu_911_p00;

assign mul_ln708_fu_911_p00 = tmp_s_reg_1188;

assign mul_ln708_fu_911_p1 = mul_ln708_fu_911_p10;

assign mul_ln708_fu_911_p10 = phi_ln59_7_reg_1183;

assign mul_ln708_fu_911_p2 = (mul_ln708_fu_911_p0 * mul_ln708_fu_911_p1);

assign res_0_V_write_assign_fu_999_p3 = {{acc_0_V_fu_939_p2}, {1'd0}};

assign res_1_V_write_assign_fu_1007_p3 = {{acc_1_V_fu_957_p2}, {1'd0}};

assign res_2_V_write_assign_fu_1015_p3 = {{acc_2_V_fu_975_p2}, {1'd0}};

assign res_3_V_write_assign_fu_1023_p3 = {{acc_3_V_fu_993_p2}, {1'd0}};

assign sext_ln708_1_fu_930_p1 = $signed(trunc_ln708_s_reg_1198);

assign sext_ln708_2_fu_945_p1 = $signed(trunc_ln708_2_reg_1203);

assign sext_ln708_3_fu_948_p1 = $signed(trunc_ln708_3_reg_1208);

assign sext_ln708_4_fu_963_p1 = $signed(trunc_ln708_4_reg_1213);

assign sext_ln708_5_fu_966_p1 = $signed(trunc_ln708_5_reg_1218);

assign sext_ln708_6_fu_981_p1 = $signed(trunc_ln708_6_reg_1223);

assign sext_ln708_fu_927_p1 = $signed(trunc_ln_reg_1193);

assign trunc_ln59_fu_515_p1 = w5_V_q0[7:0];

assign w5_V_address0 = zext_ln59_fu_472_p1;

assign w_index_fu_477_p2 = (2'd1 + ap_phi_mux_w_index9_phi_fu_197_p6);

assign xor_ln_fu_519_p3 = {{1'd1}, {w_index9_reg_193}};

assign zext_ln46_fu_489_p1 = w_index9_reg_193;

assign zext_ln59_fu_472_p1 = ap_phi_mux_w_index9_phi_fu_197_p6;

assign zext_ln708_2_fu_984_p1 = lshr_ln708_s_reg_1228;

always @ (posedge ap_clk) begin
    ap_return_0_preg[0] <= 1'b0;
    ap_return_1_preg[0] <= 1'b0;
    ap_return_2_preg[0] <= 1'b0;
    ap_return_3_preg[0] <= 1'b0;
end

endmodule //dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config5_0_0_0_0_0
