#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("input_4_V", 224, hls_in, 0, "ap_vld", "in_data", 1),
	Port_Property("layer17_out_0_V", 20, hls_out, 1, "ap_vld", "out_data", 1),
	Port_Property("layer17_out_1_V", 20, hls_out, 2, "ap_vld", "out_data", 1),
	Port_Property("layer17_out_2_V", 20, hls_out, 3, "ap_vld", "out_data", 1),
	Port_Property("layer17_out_3_V", 20, hls_out, 4, "ap_vld", "out_data", 1),
	Port_Property("layer17_out_4_V", 20, hls_out, 5, "ap_vld", "out_data", 1),
	Port_Property("layer17_out_5_V", 20, hls_out, 6, "ap_vld", "out_data", 1),
	Port_Property("layer17_out_6_V", 20, hls_out, 7, "ap_vld", "out_data", 1),
	Port_Property("layer17_out_7_V", 20, hls_out, 8, "ap_vld", "out_data", 1),
	Port_Property("layer17_out_8_V", 20, hls_out, 9, "ap_vld", "out_data", 1),
	Port_Property("layer17_out_9_V", 20, hls_out, 10, "ap_vld", "out_data", 1),
	Port_Property("layer17_out_10_V", 20, hls_out, 11, "ap_vld", "out_data", 1),
	Port_Property("layer17_out_11_V", 20, hls_out, 12, "ap_vld", "out_data", 1),
	Port_Property("layer17_out_12_V", 20, hls_out, 13, "ap_vld", "out_data", 1),
	Port_Property("layer17_out_13_V", 20, hls_out, 14, "ap_vld", "out_data", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("input_4_V_ap_vld", 1, hls_in, 0, "ap_vld", "in_vld", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("layer17_out_0_V_ap_vld", 1, hls_out, 1, "ap_vld", "out_vld", 1),
	Port_Property("layer17_out_1_V_ap_vld", 1, hls_out, 2, "ap_vld", "out_vld", 1),
	Port_Property("layer17_out_2_V_ap_vld", 1, hls_out, 3, "ap_vld", "out_vld", 1),
	Port_Property("layer17_out_3_V_ap_vld", 1, hls_out, 4, "ap_vld", "out_vld", 1),
	Port_Property("layer17_out_4_V_ap_vld", 1, hls_out, 5, "ap_vld", "out_vld", 1),
	Port_Property("layer17_out_5_V_ap_vld", 1, hls_out, 6, "ap_vld", "out_vld", 1),
	Port_Property("layer17_out_6_V_ap_vld", 1, hls_out, 7, "ap_vld", "out_vld", 1),
	Port_Property("layer17_out_7_V_ap_vld", 1, hls_out, 8, "ap_vld", "out_vld", 1),
	Port_Property("layer17_out_8_V_ap_vld", 1, hls_out, 9, "ap_vld", "out_vld", 1),
	Port_Property("layer17_out_9_V_ap_vld", 1, hls_out, 10, "ap_vld", "out_vld", 1),
	Port_Property("layer17_out_10_V_ap_vld", 1, hls_out, 11, "ap_vld", "out_vld", 1),
	Port_Property("layer17_out_11_V_ap_vld", 1, hls_out, 12, "ap_vld", "out_vld", 1),
	Port_Property("layer17_out_12_V_ap_vld", 1, hls_out, 13, "ap_vld", "out_vld", 1),
	Port_Property("layer17_out_13_V_ap_vld", 1, hls_out, 14, "ap_vld", "out_vld", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "myproject";
