// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] p_read;
input  [7:0] p_read1;
input  [7:0] p_read2;
input  [7:0] p_read3;
output  [16:0] ap_return_0;
output  [16:0] ap_return_1;
output  [16:0] ap_return_2;
output  [16:0] ap_return_3;
output  [16:0] ap_return_4;
output  [16:0] ap_return_5;
output  [16:0] ap_return_6;
output  [16:0] ap_return_7;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1;
wire   [12:0] zext_ln1118_37_fu_134_p1;
reg   [12:0] zext_ln1118_37_reg_1285;
wire   [12:0] zext_ln1118_42_fu_138_p1;
reg   [12:0] zext_ln1118_42_reg_1290;
wire   [9:0] shl_ln1118_13_fu_146_p3;
reg   [9:0] shl_ln1118_13_reg_1295;
reg  signed [9:0] tmp_159_reg_1301;
reg   [6:0] lshr_ln708_5_reg_1307;
reg   [11:0] trunc_ln1_reg_1312;
reg   [9:0] lshr_ln708_6_reg_1317;
reg   [11:0] trunc_ln1118_6_reg_1323;
reg   [11:0] trunc_ln1118_7_reg_1328;
reg   [10:0] tmp_154_reg_1333;
wire    ap_CS_fsm_state2;
reg   [12:0] tmp_155_reg_1338;
wire   [11:0] add_ln703_31_fu_364_p2;
reg   [11:0] add_ln703_31_reg_1343;
reg   [11:0] tmp_156_reg_1348;
reg   [12:0] tmp_157_reg_1353;
reg   [11:0] tmp_158_reg_1358;
reg   [11:0] tmp_160_reg_1363;
wire   [12:0] add_ln703_38_fu_464_p2;
reg   [12:0] add_ln703_38_reg_1368;
reg   [12:0] tmp_161_reg_1373;
reg   [12:0] tmp_162_reg_1378;
wire   [12:0] add_ln703_42_fu_514_p2;
reg   [12:0] add_ln703_42_reg_1383;
reg   [13:0] tmp_165_reg_1388;
wire   [12:0] add_ln703_44_fu_619_p2;
reg   [12:0] add_ln703_44_reg_1393;
wire   [11:0] add_ln703_45_fu_625_p2;
reg   [11:0] add_ln703_45_reg_1398;
reg   [13:0] tmp_166_reg_1403;
reg   [11:0] tmp_167_reg_1408;
wire   [12:0] add_ln703_50_fu_729_p2;
reg   [12:0] add_ln703_50_reg_1413;
reg   [11:0] tmp_169_reg_1418;
reg   [13:0] tmp_170_reg_1423;
wire   [13:0] add_ln703_54_fu_832_p2;
reg   [13:0] add_ln703_54_reg_1428;
reg   [12:0] lshr_ln708_8_reg_1433;
wire   [14:0] add_ln703_56_fu_909_p2;
reg   [14:0] add_ln703_56_reg_1438;
wire   [8:0] add_ln703_57_fu_915_p2;
reg   [8:0] add_ln703_57_reg_1443;
wire   [10:0] zext_ln1118_47_fu_154_p1;
wire   [10:0] sub_ln1118_14_fu_158_p2;
wire   [7:0] mul_ln708_3_fu_184_p0;
wire   [12:0] mul_ln708_3_fu_184_p2;
wire   [10:0] zext_ln703_fu_142_p1;
wire   [10:0] add_ln1118_5_fu_200_p2;
wire   [7:0] mul_ln708_4_fu_216_p0;
wire   [12:0] mul_ln708_4_fu_216_p2;
wire   [7:0] mul_ln708_5_fu_232_p0;
wire   [12:0] mul_ln708_5_fu_232_p2;
wire   [7:0] mul_ln708_fu_260_p0;
wire   [11:0] zext_ln1118_34_fu_252_p1;
wire   [11:0] mul_ln708_fu_260_p2;
wire   [12:0] shl_ln_fu_279_p3;
wire   [10:0] shl_ln1118_s_fu_290_p3;
wire   [13:0] zext_ln1118_39_fu_297_p1;
wire   [13:0] zext_ln1118_38_fu_286_p1;
wire   [13:0] sub_ln1118_fu_301_p2;
wire   [11:0] shl_ln1118_11_fu_323_p3;
wire   [9:0] shl_ln1118_12_fu_334_p3;
wire   [12:0] zext_ln1118_43_fu_330_p1;
wire   [12:0] zext_ln1118_44_fu_341_p1;
wire   [12:0] add_ln1118_fu_345_p2;
wire   [11:0] zext_ln703_10_fu_361_p1;
wire   [11:0] trunc_ln_fu_351_p4;
wire   [7:0] mul_ln1118_fu_370_p0;
wire   [12:0] zext_ln1118_fu_248_p1;
wire   [12:0] mul_ln1118_fu_370_p2;
wire   [7:0] mul_ln1118_3_fu_386_p0;
wire   [13:0] mul_ln1118_3_fu_386_p2;
wire   [12:0] sub_ln1118_13_fu_402_p2;
wire   [7:0] mul_ln708_2_fu_424_p0;
wire   [12:0] mul_ln708_2_fu_424_p2;
wire   [10:0] shl_ln3_fu_443_p3;
wire   [11:0] zext_ln703_12_fu_450_p1;
wire   [11:0] add_ln703_37_fu_454_p2;
wire   [12:0] zext_ln1118_48_fu_440_p1;
wire  signed [12:0] sext_ln703_fu_460_p1;
wire   [7:0] mul_ln1118_4_fu_470_p0;
wire   [13:0] mul_ln1118_4_fu_470_p2;
wire   [7:0] mul_ln1118_5_fu_486_p0;
wire   [13:0] mul_ln1118_5_fu_486_p2;
wire   [11:0] add_ln703_41_fu_505_p2;
wire   [12:0] zext_ln703_13_fu_502_p1;
wire   [12:0] zext_ln703_14_fu_510_p1;
wire   [10:0] tmp_fu_520_p3;
wire   [11:0] zext_ln1118_49_fu_528_p1;
wire   [11:0] sub_ln1118_15_fu_532_p2;
wire   [10:0] tmp_163_fu_538_p4;
wire   [11:0] tmp_4_fu_552_p3;
wire   [12:0] zext_ln1118_50_fu_559_p1;
wire   [12:0] sub_ln1118_16_fu_563_p2;
wire   [11:0] tmp_164_fu_568_p4;
wire   [12:0] shl_ln1118_14_fu_582_p3;
wire   [13:0] zext_ln1118_51_fu_589_p1;
wire   [13:0] sub_ln1118_17_fu_593_p2;
wire  signed [14:0] sext_ln1118_fu_599_p1;
wire   [14:0] zext_ln1118_46_fu_421_p1;
wire   [14:0] sub_ln1118_18_fu_603_p2;
wire  signed [12:0] sext_ln708_1_fu_578_p1;
wire  signed [12:0] sext_ln1118_21_fu_548_p1;
wire   [13:0] shl_ln1118_15_fu_630_p3;
wire   [11:0] shl_ln1118_16_fu_642_p3;
wire   [14:0] zext_ln1118_52_fu_638_p1;
wire   [14:0] zext_ln1118_54_fu_654_p1;
wire   [14:0] sub_ln1118_19_fu_658_p2;
wire   [9:0] shl_ln1118_17_fu_674_p3;
wire   [12:0] zext_ln1118_56_fu_681_p1;
wire   [12:0] sub_ln1118_20_fu_685_p2;
wire   [12:0] sub_ln1118_21_fu_701_p2;
wire   [11:0] tmp_168_fu_706_p4;
wire   [9:0] add_ln703_49_fu_720_p2;
wire  signed [12:0] sext_ln703_34_fu_716_p1;
wire  signed [12:0] sext_ln703_35_fu_725_p1;
wire   [12:0] zext_ln1118_53_fu_650_p1;
wire   [12:0] sub_ln1118_22_fu_735_p2;
wire   [13:0] sub_ln1118_23_fu_751_p2;
wire   [8:0] shl_ln1118_18_fu_761_p3;
wire  signed [14:0] sext_ln1118_1_fu_757_p1;
wire   [14:0] zext_ln1118_58_fu_772_p1;
wire   [14:0] sub_ln1118_24_fu_776_p2;
wire   [11:0] shl_ln1118_19_fu_792_p3;
wire   [12:0] zext_ln1118_59_fu_799_p1;
wire   [12:0] zext_ln1118_45_fu_418_p1;
wire   [12:0] sub_ln1118_25_fu_803_p2;
wire   [11:0] tmp_171_fu_809_p4;
wire   [11:0] add_ln703_53_fu_823_p2;
wire  signed [13:0] sext_ln703_37_fu_819_p1;
wire   [13:0] zext_ln703_18_fu_828_p1;
wire   [8:0] shl_ln1118_20_fu_838_p3;
wire   [9:0] zext_ln1118_60_fu_846_p1;
wire   [9:0] sub_ln1118_26_fu_850_p2;
wire   [8:0] tmp_172_fu_856_p4;
wire   [13:0] zext_ln1118_57_fu_768_p1;
wire   [13:0] add_ln1118_6_fu_870_p2;
wire   [12:0] tmp_173_fu_876_p4;
wire   [7:0] mul_ln708_6_fu_893_p0;
wire   [13:0] mul_ln708_6_fu_893_p2;
wire   [14:0] zext_ln708_7_fu_886_p1;
wire  signed [14:0] sext_ln1118_25_fu_866_p1;
wire   [8:0] zext_ln1118_40_fu_317_p1;
wire    ap_CS_fsm_state3;
wire   [13:0] zext_ln1118_55_fu_921_p1;
wire  signed [13:0] sext_ln1118_16_fu_924_p1;
wire   [13:0] add_ln703_fu_927_p2;
wire  signed [14:0] sext_ln703_25_fu_933_p1;
wire   [14:0] zext_ln703_15_fu_937_p1;
wire  signed [13:0] sext_ln1118_17_fu_946_p1;
wire  signed [13:0] sext_ln1118_18_fu_949_p1;
wire   [13:0] add_ln703_33_fu_961_p2;
wire  signed [12:0] sext_ln703_27_fu_958_p1;
wire  signed [12:0] sext_ln1118_19_fu_952_p1;
wire   [12:0] add_ln703_34_fu_971_p2;
wire  signed [14:0] sext_ln703_28_fu_967_p1;
wire  signed [14:0] sext_ln703_29_fu_977_p1;
wire   [13:0] zext_ln708_fu_987_p1;
wire  signed [13:0] sext_ln703_26_fu_955_p1;
wire   [13:0] add_ln703_36_fu_990_p2;
wire  signed [13:0] sext_ln703_30_fu_996_p1;
wire  signed [13:0] sext_ln1118_20_fu_1008_p1;
wire  signed [13:0] sext_ln708_fu_1005_p1;
wire   [13:0] add_ln703_40_fu_1011_p2;
wire  signed [14:0] sext_ln703_31_fu_1017_p1;
wire   [14:0] zext_ln703_16_fu_1021_p1;
wire  signed [14:0] sext_ln703_32_fu_1030_p1;
wire   [14:0] zext_ln703_17_fu_1036_p1;
wire  signed [14:0] sext_ln703_33_fu_1033_p1;
wire   [14:0] add_ln703_46_fu_1039_p2;
wire  signed [14:0] sext_ln1118_23_fu_1054_p1;
wire  signed [14:0] sext_ln1118_22_fu_1051_p1;
wire   [14:0] add_ln703_48_fu_1057_p2;
wire  signed [14:0] sext_ln703_36_fu_1063_p1;
wire  signed [14:0] sext_ln708_2_fu_1075_p1;
wire  signed [14:0] sext_ln1118_24_fu_1072_p1;
wire   [14:0] add_ln703_52_fu_1078_p2;
wire  signed [14:0] sext_ln703_38_fu_1084_p1;
wire   [13:0] zext_ln708_9_fu_1093_p1;
wire  signed [13:0] sext_ln703_4_fu_1099_p1;
wire   [13:0] add_ln703_58_fu_1102_p2;
wire  signed [15:0] sext_ln703_39_fu_1096_p1;
wire  signed [15:0] sext_ln703_5_fu_1108_p1;
wire   [14:0] p_Val2_s_fu_940_p2;
wire   [15:0] tmp_174_fu_1118_p3;
wire   [14:0] acc_1_V_fu_981_p2;
wire   [15:0] tmp_175_fu_1130_p3;
wire   [13:0] acc_2_V_fu_999_p2;
wire   [14:0] tmp_176_fu_1142_p3;
wire   [14:0] acc_3_V_fu_1024_p2;
wire   [15:0] tmp_177_fu_1154_p3;
wire   [14:0] acc_4_V_fu_1045_p2;
wire   [15:0] tmp_178_fu_1166_p3;
wire   [14:0] acc_5_V_fu_1066_p2;
wire   [15:0] tmp_179_fu_1178_p3;
wire   [14:0] acc_6_V_fu_1087_p2;
wire   [15:0] tmp_180_fu_1190_p3;
wire   [15:0] acc_7_V_fu_1112_p2;
wire  signed [16:0] sext_ln728_fu_1126_p1;
wire  signed [16:0] sext_ln728_4_fu_1138_p1;
wire  signed [16:0] sext_ln728_5_fu_1150_p1;
wire  signed [16:0] sext_ln728_6_fu_1162_p1;
wire  signed [16:0] sext_ln728_7_fu_1174_p1;
wire  signed [16:0] sext_ln728_8_fu_1186_p1;
wire  signed [16:0] sext_ln728_9_fu_1198_p1;
wire   [16:0] res_7_V_write_assign_fu_1202_p3;
reg   [2:0] ap_NS_fsm;
wire   [13:0] mul_ln1118_3_fu_386_p00;
wire   [13:0] mul_ln1118_4_fu_470_p00;
wire   [13:0] mul_ln1118_5_fu_486_p00;
wire   [12:0] mul_ln708_3_fu_184_p00;
wire   [13:0] mul_ln708_6_fu_893_p00;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln703_31_reg_1343 <= add_ln703_31_fu_364_p2;
        add_ln703_38_reg_1368 <= add_ln703_38_fu_464_p2;
        add_ln703_42_reg_1383 <= add_ln703_42_fu_514_p2;
        add_ln703_44_reg_1393 <= add_ln703_44_fu_619_p2;
        add_ln703_45_reg_1398 <= add_ln703_45_fu_625_p2;
        add_ln703_50_reg_1413 <= add_ln703_50_fu_729_p2;
        add_ln703_54_reg_1428 <= add_ln703_54_fu_832_p2;
        add_ln703_56_reg_1438 <= add_ln703_56_fu_909_p2;
        add_ln703_57_reg_1443 <= add_ln703_57_fu_915_p2;
        lshr_ln708_8_reg_1433 <= {{mul_ln708_6_fu_893_p2[13:1]}};
        tmp_154_reg_1333 <= {{mul_ln708_fu_260_p2[11:1]}};
        tmp_155_reg_1338 <= {{sub_ln1118_fu_301_p2[13:1]}};
        tmp_156_reg_1348 <= {{mul_ln1118_fu_370_p2[12:1]}};
        tmp_157_reg_1353 <= {{mul_ln1118_3_fu_386_p2[13:1]}};
        tmp_158_reg_1358 <= {{sub_ln1118_13_fu_402_p2[12:1]}};
        tmp_160_reg_1363 <= {{mul_ln708_2_fu_424_p2[12:1]}};
        tmp_161_reg_1373 <= {{mul_ln1118_4_fu_470_p2[13:1]}};
        tmp_162_reg_1378 <= {{mul_ln1118_5_fu_486_p2[13:1]}};
        tmp_165_reg_1388 <= {{sub_ln1118_18_fu_603_p2[14:1]}};
        tmp_166_reg_1403 <= {{sub_ln1118_19_fu_658_p2[14:1]}};
        tmp_167_reg_1408 <= {{sub_ln1118_20_fu_685_p2[12:1]}};
        tmp_169_reg_1418 <= {{sub_ln1118_22_fu_735_p2[12:1]}};
        tmp_170_reg_1423 <= {{sub_ln1118_24_fu_776_p2[14:1]}};
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        lshr_ln708_5_reg_1307 <= {{p_read1[7:1]}};
        lshr_ln708_6_reg_1317 <= {{add_ln1118_5_fu_200_p2[10:1]}};
        shl_ln1118_13_reg_1295[9 : 2] <= shl_ln1118_13_fu_146_p3[9 : 2];
        tmp_159_reg_1301 <= {{sub_ln1118_14_fu_158_p2[10:1]}};
        trunc_ln1118_6_reg_1323 <= {{mul_ln708_4_fu_216_p2[12:1]}};
        trunc_ln1118_7_reg_1328 <= {{mul_ln708_5_fu_232_p2[12:1]}};
        trunc_ln1_reg_1312 <= {{mul_ln708_3_fu_184_p2[12:1]}};
        zext_ln1118_37_reg_1285[7 : 0] <= zext_ln1118_37_fu_134_p1[7 : 0];
        zext_ln1118_42_reg_1290[7 : 0] <= zext_ln1118_42_fu_138_p1[7 : 0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_1_V_fu_981_p2 = ($signed(sext_ln703_28_fu_967_p1) + $signed(sext_ln703_29_fu_977_p1));

assign acc_2_V_fu_999_p2 = ($signed(add_ln703_36_fu_990_p2) + $signed(sext_ln703_30_fu_996_p1));

assign acc_3_V_fu_1024_p2 = ($signed(sext_ln703_31_fu_1017_p1) + $signed(zext_ln703_16_fu_1021_p1));

assign acc_4_V_fu_1045_p2 = ($signed(sext_ln703_33_fu_1033_p1) + $signed(add_ln703_46_fu_1039_p2));

assign acc_5_V_fu_1066_p2 = ($signed(add_ln703_48_fu_1057_p2) + $signed(sext_ln703_36_fu_1063_p1));

assign acc_6_V_fu_1087_p2 = ($signed(add_ln703_52_fu_1078_p2) + $signed(sext_ln703_38_fu_1084_p1));

assign acc_7_V_fu_1112_p2 = ($signed(sext_ln703_39_fu_1096_p1) + $signed(sext_ln703_5_fu_1108_p1));

assign add_ln1118_5_fu_200_p2 = (zext_ln703_fu_142_p1 + zext_ln1118_47_fu_154_p1);

assign add_ln1118_6_fu_870_p2 = (zext_ln1118_38_fu_286_p1 + zext_ln1118_57_fu_768_p1);

assign add_ln1118_fu_345_p2 = (zext_ln1118_43_fu_330_p1 + zext_ln1118_44_fu_341_p1);

assign add_ln703_31_fu_364_p2 = (zext_ln703_10_fu_361_p1 + trunc_ln_fu_351_p4);

assign add_ln703_33_fu_961_p2 = ($signed(sext_ln1118_17_fu_946_p1) + $signed(sext_ln1118_18_fu_949_p1));

assign add_ln703_34_fu_971_p2 = ($signed(sext_ln703_27_fu_958_p1) + $signed(sext_ln1118_19_fu_952_p1));

assign add_ln703_36_fu_990_p2 = ($signed(zext_ln708_fu_987_p1) + $signed(sext_ln703_26_fu_955_p1));

assign add_ln703_37_fu_454_p2 = ($signed(zext_ln703_12_fu_450_p1) + $signed(12'd4032));

assign add_ln703_38_fu_464_p2 = ($signed(zext_ln1118_48_fu_440_p1) + $signed(sext_ln703_fu_460_p1));

assign add_ln703_40_fu_1011_p2 = ($signed(sext_ln1118_20_fu_1008_p1) + $signed(sext_ln708_fu_1005_p1));

assign add_ln703_41_fu_505_p2 = (trunc_ln1_reg_1312 + 12'd384);

assign add_ln703_42_fu_514_p2 = (zext_ln703_13_fu_502_p1 + zext_ln703_14_fu_510_p1);

assign add_ln703_44_fu_619_p2 = ($signed(sext_ln708_1_fu_578_p1) + $signed(sext_ln1118_21_fu_548_p1));

assign add_ln703_45_fu_625_p2 = (trunc_ln1118_6_reg_1323 + 12'd448);

assign add_ln703_46_fu_1039_p2 = ($signed(sext_ln703_32_fu_1030_p1) + $signed(zext_ln703_17_fu_1036_p1));

assign add_ln703_48_fu_1057_p2 = ($signed(sext_ln1118_23_fu_1054_p1) + $signed(sext_ln1118_22_fu_1051_p1));

assign add_ln703_49_fu_720_p2 = ($signed(lshr_ln708_6_reg_1317) + $signed(10'd704));

assign add_ln703_50_fu_729_p2 = ($signed(sext_ln703_34_fu_716_p1) + $signed(sext_ln703_35_fu_725_p1));

assign add_ln703_52_fu_1078_p2 = ($signed(sext_ln708_2_fu_1075_p1) + $signed(sext_ln1118_24_fu_1072_p1));

assign add_ln703_53_fu_823_p2 = (trunc_ln1118_7_reg_1328 + 12'd224);

assign add_ln703_54_fu_832_p2 = ($signed(sext_ln703_37_fu_819_p1) + $signed(zext_ln703_18_fu_828_p1));

assign add_ln703_56_fu_909_p2 = ($signed(zext_ln708_7_fu_886_p1) + $signed(sext_ln1118_25_fu_866_p1));

assign add_ln703_57_fu_915_p2 = ($signed(zext_ln1118_40_fu_317_p1) + $signed(9'd320));

assign add_ln703_58_fu_1102_p2 = ($signed(zext_ln708_9_fu_1093_p1) + $signed(sext_ln703_4_fu_1099_p1));

assign add_ln703_fu_927_p2 = ($signed(zext_ln1118_55_fu_921_p1) + $signed(sext_ln1118_16_fu_924_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_return_0 = sext_ln728_fu_1126_p1;

assign ap_return_1 = sext_ln728_4_fu_1138_p1;

assign ap_return_2 = sext_ln728_5_fu_1150_p1;

assign ap_return_3 = sext_ln728_6_fu_1162_p1;

assign ap_return_4 = sext_ln728_7_fu_1174_p1;

assign ap_return_5 = sext_ln728_8_fu_1186_p1;

assign ap_return_6 = sext_ln728_9_fu_1198_p1;

assign ap_return_7 = res_7_V_write_assign_fu_1202_p3;

assign mul_ln1118_3_fu_386_p0 = mul_ln1118_3_fu_386_p00;

assign mul_ln1118_3_fu_386_p00 = p_read1;

assign mul_ln1118_3_fu_386_p2 = ($signed({{1'b0}, {mul_ln1118_3_fu_386_p0}}) * $signed(-'h1B));

assign mul_ln1118_4_fu_470_p0 = mul_ln1118_4_fu_470_p00;

assign mul_ln1118_4_fu_470_p00 = p_read;

assign mul_ln1118_4_fu_470_p2 = ($signed({{1'b0}, {mul_ln1118_4_fu_470_p0}}) * $signed(-'h16));

assign mul_ln1118_5_fu_486_p0 = mul_ln1118_5_fu_486_p00;

assign mul_ln1118_5_fu_486_p00 = p_read2;

assign mul_ln1118_5_fu_486_p2 = ($signed({{1'b0}, {mul_ln1118_5_fu_486_p0}}) * $signed(-'h1B));

assign mul_ln1118_fu_370_p0 = zext_ln1118_fu_248_p1;

assign mul_ln1118_fu_370_p2 = ($signed({{1'b0}, {mul_ln1118_fu_370_p0}}) * $signed(-'hB));

assign mul_ln708_2_fu_424_p0 = zext_ln1118_fu_248_p1;

assign mul_ln708_2_fu_424_p2 = (mul_ln708_2_fu_424_p0 * $signed('h1A));

assign mul_ln708_3_fu_184_p0 = mul_ln708_3_fu_184_p00;

assign mul_ln708_3_fu_184_p00 = p_read1;

assign mul_ln708_3_fu_184_p2 = (mul_ln708_3_fu_184_p0 * $signed('h1D));

assign mul_ln708_4_fu_216_p0 = zext_ln1118_42_fu_138_p1;

assign mul_ln708_4_fu_216_p2 = (mul_ln708_4_fu_216_p0 * $signed('h17));

assign mul_ln708_5_fu_232_p0 = zext_ln1118_42_fu_138_p1;

assign mul_ln708_5_fu_232_p2 = (mul_ln708_5_fu_232_p0 * $signed('h16));

assign mul_ln708_6_fu_893_p0 = mul_ln708_6_fu_893_p00;

assign mul_ln708_6_fu_893_p00 = p_read3;

assign mul_ln708_6_fu_893_p2 = (mul_ln708_6_fu_893_p0 * $signed('h26));

assign mul_ln708_fu_260_p0 = zext_ln1118_34_fu_252_p1;

assign mul_ln708_fu_260_p2 = (mul_ln708_fu_260_p0 * $signed('hD));

assign p_Val2_s_fu_940_p2 = ($signed(sext_ln703_25_fu_933_p1) + $signed(zext_ln703_15_fu_937_p1));

assign res_7_V_write_assign_fu_1202_p3 = {{acc_7_V_fu_1112_p2}, {1'd0}};

assign sext_ln1118_16_fu_924_p1 = $signed(tmp_155_reg_1338);

assign sext_ln1118_17_fu_946_p1 = $signed(tmp_156_reg_1348);

assign sext_ln1118_18_fu_949_p1 = $signed(tmp_157_reg_1353);

assign sext_ln1118_19_fu_952_p1 = $signed(tmp_158_reg_1358);

assign sext_ln1118_1_fu_757_p1 = $signed(sub_ln1118_23_fu_751_p2);

assign sext_ln1118_20_fu_1008_p1 = $signed(tmp_162_reg_1378);

assign sext_ln1118_21_fu_548_p1 = $signed(tmp_163_fu_538_p4);

assign sext_ln1118_22_fu_1051_p1 = $signed(tmp_166_reg_1403);

assign sext_ln1118_23_fu_1054_p1 = $signed(tmp_167_reg_1408);

assign sext_ln1118_24_fu_1072_p1 = $signed(tmp_169_reg_1418);

assign sext_ln1118_25_fu_866_p1 = $signed(tmp_172_fu_856_p4);

assign sext_ln1118_fu_599_p1 = $signed(sub_ln1118_17_fu_593_p2);

assign sext_ln703_25_fu_933_p1 = $signed(add_ln703_fu_927_p2);

assign sext_ln703_26_fu_955_p1 = tmp_159_reg_1301;

assign sext_ln703_27_fu_958_p1 = tmp_159_reg_1301;

assign sext_ln703_28_fu_967_p1 = $signed(add_ln703_33_fu_961_p2);

assign sext_ln703_29_fu_977_p1 = $signed(add_ln703_34_fu_971_p2);

assign sext_ln703_30_fu_996_p1 = $signed(add_ln703_38_reg_1368);

assign sext_ln703_31_fu_1017_p1 = $signed(add_ln703_40_fu_1011_p2);

assign sext_ln703_32_fu_1030_p1 = $signed(tmp_165_reg_1388);

assign sext_ln703_33_fu_1033_p1 = $signed(add_ln703_44_reg_1393);

assign sext_ln703_34_fu_716_p1 = $signed(tmp_168_fu_706_p4);

assign sext_ln703_35_fu_725_p1 = $signed(add_ln703_49_fu_720_p2);

assign sext_ln703_36_fu_1063_p1 = $signed(add_ln703_50_reg_1413);

assign sext_ln703_37_fu_819_p1 = $signed(tmp_171_fu_809_p4);

assign sext_ln703_38_fu_1084_p1 = $signed(add_ln703_54_reg_1428);

assign sext_ln703_39_fu_1096_p1 = $signed(add_ln703_56_reg_1438);

assign sext_ln703_4_fu_1099_p1 = $signed(add_ln703_57_reg_1443);

assign sext_ln703_5_fu_1108_p1 = $signed(add_ln703_58_fu_1102_p2);

assign sext_ln703_fu_460_p1 = $signed(add_ln703_37_fu_454_p2);

assign sext_ln708_1_fu_578_p1 = $signed(tmp_164_fu_568_p4);

assign sext_ln708_2_fu_1075_p1 = $signed(tmp_170_reg_1423);

assign sext_ln708_fu_1005_p1 = $signed(tmp_161_reg_1373);

assign sext_ln728_4_fu_1138_p1 = $signed(tmp_175_fu_1130_p3);

assign sext_ln728_5_fu_1150_p1 = $signed(tmp_176_fu_1142_p3);

assign sext_ln728_6_fu_1162_p1 = $signed(tmp_177_fu_1154_p3);

assign sext_ln728_7_fu_1174_p1 = $signed(tmp_178_fu_1166_p3);

assign sext_ln728_8_fu_1186_p1 = $signed(tmp_179_fu_1178_p3);

assign sext_ln728_9_fu_1198_p1 = $signed(tmp_180_fu_1190_p3);

assign sext_ln728_fu_1126_p1 = $signed(tmp_174_fu_1118_p3);

assign shl_ln1118_11_fu_323_p3 = {{p_read2}, {4'd0}};

assign shl_ln1118_12_fu_334_p3 = {{p_read2}, {2'd0}};

assign shl_ln1118_13_fu_146_p3 = {{p_read3}, {2'd0}};

assign shl_ln1118_14_fu_582_p3 = {{p_read3}, {5'd0}};

assign shl_ln1118_15_fu_630_p3 = {{p_read}, {6'd0}};

assign shl_ln1118_16_fu_642_p3 = {{p_read}, {4'd0}};

assign shl_ln1118_17_fu_674_p3 = {{p_read1}, {2'd0}};

assign shl_ln1118_18_fu_761_p3 = {{p_read1}, {1'd0}};

assign shl_ln1118_19_fu_792_p3 = {{p_read3}, {4'd0}};

assign shl_ln1118_20_fu_838_p3 = {{p_read}, {1'd0}};

assign shl_ln1118_s_fu_290_p3 = {{p_read1}, {3'd0}};

assign shl_ln3_fu_443_p3 = {{p_read2}, {3'd0}};

assign shl_ln_fu_279_p3 = {{p_read1}, {5'd0}};

assign sub_ln1118_13_fu_402_p2 = (zext_ln1118_44_fu_341_p1 - zext_ln1118_43_fu_330_p1);

assign sub_ln1118_14_fu_158_p2 = (11'd0 - zext_ln1118_47_fu_154_p1);

assign sub_ln1118_15_fu_532_p2 = (zext_ln1118_34_fu_252_p1 - zext_ln1118_49_fu_528_p1);

assign sub_ln1118_16_fu_563_p2 = (zext_ln1118_37_reg_1285 - zext_ln1118_50_fu_559_p1);

assign sub_ln1118_17_fu_593_p2 = (14'd0 - zext_ln1118_51_fu_589_p1);

assign sub_ln1118_18_fu_603_p2 = ($signed(sext_ln1118_fu_599_p1) - $signed(zext_ln1118_46_fu_421_p1));

assign sub_ln1118_19_fu_658_p2 = (zext_ln1118_52_fu_638_p1 - zext_ln1118_54_fu_654_p1);

assign sub_ln1118_20_fu_685_p2 = (zext_ln1118_50_fu_559_p1 - zext_ln1118_56_fu_681_p1);

assign sub_ln1118_21_fu_701_p2 = (zext_ln1118_43_fu_330_p1 - zext_ln1118_42_reg_1290);

assign sub_ln1118_22_fu_735_p2 = (13'd0 - zext_ln1118_53_fu_650_p1);

assign sub_ln1118_23_fu_751_p2 = (14'd0 - zext_ln1118_38_fu_286_p1);

assign sub_ln1118_24_fu_776_p2 = ($signed(sext_ln1118_1_fu_757_p1) - $signed(zext_ln1118_58_fu_772_p1));

assign sub_ln1118_25_fu_803_p2 = (zext_ln1118_59_fu_799_p1 - zext_ln1118_45_fu_418_p1);

assign sub_ln1118_26_fu_850_p2 = (10'd0 - zext_ln1118_60_fu_846_p1);

assign sub_ln1118_fu_301_p2 = (zext_ln1118_39_fu_297_p1 - zext_ln1118_38_fu_286_p1);

assign tmp_163_fu_538_p4 = {{sub_ln1118_15_fu_532_p2[11:1]}};

assign tmp_164_fu_568_p4 = {{sub_ln1118_16_fu_563_p2[12:1]}};

assign tmp_168_fu_706_p4 = {{sub_ln1118_21_fu_701_p2[12:1]}};

assign tmp_171_fu_809_p4 = {{sub_ln1118_25_fu_803_p2[12:1]}};

assign tmp_172_fu_856_p4 = {{sub_ln1118_26_fu_850_p2[9:1]}};

assign tmp_173_fu_876_p4 = {{add_ln1118_6_fu_870_p2[13:1]}};

assign tmp_174_fu_1118_p3 = {{p_Val2_s_fu_940_p2}, {1'd0}};

assign tmp_175_fu_1130_p3 = {{acc_1_V_fu_981_p2}, {1'd0}};

assign tmp_176_fu_1142_p3 = {{acc_2_V_fu_999_p2}, {1'd0}};

assign tmp_177_fu_1154_p3 = {{acc_3_V_fu_1024_p2}, {1'd0}};

assign tmp_178_fu_1166_p3 = {{acc_4_V_fu_1045_p2}, {1'd0}};

assign tmp_179_fu_1178_p3 = {{acc_5_V_fu_1066_p2}, {1'd0}};

assign tmp_180_fu_1190_p3 = {{acc_6_V_fu_1087_p2}, {1'd0}};

assign tmp_4_fu_552_p3 = {{p_read1}, {4'd0}};

assign tmp_fu_520_p3 = {{p_read}, {3'd0}};

assign trunc_ln_fu_351_p4 = {{add_ln1118_fu_345_p2[12:1]}};

assign zext_ln1118_34_fu_252_p1 = p_read;

assign zext_ln1118_37_fu_134_p1 = p_read1;

assign zext_ln1118_38_fu_286_p1 = shl_ln_fu_279_p3;

assign zext_ln1118_39_fu_297_p1 = shl_ln1118_s_fu_290_p3;

assign zext_ln1118_40_fu_317_p1 = p_read2;

assign zext_ln1118_42_fu_138_p1 = p_read2;

assign zext_ln1118_43_fu_330_p1 = shl_ln1118_11_fu_323_p3;

assign zext_ln1118_44_fu_341_p1 = shl_ln1118_12_fu_334_p3;

assign zext_ln1118_45_fu_418_p1 = shl_ln1118_13_reg_1295;

assign zext_ln1118_46_fu_421_p1 = shl_ln1118_13_reg_1295;

assign zext_ln1118_47_fu_154_p1 = shl_ln1118_13_fu_146_p3;

assign zext_ln1118_48_fu_440_p1 = lshr_ln708_5_reg_1307;

assign zext_ln1118_49_fu_528_p1 = tmp_fu_520_p3;

assign zext_ln1118_50_fu_559_p1 = tmp_4_fu_552_p3;

assign zext_ln1118_51_fu_589_p1 = shl_ln1118_14_fu_582_p3;

assign zext_ln1118_52_fu_638_p1 = shl_ln1118_15_fu_630_p3;

assign zext_ln1118_53_fu_650_p1 = shl_ln1118_16_fu_642_p3;

assign zext_ln1118_54_fu_654_p1 = shl_ln1118_16_fu_642_p3;

assign zext_ln1118_55_fu_921_p1 = tmp_154_reg_1333;

assign zext_ln1118_56_fu_681_p1 = shl_ln1118_17_fu_674_p3;

assign zext_ln1118_57_fu_768_p1 = shl_ln1118_18_fu_761_p3;

assign zext_ln1118_58_fu_772_p1 = shl_ln1118_18_fu_761_p3;

assign zext_ln1118_59_fu_799_p1 = shl_ln1118_19_fu_792_p3;

assign zext_ln1118_60_fu_846_p1 = shl_ln1118_20_fu_838_p3;

assign zext_ln1118_fu_248_p1 = p_read;

assign zext_ln703_10_fu_361_p1 = p_read3;

assign zext_ln703_12_fu_450_p1 = shl_ln3_fu_443_p3;

assign zext_ln703_13_fu_502_p1 = lshr_ln708_6_reg_1317;

assign zext_ln703_14_fu_510_p1 = add_ln703_41_fu_505_p2;

assign zext_ln703_15_fu_937_p1 = add_ln703_31_reg_1343;

assign zext_ln703_16_fu_1021_p1 = add_ln703_42_reg_1383;

assign zext_ln703_17_fu_1036_p1 = add_ln703_45_reg_1398;

assign zext_ln703_18_fu_828_p1 = add_ln703_53_fu_823_p2;

assign zext_ln703_fu_142_p1 = p_read3;

assign zext_ln708_7_fu_886_p1 = tmp_173_fu_876_p4;

assign zext_ln708_9_fu_1093_p1 = lshr_ln708_8_reg_1433;

assign zext_ln708_fu_987_p1 = tmp_160_reg_1363;

always @ (posedge ap_clk) begin
    zext_ln1118_37_reg_1285[12:8] <= 5'b00000;
    zext_ln1118_42_reg_1290[12:8] <= 5'b00000;
    shl_ln1118_13_reg_1295[1:0] <= 2'b00;
end

endmodule //dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0
