// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_config2_0_0_0_0_0_0_0_0_0 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        data_V_ap_vld,
        data_V,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   data_V_ap_vld;
input  [223:0] data_V;
output  [20:0] ap_return_0;
output  [20:0] ap_return_1;
output  [20:0] ap_return_2;
output  [20:0] ap_return_3;
output  [20:0] ap_return_4;
output  [20:0] ap_return_5;
output  [20:0] ap_return_6;
output  [20:0] ap_return_7;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[20:0] ap_return_0;
reg[20:0] ap_return_1;
reg[20:0] ap_return_2;
reg[20:0] ap_return_3;
reg[20:0] ap_return_4;
reg[20:0] ap_return_5;
reg[20:0] ap_return_6;
reg[20:0] ap_return_7;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln135_fu_481_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_state6_pp0_stage0_iter4;
wire    ap_block_state7_pp0_stage0_iter5;
wire    ap_block_state8_pp0_stage0_iter6;
wire    ap_block_state9_pp0_stage0_iter7;
wire    ap_block_state10_pp0_stage0_iter8;
wire    ap_block_state11_pp0_stage0_iter9;
wire    ap_block_state12_pp0_stage0_iter10;
wire    ap_block_state13_pp0_stage0_iter11;
wire    ap_block_state14_pp0_stage0_iter12;
wire    ap_block_state15_pp0_stage0_iter13;
reg    ap_block_pp0_stage0_11001;
wire   [5:0] outidx5_address0;
reg    outidx5_ce0;
wire   [1:0] outidx5_q0;
wire   [5:0] w2_V_address0;
reg    w2_V_ce0;
wire   [13:0] w2_V_q0;
reg    data_V_blk_n;
wire    ap_block_pp0_stage0;
reg   [5:0] w_index26_reg_148;
reg   [5:0] w_index26_reg_148_pp0_iter1_reg;
reg   [5:0] w_index26_reg_148_pp0_iter2_reg;
reg   [5:0] w_index26_reg_148_pp0_iter3_reg;
reg   [5:0] w_index26_reg_148_pp0_iter4_reg;
reg   [5:0] w_index26_reg_148_pp0_iter5_reg;
reg   [5:0] w_index26_reg_148_pp0_iter6_reg;
reg   [31:0] in_index_025_reg_163;
reg   [15:0] p_Val2_24_reg_178;
reg   [15:0] p_Val2_1422_reg_193;
reg   [15:0] p_Val2_1520_reg_208;
reg   [15:0] p_Val2_1618_reg_223;
reg   [15:0] p_Val2_1716_reg_253;
reg   [15:0] p_Val2_1814_reg_267;
reg   [15:0] p_Val2_1912_reg_281;
reg   [15:0] p_Val2_2010_reg_295;
reg   [223:0] data_V_read_reg_837;
reg   [223:0] tmp_127_fu_453_p4;
reg   [223:0] tmp_127_reg_842;
wire   [5:0] w_index_fu_463_p2;
reg   [5:0] w_index_reg_847;
wire   [31:0] in_index_fu_469_p2;
reg   [31:0] in_index_reg_852;
wire   [0:0] icmp_ln154_fu_475_p2;
reg   [0:0] icmp_ln154_reg_857;
reg   [0:0] icmp_ln135_reg_862;
reg   [0:0] icmp_ln135_reg_862_pp0_iter1_reg;
reg   [0:0] icmp_ln135_reg_862_pp0_iter2_reg;
reg   [0:0] icmp_ln135_reg_862_pp0_iter3_reg;
reg   [0:0] icmp_ln135_reg_862_pp0_iter4_reg;
reg   [0:0] icmp_ln135_reg_862_pp0_iter5_reg;
reg   [0:0] icmp_ln135_reg_862_pp0_iter6_reg;
reg   [0:0] icmp_ln135_reg_862_pp0_iter7_reg;
reg   [0:0] icmp_ln135_reg_862_pp0_iter8_reg;
reg   [0:0] icmp_ln135_reg_862_pp0_iter9_reg;
reg   [0:0] icmp_ln135_reg_862_pp0_iter10_reg;
reg   [0:0] icmp_ln135_reg_862_pp0_iter11_reg;
reg   [0:0] icmp_ln135_reg_862_pp0_iter12_reg;
wire   [223:0] select_ln145_1_fu_553_p3;
reg   [223:0] select_ln145_1_reg_866;
wire   [7:0] select_ln145_2_fu_559_p3;
reg   [7:0] select_ln145_2_reg_871;
wire   [7:0] sub_ln145_3_fu_567_p2;
reg   [7:0] sub_ln145_3_reg_876;
reg   [7:0] sub_ln145_3_reg_876_pp0_iter2_reg;
reg   [7:0] sub_ln145_3_reg_876_pp0_iter3_reg;
reg   [7:0] sub_ln145_3_reg_876_pp0_iter4_reg;
reg   [7:0] sub_ln145_3_reg_876_pp0_iter5_reg;
reg   [7:0] sub_ln145_3_reg_876_pp0_iter6_reg;
reg   [7:0] sub_ln145_3_reg_876_pp0_iter7_reg;
wire   [31:0] select_ln154_fu_573_p3;
reg    ap_enable_reg_pp0_iter1;
wire   [223:0] grp_fu_582_p2;
reg   [223:0] lshr_ln145_reg_896;
reg   [1:0] out_index_reg_906;
reg   [1:0] out_index_reg_906_pp0_iter9_reg;
reg   [1:0] out_index_reg_906_pp0_iter10_reg;
reg   [1:0] out_index_reg_906_pp0_iter11_reg;
reg   [1:0] out_index_reg_906_pp0_iter12_reg;
wire   [15:0] trunc_ln145_1_fu_607_p1;
reg   [15:0] trunc_ln145_1_reg_912;
wire   [7:0] trunc_ln145_2_fu_611_p1;
reg  signed [7:0] trunc_ln145_2_reg_917;
reg  signed [5:0] tmp_40_reg_922;
wire  signed [20:0] sext_ln1116_cast_fu_625_p1;
wire  signed [20:0] grp_fu_825_p2;
reg  signed [20:0] mul_ln1118_reg_943;
wire  signed [20:0] grp_fu_831_p2;
reg  signed [20:0] mul_ln1118_1_reg_948;
wire   [15:0] acc_0_V_fu_656_p2;
reg   [15:0] acc_0_V_reg_953;
reg   [15:0] trunc_ln708_s_reg_961;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg   [5:0] ap_phi_mux_w_index26_phi_fu_152_p6;
reg   [31:0] ap_phi_mux_in_index_025_phi_fu_167_p6;
reg   [15:0] ap_phi_mux_p_Val2_24_phi_fu_182_p6;
reg   [15:0] ap_phi_mux_p_Val2_s_phi_fu_367_p8;
reg   [15:0] ap_phi_mux_p_Val2_1422_phi_fu_197_p6;
reg   [15:0] ap_phi_mux_p_Val2_16_phi_fu_349_p8;
reg   [15:0] ap_phi_mux_p_Val2_1520_phi_fu_212_p6;
reg   [15:0] ap_phi_mux_p_Val2_17_phi_fu_331_p8;
reg   [15:0] ap_phi_mux_p_Val2_1618_phi_fu_227_p6;
reg   [15:0] ap_phi_mux_p_Val2_18_phi_fu_313_p8;
reg   [15:0] ap_phi_mux_p_Val2_19_phi_fu_439_p8;
reg   [15:0] ap_phi_mux_p_Val2_20_phi_fu_421_p8;
reg   [15:0] ap_phi_mux_p_Val2_21_phi_fu_403_p8;
reg   [15:0] ap_phi_mux_p_Val2_22_phi_fu_385_p8;
wire   [15:0] ap_phi_reg_pp0_iter13_p_Val2_18_reg_309;
wire   [15:0] ap_phi_reg_pp0_iter13_p_Val2_17_reg_327;
wire   [15:0] ap_phi_reg_pp0_iter13_p_Val2_16_reg_345;
wire   [15:0] ap_phi_reg_pp0_iter13_p_Val2_s_reg_363;
wire   [15:0] acc_4_V_fu_700_p2;
wire   [15:0] ap_phi_reg_pp0_iter13_p_Val2_22_reg_381;
wire   [2:0] or_ln_fu_671_p3;
wire   [15:0] ap_phi_reg_pp0_iter13_p_Val2_21_reg_399;
wire   [15:0] ap_phi_reg_pp0_iter13_p_Val2_20_reg_417;
wire   [15:0] ap_phi_reg_pp0_iter13_p_Val2_19_reg_435;
wire   [63:0] zext_ln139_fu_587_p1;
wire   [4:0] empty_fu_487_p1;
wire   [8:0] tmp_2_fu_495_p3;
wire   [8:0] empty_25_fu_503_p2;
wire   [3:0] empty_24_fu_491_p1;
wire   [7:0] tmp_126_fu_515_p3;
wire   [7:0] trunc_ln145_fu_523_p1;
wire   [0:0] icmp_ln145_fu_509_p2;
wire   [7:0] sub_ln145_fu_527_p2;
wire   [7:0] sub_ln145_2_fu_539_p2;
wire   [7:0] sub_ln145_1_fu_533_p2;
wire   [7:0] select_ln145_fu_545_p3;
wire   [223:0] grp_fu_582_p1;
wire   [223:0] zext_ln145_1_fu_593_p1;
wire   [223:0] lshr_ln145_1_fu_596_p2;
wire   [223:0] and_ln145_fu_602_p2;
wire   [15:0] phi_ln_fu_643_p6;
wire   [15:0] trunc_ln_fu_634_p4;
wire   [2:0] phi_ln1265_2_fu_678_p9;
wire   [15:0] phi_ln1265_2_fu_678_p10;
wire   [20:0] res_0_V_write_assign_fu_709_p3;
wire   [20:0] res_1_V_write_assign_fu_717_p3;
wire   [20:0] res_2_V_write_assign_fu_725_p3;
wire   [20:0] res_3_V_write_assign_fu_733_p3;
wire   [20:0] res_4_V_write_assign_fu_741_p3;
wire   [20:0] res_5_V_write_assign_fu_749_p3;
wire   [20:0] res_6_V_write_assign_fu_757_p3;
wire   [20:0] res_7_V_write_assign_fu_765_p3;
wire  signed [15:0] grp_fu_825_p1;
wire  signed [15:0] grp_fu_831_p0;
reg    grp_fu_582_ce;
reg    grp_fu_825_ce;
reg    grp_fu_831_ce;
reg   [20:0] ap_return_0_preg;
reg   [20:0] ap_return_1_preg;
reg   [20:0] ap_return_2_preg;
reg   [20:0] ap_return_3_preg;
reg   [20:0] ap_return_4_preg;
reg   [20:0] ap_return_5_preg;
reg   [20:0] ap_return_6_preg;
reg   [20:0] ap_return_7_preg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to12;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_247;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_return_0_preg = 21'd0;
#0 ap_return_1_preg = 21'd0;
#0 ap_return_2_preg = 21'd0;
#0 ap_return_3_preg = 21'd0;
#0 ap_return_4_preg = 21'd0;
#0 ap_return_5_preg = 21'd0;
#0 ap_return_6_preg = 21'd0;
#0 ap_return_7_preg = 21'd0;
end

dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_config2_0_0_0_0_0_0_0_0_0_outbkb #(
    .DataWidth( 2 ),
    .AddressRange( 56 ),
    .AddressWidth( 6 ))
outidx5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(outidx5_address0),
    .ce0(outidx5_ce0),
    .q0(outidx5_q0)
);

dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_config2_0_0_0_0_0_0_0_0_0_w2_V #(
    .DataWidth( 14 ),
    .AddressRange( 56 ),
    .AddressWidth( 6 ))
w2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_V_address0),
    .ce0(w2_V_ce0),
    .q0(w2_V_q0)
);

myproject_lshr_224ns_8ns_224_6_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .OP( 1 ),
    .din0_WIDTH( 224 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 224 ))
myproject_lshr_224ns_8ns_224_6_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln145_1_reg_866),
    .din1(grp_fu_582_p1),
    .ce(grp_fu_582_ce),
    .dout(grp_fu_582_p2)
);

myproject_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
myproject_mux_42_16_1_1_U2(
    .din0(ap_phi_mux_p_Val2_24_phi_fu_182_p6),
    .din1(ap_phi_mux_p_Val2_1422_phi_fu_197_p6),
    .din2(ap_phi_mux_p_Val2_1520_phi_fu_212_p6),
    .din3(ap_phi_mux_p_Val2_1618_phi_fu_227_p6),
    .din4(out_index_reg_906_pp0_iter11_reg),
    .dout(phi_ln_fu_643_p6)
);

myproject_mux_83_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
myproject_mux_83_16_1_1_U3(
    .din0(p_Val2_2010_reg_295),
    .din1(p_Val2_2010_reg_295),
    .din2(p_Val2_2010_reg_295),
    .din3(p_Val2_2010_reg_295),
    .din4(p_Val2_1716_reg_253),
    .din5(p_Val2_1814_reg_267),
    .din6(p_Val2_1912_reg_281),
    .din7(p_Val2_2010_reg_295),
    .din8(phi_ln1265_2_fu_678_p9),
    .dout(phi_ln1265_2_fu_678_p10)
);

myproject_mul_mul_8s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_mul_mul_8s_16s_21_3_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln145_2_reg_917),
    .din1(grp_fu_825_p1),
    .ce(grp_fu_825_ce),
    .dout(grp_fu_825_p2)
);

myproject_mul_mul_16s_6s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 21 ))
myproject_mul_mul_16s_6s_21_3_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_831_p0),
    .din1(tmp_40_reg_922),
    .ce(grp_fu_831_ce),
    .dout(grp_fu_831_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter13 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_0_preg[5] <= 1'b0;
        ap_return_0_preg[6] <= 1'b0;
        ap_return_0_preg[7] <= 1'b0;
        ap_return_0_preg[8] <= 1'b0;
        ap_return_0_preg[9] <= 1'b0;
        ap_return_0_preg[10] <= 1'b0;
        ap_return_0_preg[11] <= 1'b0;
        ap_return_0_preg[12] <= 1'b0;
        ap_return_0_preg[13] <= 1'b0;
        ap_return_0_preg[14] <= 1'b0;
        ap_return_0_preg[15] <= 1'b0;
        ap_return_0_preg[16] <= 1'b0;
        ap_return_0_preg[17] <= 1'b0;
        ap_return_0_preg[18] <= 1'b0;
        ap_return_0_preg[19] <= 1'b0;
        ap_return_0_preg[20] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
                        ap_return_0_preg[20 : 5] <= res_0_V_write_assign_fu_709_p3[20 : 5];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_1_preg[5] <= 1'b0;
        ap_return_1_preg[6] <= 1'b0;
        ap_return_1_preg[7] <= 1'b0;
        ap_return_1_preg[8] <= 1'b0;
        ap_return_1_preg[9] <= 1'b0;
        ap_return_1_preg[10] <= 1'b0;
        ap_return_1_preg[11] <= 1'b0;
        ap_return_1_preg[12] <= 1'b0;
        ap_return_1_preg[13] <= 1'b0;
        ap_return_1_preg[14] <= 1'b0;
        ap_return_1_preg[15] <= 1'b0;
        ap_return_1_preg[16] <= 1'b0;
        ap_return_1_preg[17] <= 1'b0;
        ap_return_1_preg[18] <= 1'b0;
        ap_return_1_preg[19] <= 1'b0;
        ap_return_1_preg[20] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
                        ap_return_1_preg[20 : 5] <= res_1_V_write_assign_fu_717_p3[20 : 5];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_2_preg[5] <= 1'b0;
        ap_return_2_preg[6] <= 1'b0;
        ap_return_2_preg[7] <= 1'b0;
        ap_return_2_preg[8] <= 1'b0;
        ap_return_2_preg[9] <= 1'b0;
        ap_return_2_preg[10] <= 1'b0;
        ap_return_2_preg[11] <= 1'b0;
        ap_return_2_preg[12] <= 1'b0;
        ap_return_2_preg[13] <= 1'b0;
        ap_return_2_preg[14] <= 1'b0;
        ap_return_2_preg[15] <= 1'b0;
        ap_return_2_preg[16] <= 1'b0;
        ap_return_2_preg[17] <= 1'b0;
        ap_return_2_preg[18] <= 1'b0;
        ap_return_2_preg[19] <= 1'b0;
        ap_return_2_preg[20] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
                        ap_return_2_preg[20 : 5] <= res_2_V_write_assign_fu_725_p3[20 : 5];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_3_preg[5] <= 1'b0;
        ap_return_3_preg[6] <= 1'b0;
        ap_return_3_preg[7] <= 1'b0;
        ap_return_3_preg[8] <= 1'b0;
        ap_return_3_preg[9] <= 1'b0;
        ap_return_3_preg[10] <= 1'b0;
        ap_return_3_preg[11] <= 1'b0;
        ap_return_3_preg[12] <= 1'b0;
        ap_return_3_preg[13] <= 1'b0;
        ap_return_3_preg[14] <= 1'b0;
        ap_return_3_preg[15] <= 1'b0;
        ap_return_3_preg[16] <= 1'b0;
        ap_return_3_preg[17] <= 1'b0;
        ap_return_3_preg[18] <= 1'b0;
        ap_return_3_preg[19] <= 1'b0;
        ap_return_3_preg[20] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
                        ap_return_3_preg[20 : 5] <= res_3_V_write_assign_fu_733_p3[20 : 5];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_4_preg[5] <= 1'b0;
        ap_return_4_preg[6] <= 1'b0;
        ap_return_4_preg[7] <= 1'b0;
        ap_return_4_preg[8] <= 1'b0;
        ap_return_4_preg[9] <= 1'b0;
        ap_return_4_preg[10] <= 1'b0;
        ap_return_4_preg[11] <= 1'b0;
        ap_return_4_preg[12] <= 1'b0;
        ap_return_4_preg[13] <= 1'b0;
        ap_return_4_preg[14] <= 1'b0;
        ap_return_4_preg[15] <= 1'b0;
        ap_return_4_preg[16] <= 1'b0;
        ap_return_4_preg[17] <= 1'b0;
        ap_return_4_preg[18] <= 1'b0;
        ap_return_4_preg[19] <= 1'b0;
        ap_return_4_preg[20] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
                        ap_return_4_preg[20 : 5] <= res_4_V_write_assign_fu_741_p3[20 : 5];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_5_preg[5] <= 1'b0;
        ap_return_5_preg[6] <= 1'b0;
        ap_return_5_preg[7] <= 1'b0;
        ap_return_5_preg[8] <= 1'b0;
        ap_return_5_preg[9] <= 1'b0;
        ap_return_5_preg[10] <= 1'b0;
        ap_return_5_preg[11] <= 1'b0;
        ap_return_5_preg[12] <= 1'b0;
        ap_return_5_preg[13] <= 1'b0;
        ap_return_5_preg[14] <= 1'b0;
        ap_return_5_preg[15] <= 1'b0;
        ap_return_5_preg[16] <= 1'b0;
        ap_return_5_preg[17] <= 1'b0;
        ap_return_5_preg[18] <= 1'b0;
        ap_return_5_preg[19] <= 1'b0;
        ap_return_5_preg[20] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
                        ap_return_5_preg[20 : 5] <= res_5_V_write_assign_fu_749_p3[20 : 5];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_6_preg[5] <= 1'b0;
        ap_return_6_preg[6] <= 1'b0;
        ap_return_6_preg[7] <= 1'b0;
        ap_return_6_preg[8] <= 1'b0;
        ap_return_6_preg[9] <= 1'b0;
        ap_return_6_preg[10] <= 1'b0;
        ap_return_6_preg[11] <= 1'b0;
        ap_return_6_preg[12] <= 1'b0;
        ap_return_6_preg[13] <= 1'b0;
        ap_return_6_preg[14] <= 1'b0;
        ap_return_6_preg[15] <= 1'b0;
        ap_return_6_preg[16] <= 1'b0;
        ap_return_6_preg[17] <= 1'b0;
        ap_return_6_preg[18] <= 1'b0;
        ap_return_6_preg[19] <= 1'b0;
        ap_return_6_preg[20] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
                        ap_return_6_preg[20 : 5] <= res_6_V_write_assign_fu_757_p3[20 : 5];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_7_preg[5] <= 1'b0;
        ap_return_7_preg[6] <= 1'b0;
        ap_return_7_preg[7] <= 1'b0;
        ap_return_7_preg[8] <= 1'b0;
        ap_return_7_preg[9] <= 1'b0;
        ap_return_7_preg[10] <= 1'b0;
        ap_return_7_preg[11] <= 1'b0;
        ap_return_7_preg[12] <= 1'b0;
        ap_return_7_preg[13] <= 1'b0;
        ap_return_7_preg[14] <= 1'b0;
        ap_return_7_preg[15] <= 1'b0;
        ap_return_7_preg[16] <= 1'b0;
        ap_return_7_preg[17] <= 1'b0;
        ap_return_7_preg[18] <= 1'b0;
        ap_return_7_preg[19] <= 1'b0;
        ap_return_7_preg[20] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
                        ap_return_7_preg[20 : 5] <= res_7_V_write_assign_fu_765_p3[20 : 5];
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln135_reg_862 == 1'd0))) begin
        in_index_025_reg_163 <= select_ln154_fu_573_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_index_025_reg_163 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd0))) begin
        p_Val2_1422_reg_193 <= ap_phi_mux_p_Val2_16_phi_fu_349_p8;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_1422_reg_193 <= 16'd65088;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd0))) begin
        p_Val2_1520_reg_208 <= ap_phi_mux_p_Val2_17_phi_fu_331_p8;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_1520_reg_208 <= 16'd160;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd0))) begin
        p_Val2_1618_reg_223 <= ap_phi_mux_p_Val2_18_phi_fu_313_p8;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_1618_reg_223 <= 16'd65504;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd0))) begin
        p_Val2_1716_reg_253 <= ap_phi_mux_p_Val2_19_phi_fu_439_p8;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_1716_reg_253 <= 16'd448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd0))) begin
        p_Val2_1814_reg_267 <= ap_phi_mux_p_Val2_20_phi_fu_421_p8;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_1814_reg_267 <= 16'd864;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd0))) begin
        p_Val2_1912_reg_281 <= ap_phi_mux_p_Val2_21_phi_fu_403_p8;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_1912_reg_281 <= 16'd65472;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd0))) begin
        p_Val2_2010_reg_295 <= ap_phi_mux_p_Val2_22_phi_fu_385_p8;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_2010_reg_295 <= 16'd65248;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd0))) begin
        p_Val2_24_reg_178 <= ap_phi_mux_p_Val2_s_phi_fu_367_p8;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_24_reg_178 <= 16'd65280;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln135_reg_862 == 1'd0))) begin
        w_index26_reg_148 <= w_index_reg_847;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        w_index26_reg_148 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        acc_0_V_reg_953 <= acc_0_V_fu_656_p2;
        icmp_ln135_reg_862_pp0_iter10_reg <= icmp_ln135_reg_862_pp0_iter9_reg;
        icmp_ln135_reg_862_pp0_iter11_reg <= icmp_ln135_reg_862_pp0_iter10_reg;
        icmp_ln135_reg_862_pp0_iter12_reg <= icmp_ln135_reg_862_pp0_iter11_reg;
        icmp_ln135_reg_862_pp0_iter2_reg <= icmp_ln135_reg_862_pp0_iter1_reg;
        icmp_ln135_reg_862_pp0_iter3_reg <= icmp_ln135_reg_862_pp0_iter2_reg;
        icmp_ln135_reg_862_pp0_iter4_reg <= icmp_ln135_reg_862_pp0_iter3_reg;
        icmp_ln135_reg_862_pp0_iter5_reg <= icmp_ln135_reg_862_pp0_iter4_reg;
        icmp_ln135_reg_862_pp0_iter6_reg <= icmp_ln135_reg_862_pp0_iter5_reg;
        icmp_ln135_reg_862_pp0_iter7_reg <= icmp_ln135_reg_862_pp0_iter6_reg;
        icmp_ln135_reg_862_pp0_iter8_reg <= icmp_ln135_reg_862_pp0_iter7_reg;
        icmp_ln135_reg_862_pp0_iter9_reg <= icmp_ln135_reg_862_pp0_iter8_reg;
        lshr_ln145_reg_896 <= grp_fu_582_p2;
        mul_ln1118_1_reg_948 <= grp_fu_831_p2;
        mul_ln1118_reg_943 <= grp_fu_825_p2;
        out_index_reg_906 <= outidx5_q0;
        out_index_reg_906_pp0_iter10_reg <= out_index_reg_906_pp0_iter9_reg;
        out_index_reg_906_pp0_iter11_reg <= out_index_reg_906_pp0_iter10_reg;
        out_index_reg_906_pp0_iter12_reg <= out_index_reg_906_pp0_iter11_reg;
        out_index_reg_906_pp0_iter9_reg <= out_index_reg_906;
        sub_ln145_3_reg_876_pp0_iter2_reg[7 : 1] <= sub_ln145_3_reg_876[7 : 1];
        sub_ln145_3_reg_876_pp0_iter3_reg[7 : 1] <= sub_ln145_3_reg_876_pp0_iter2_reg[7 : 1];
        sub_ln145_3_reg_876_pp0_iter4_reg[7 : 1] <= sub_ln145_3_reg_876_pp0_iter3_reg[7 : 1];
        sub_ln145_3_reg_876_pp0_iter5_reg[7 : 1] <= sub_ln145_3_reg_876_pp0_iter4_reg[7 : 1];
        sub_ln145_3_reg_876_pp0_iter6_reg[7 : 1] <= sub_ln145_3_reg_876_pp0_iter5_reg[7 : 1];
        sub_ln145_3_reg_876_pp0_iter7_reg[7 : 1] <= sub_ln145_3_reg_876_pp0_iter6_reg[7 : 1];
        tmp_40_reg_922 <= {{w2_V_q0[13:8]}};
        trunc_ln145_1_reg_912 <= trunc_ln145_1_fu_607_p1;
        trunc_ln145_2_reg_917 <= trunc_ln145_2_fu_611_p1;
        trunc_ln708_s_reg_961 <= {{mul_ln1118_1_reg_948[20:5]}};
        w_index26_reg_148_pp0_iter2_reg <= w_index26_reg_148_pp0_iter1_reg;
        w_index26_reg_148_pp0_iter3_reg <= w_index26_reg_148_pp0_iter2_reg;
        w_index26_reg_148_pp0_iter4_reg <= w_index26_reg_148_pp0_iter3_reg;
        w_index26_reg_148_pp0_iter5_reg <= w_index26_reg_148_pp0_iter4_reg;
        w_index26_reg_148_pp0_iter6_reg <= w_index26_reg_148_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_read_reg_837 <= data_V;
        icmp_ln135_reg_862 <= icmp_ln135_fu_481_p2;
        icmp_ln135_reg_862_pp0_iter1_reg <= icmp_ln135_reg_862;
        icmp_ln154_reg_857 <= icmp_ln154_fu_475_p2;
        in_index_reg_852 <= in_index_fu_469_p2;
        select_ln145_1_reg_866 <= select_ln145_1_fu_553_p3;
        select_ln145_2_reg_871 <= select_ln145_2_fu_559_p3;
        sub_ln145_3_reg_876[7 : 1] <= sub_ln145_3_fu_567_p2[7 : 1];
        tmp_127_reg_842 <= tmp_127_fu_453_p4;
        w_index26_reg_148_pp0_iter1_reg <= w_index26_reg_148;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_index_reg_847 <= w_index_fu_463_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_0to12 = 1'b1;
    end else begin
        ap_idle_pp0_0to12 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_247)) begin
        if ((icmp_ln135_reg_862 == 1'd1)) begin
            ap_phi_mux_in_index_025_phi_fu_167_p6 = 32'd0;
        end else if ((icmp_ln135_reg_862 == 1'd0)) begin
            ap_phi_mux_in_index_025_phi_fu_167_p6 = select_ln154_fu_573_p3;
        end else begin
            ap_phi_mux_in_index_025_phi_fu_167_p6 = in_index_025_reg_163;
        end
    end else begin
        ap_phi_mux_in_index_025_phi_fu_167_p6 = in_index_025_reg_163;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        if ((icmp_ln135_reg_862_pp0_iter12_reg == 1'd1)) begin
            ap_phi_mux_p_Val2_1422_phi_fu_197_p6 = 16'd65088;
        end else if ((icmp_ln135_reg_862_pp0_iter12_reg == 1'd0)) begin
            ap_phi_mux_p_Val2_1422_phi_fu_197_p6 = ap_phi_mux_p_Val2_16_phi_fu_349_p8;
        end else begin
            ap_phi_mux_p_Val2_1422_phi_fu_197_p6 = p_Val2_1422_reg_193;
        end
    end else begin
        ap_phi_mux_p_Val2_1422_phi_fu_197_p6 = p_Val2_1422_reg_193;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        if ((icmp_ln135_reg_862_pp0_iter12_reg == 1'd1)) begin
            ap_phi_mux_p_Val2_1520_phi_fu_212_p6 = 16'd160;
        end else if ((icmp_ln135_reg_862_pp0_iter12_reg == 1'd0)) begin
            ap_phi_mux_p_Val2_1520_phi_fu_212_p6 = ap_phi_mux_p_Val2_17_phi_fu_331_p8;
        end else begin
            ap_phi_mux_p_Val2_1520_phi_fu_212_p6 = p_Val2_1520_reg_208;
        end
    end else begin
        ap_phi_mux_p_Val2_1520_phi_fu_212_p6 = p_Val2_1520_reg_208;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        if ((icmp_ln135_reg_862_pp0_iter12_reg == 1'd1)) begin
            ap_phi_mux_p_Val2_1618_phi_fu_227_p6 = 16'd65504;
        end else if ((icmp_ln135_reg_862_pp0_iter12_reg == 1'd0)) begin
            ap_phi_mux_p_Val2_1618_phi_fu_227_p6 = ap_phi_mux_p_Val2_18_phi_fu_313_p8;
        end else begin
            ap_phi_mux_p_Val2_1618_phi_fu_227_p6 = p_Val2_1618_reg_223;
        end
    end else begin
        ap_phi_mux_p_Val2_1618_phi_fu_227_p6 = p_Val2_1618_reg_223;
    end
end

always @ (*) begin
    if ((out_index_reg_906_pp0_iter12_reg == 2'd1)) begin
        ap_phi_mux_p_Val2_16_phi_fu_349_p8 = acc_0_V_reg_953;
    end else if (((out_index_reg_906_pp0_iter12_reg == 2'd0) | (out_index_reg_906_pp0_iter12_reg == 2'd2) | (out_index_reg_906_pp0_iter12_reg == 2'd3))) begin
        ap_phi_mux_p_Val2_16_phi_fu_349_p8 = p_Val2_1422_reg_193;
    end else begin
        ap_phi_mux_p_Val2_16_phi_fu_349_p8 = ap_phi_reg_pp0_iter13_p_Val2_16_reg_345;
    end
end

always @ (*) begin
    if ((out_index_reg_906_pp0_iter12_reg == 2'd2)) begin
        ap_phi_mux_p_Val2_17_phi_fu_331_p8 = acc_0_V_reg_953;
    end else if (((out_index_reg_906_pp0_iter12_reg == 2'd0) | (out_index_reg_906_pp0_iter12_reg == 2'd1) | (out_index_reg_906_pp0_iter12_reg == 2'd3))) begin
        ap_phi_mux_p_Val2_17_phi_fu_331_p8 = p_Val2_1520_reg_208;
    end else begin
        ap_phi_mux_p_Val2_17_phi_fu_331_p8 = ap_phi_reg_pp0_iter13_p_Val2_17_reg_327;
    end
end

always @ (*) begin
    if (((out_index_reg_906_pp0_iter12_reg == 2'd0) | (out_index_reg_906_pp0_iter12_reg == 2'd1) | (out_index_reg_906_pp0_iter12_reg == 2'd2))) begin
        ap_phi_mux_p_Val2_18_phi_fu_313_p8 = p_Val2_1618_reg_223;
    end else if ((out_index_reg_906_pp0_iter12_reg == 2'd3)) begin
        ap_phi_mux_p_Val2_18_phi_fu_313_p8 = acc_0_V_reg_953;
    end else begin
        ap_phi_mux_p_Val2_18_phi_fu_313_p8 = ap_phi_reg_pp0_iter13_p_Val2_18_reg_309;
    end
end

always @ (*) begin
    if ((or_ln_fu_671_p3 == 3'd4)) begin
        ap_phi_mux_p_Val2_19_phi_fu_439_p8 = acc_4_V_fu_700_p2;
    end else if (((or_ln_fu_671_p3 == 3'd6) | (or_ln_fu_671_p3 == 3'd5) | (~(or_ln_fu_671_p3 == 3'd6) & ~(or_ln_fu_671_p3 == 3'd5) & ~(or_ln_fu_671_p3 == 3'd4)))) begin
        ap_phi_mux_p_Val2_19_phi_fu_439_p8 = p_Val2_1716_reg_253;
    end else begin
        ap_phi_mux_p_Val2_19_phi_fu_439_p8 = ap_phi_reg_pp0_iter13_p_Val2_19_reg_435;
    end
end

always @ (*) begin
    if ((or_ln_fu_671_p3 == 3'd5)) begin
        ap_phi_mux_p_Val2_20_phi_fu_421_p8 = acc_4_V_fu_700_p2;
    end else if (((or_ln_fu_671_p3 == 3'd6) | (or_ln_fu_671_p3 == 3'd4) | (~(or_ln_fu_671_p3 == 3'd6) & ~(or_ln_fu_671_p3 == 3'd5) & ~(or_ln_fu_671_p3 == 3'd4)))) begin
        ap_phi_mux_p_Val2_20_phi_fu_421_p8 = p_Val2_1814_reg_267;
    end else begin
        ap_phi_mux_p_Val2_20_phi_fu_421_p8 = ap_phi_reg_pp0_iter13_p_Val2_20_reg_417;
    end
end

always @ (*) begin
    if ((or_ln_fu_671_p3 == 3'd6)) begin
        ap_phi_mux_p_Val2_21_phi_fu_403_p8 = acc_4_V_fu_700_p2;
    end else if (((or_ln_fu_671_p3 == 3'd5) | (or_ln_fu_671_p3 == 3'd4) | (~(or_ln_fu_671_p3 == 3'd6) & ~(or_ln_fu_671_p3 == 3'd5) & ~(or_ln_fu_671_p3 == 3'd4)))) begin
        ap_phi_mux_p_Val2_21_phi_fu_403_p8 = p_Val2_1912_reg_281;
    end else begin
        ap_phi_mux_p_Val2_21_phi_fu_403_p8 = ap_phi_reg_pp0_iter13_p_Val2_21_reg_399;
    end
end

always @ (*) begin
    if (((or_ln_fu_671_p3 == 3'd6) | (or_ln_fu_671_p3 == 3'd5) | (or_ln_fu_671_p3 == 3'd4))) begin
        ap_phi_mux_p_Val2_22_phi_fu_385_p8 = p_Val2_2010_reg_295;
    end else if ((~(or_ln_fu_671_p3 == 3'd6) & ~(or_ln_fu_671_p3 == 3'd5) & ~(or_ln_fu_671_p3 == 3'd4))) begin
        ap_phi_mux_p_Val2_22_phi_fu_385_p8 = acc_4_V_fu_700_p2;
    end else begin
        ap_phi_mux_p_Val2_22_phi_fu_385_p8 = ap_phi_reg_pp0_iter13_p_Val2_22_reg_381;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        if ((icmp_ln135_reg_862_pp0_iter12_reg == 1'd1)) begin
            ap_phi_mux_p_Val2_24_phi_fu_182_p6 = 16'd65280;
        end else if ((icmp_ln135_reg_862_pp0_iter12_reg == 1'd0)) begin
            ap_phi_mux_p_Val2_24_phi_fu_182_p6 = ap_phi_mux_p_Val2_s_phi_fu_367_p8;
        end else begin
            ap_phi_mux_p_Val2_24_phi_fu_182_p6 = p_Val2_24_reg_178;
        end
    end else begin
        ap_phi_mux_p_Val2_24_phi_fu_182_p6 = p_Val2_24_reg_178;
    end
end

always @ (*) begin
    if ((out_index_reg_906_pp0_iter12_reg == 2'd0)) begin
        ap_phi_mux_p_Val2_s_phi_fu_367_p8 = acc_0_V_reg_953;
    end else if (((out_index_reg_906_pp0_iter12_reg == 2'd1) | (out_index_reg_906_pp0_iter12_reg == 2'd2) | (out_index_reg_906_pp0_iter12_reg == 2'd3))) begin
        ap_phi_mux_p_Val2_s_phi_fu_367_p8 = p_Val2_24_reg_178;
    end else begin
        ap_phi_mux_p_Val2_s_phi_fu_367_p8 = ap_phi_reg_pp0_iter13_p_Val2_s_reg_363;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_247)) begin
        if ((icmp_ln135_reg_862 == 1'd1)) begin
            ap_phi_mux_w_index26_phi_fu_152_p6 = 6'd0;
        end else if ((icmp_ln135_reg_862 == 1'd0)) begin
            ap_phi_mux_w_index26_phi_fu_152_p6 = w_index_reg_847;
        end else begin
            ap_phi_mux_w_index26_phi_fu_152_p6 = w_index26_reg_148;
        end
    end else begin
        ap_phi_mux_w_index26_phi_fu_152_p6 = w_index26_reg_148;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_fu_481_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to12 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ap_return_0 = res_0_V_write_assign_fu_709_p3;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ap_return_1 = res_1_V_write_assign_fu_717_p3;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ap_return_2 = res_2_V_write_assign_fu_725_p3;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ap_return_3 = res_3_V_write_assign_fu_733_p3;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ap_return_4 = res_4_V_write_assign_fu_741_p3;
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ap_return_5 = res_5_V_write_assign_fu_749_p3;
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ap_return_6 = res_6_V_write_assign_fu_757_p3;
    end else begin
        ap_return_6 = ap_return_6_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_862_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ap_return_7 = res_7_V_write_assign_fu_765_p3;
    end else begin
        ap_return_7 = ap_return_7_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_blk_n = data_V_ap_vld;
    end else begin
        data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_582_ce = 1'b1;
    end else begin
        grp_fu_582_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_825_ce = 1'b1;
    end else begin
        grp_fu_825_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_831_ce = 1'b1;
    end else begin
        grp_fu_831_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        outidx5_ce0 = 1'b1;
    end else begin
        outidx5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        w2_V_ce0 = 1'b1;
    end else begin
        w2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_0_V_fu_656_p2 = (phi_ln_fu_643_p6 + trunc_ln_fu_634_p4);

assign acc_4_V_fu_700_p2 = (phi_ln1265_2_fu_678_p10 + trunc_ln708_s_reg_961);

assign and_ln145_fu_602_p2 = (lshr_ln145_reg_896 & lshr_ln145_1_fu_596_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((data_V_ap_vld == 1'b0) & (ap_start == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((data_V_ap_vld == 1'b0) & (ap_start == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state10_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = (data_V_ap_vld == 1'b0);
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_247 = ((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter13_p_Val2_16_reg_345 = 'bx;

assign ap_phi_reg_pp0_iter13_p_Val2_17_reg_327 = 'bx;

assign ap_phi_reg_pp0_iter13_p_Val2_18_reg_309 = 'bx;

assign ap_phi_reg_pp0_iter13_p_Val2_19_reg_435 = 'bx;

assign ap_phi_reg_pp0_iter13_p_Val2_20_reg_417 = 'bx;

assign ap_phi_reg_pp0_iter13_p_Val2_21_reg_399 = 'bx;

assign ap_phi_reg_pp0_iter13_p_Val2_22_reg_381 = 'bx;

assign ap_phi_reg_pp0_iter13_p_Val2_s_reg_363 = 'bx;

assign empty_24_fu_491_p1 = in_index_025_reg_163[3:0];

assign empty_25_fu_503_p2 = (tmp_2_fu_495_p3 | 9'd15);

assign empty_fu_487_p1 = in_index_025_reg_163[4:0];

assign grp_fu_582_p1 = select_ln145_2_reg_871;

assign grp_fu_825_p1 = sext_ln1116_cast_fu_625_p1;

assign grp_fu_831_p0 = sext_ln1116_cast_fu_625_p1;

assign icmp_ln135_fu_481_p2 = ((ap_phi_mux_w_index26_phi_fu_152_p6 == 6'd55) ? 1'b1 : 1'b0);

assign icmp_ln145_fu_509_p2 = ((tmp_2_fu_495_p3 > empty_25_fu_503_p2) ? 1'b1 : 1'b0);

assign icmp_ln154_fu_475_p2 = (($signed(in_index_fu_469_p2) > $signed(32'd13)) ? 1'b1 : 1'b0);

assign in_index_fu_469_p2 = (ap_phi_mux_in_index_025_phi_fu_167_p6 + 32'd1);

assign lshr_ln145_1_fu_596_p2 = 224'd26959946667150639794667015087019630673637144422540572481103610249215 >> zext_ln145_1_fu_593_p1;

assign or_ln_fu_671_p3 = {{1'd1}, {out_index_reg_906_pp0_iter12_reg}};

assign outidx5_address0 = zext_ln139_fu_587_p1;

assign phi_ln1265_2_fu_678_p9 = {{1'd1}, {out_index_reg_906_pp0_iter12_reg}};

assign res_0_V_write_assign_fu_709_p3 = {{ap_phi_mux_p_Val2_s_phi_fu_367_p8}, {5'd0}};

assign res_1_V_write_assign_fu_717_p3 = {{ap_phi_mux_p_Val2_16_phi_fu_349_p8}, {5'd0}};

assign res_2_V_write_assign_fu_725_p3 = {{ap_phi_mux_p_Val2_17_phi_fu_331_p8}, {5'd0}};

assign res_3_V_write_assign_fu_733_p3 = {{ap_phi_mux_p_Val2_18_phi_fu_313_p8}, {5'd0}};

assign res_4_V_write_assign_fu_741_p3 = {{ap_phi_mux_p_Val2_19_phi_fu_439_p8}, {5'd0}};

assign res_5_V_write_assign_fu_749_p3 = {{ap_phi_mux_p_Val2_20_phi_fu_421_p8}, {5'd0}};

assign res_6_V_write_assign_fu_757_p3 = {{ap_phi_mux_p_Val2_21_phi_fu_403_p8}, {5'd0}};

assign res_7_V_write_assign_fu_765_p3 = {{ap_phi_mux_p_Val2_22_phi_fu_385_p8}, {5'd0}};

assign select_ln145_1_fu_553_p3 = ((icmp_ln145_fu_509_p2[0:0] === 1'b1) ? tmp_127_reg_842 : data_V_read_reg_837);

assign select_ln145_2_fu_559_p3 = ((icmp_ln145_fu_509_p2[0:0] === 1'b1) ? sub_ln145_1_fu_533_p2 : tmp_126_fu_515_p3);

assign select_ln145_fu_545_p3 = ((icmp_ln145_fu_509_p2[0:0] === 1'b1) ? sub_ln145_fu_527_p2 : sub_ln145_2_fu_539_p2);

assign select_ln154_fu_573_p3 = ((icmp_ln154_reg_857[0:0] === 1'b1) ? 32'd0 : in_index_reg_852);

assign sext_ln1116_cast_fu_625_p1 = $signed(trunc_ln145_1_reg_912);

assign sub_ln145_1_fu_533_p2 = ($signed(8'd223) - $signed(tmp_126_fu_515_p3));

assign sub_ln145_2_fu_539_p2 = (trunc_ln145_fu_523_p1 - tmp_126_fu_515_p3);

assign sub_ln145_3_fu_567_p2 = ($signed(8'd223) - $signed(select_ln145_fu_545_p3));

assign sub_ln145_fu_527_p2 = (tmp_126_fu_515_p3 - trunc_ln145_fu_523_p1);

assign tmp_126_fu_515_p3 = {{empty_24_fu_491_p1}, {4'd0}};

integer ap_tvar_int_0;

always @ (data_V) begin
    for (ap_tvar_int_0 = 224 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 223 - 0) begin
            tmp_127_fu_453_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            tmp_127_fu_453_p4[ap_tvar_int_0] = data_V[223 - ap_tvar_int_0];
        end
    end
end

assign tmp_2_fu_495_p3 = {{empty_fu_487_p1}, {4'd0}};

assign trunc_ln145_1_fu_607_p1 = and_ln145_fu_602_p2[15:0];

assign trunc_ln145_2_fu_611_p1 = w2_V_q0[7:0];

assign trunc_ln145_fu_523_p1 = empty_25_fu_503_p2[7:0];

assign trunc_ln_fu_634_p4 = {{mul_ln1118_reg_943[20:5]}};

assign w2_V_address0 = zext_ln139_fu_587_p1;

assign w_index_fu_463_p2 = (ap_phi_mux_w_index26_phi_fu_152_p6 + 6'd1);

assign zext_ln139_fu_587_p1 = w_index26_reg_148_pp0_iter6_reg;

assign zext_ln145_1_fu_593_p1 = sub_ln145_3_reg_876_pp0_iter7_reg;

always @ (posedge ap_clk) begin
    sub_ln145_3_reg_876[0] <= 1'b0;
    sub_ln145_3_reg_876_pp0_iter2_reg[0] <= 1'b0;
    sub_ln145_3_reg_876_pp0_iter3_reg[0] <= 1'b0;
    sub_ln145_3_reg_876_pp0_iter4_reg[0] <= 1'b0;
    sub_ln145_3_reg_876_pp0_iter5_reg[0] <= 1'b0;
    sub_ln145_3_reg_876_pp0_iter6_reg[0] <= 1'b0;
    sub_ln145_3_reg_876_pp0_iter7_reg[0] <= 1'b0;
    ap_return_0_preg[4:0] <= 5'b00000;
    ap_return_1_preg[4:0] <= 5'b00000;
    ap_return_2_preg[4:0] <= 5'b00000;
    ap_return_3_preg[4:0] <= 5'b00000;
    ap_return_4_preg[4:0] <= 5'b00000;
    ap_return_5_preg[4:0] <= 5'b00000;
    ap_return_6_preg[4:0] <= 5'b00000;
    ap_return_7_preg[4:0] <= 5'b00000;
end

endmodule //dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_config2_0_0_0_0_0_0_0_0_0
