// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_resource_rf_gt_nin_rem0_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] p_read;
input  [7:0] p_read1;
input  [7:0] p_read2;
input  [7:0] p_read3;
output  [16:0] ap_return_0;
output  [16:0] ap_return_1;
output  [16:0] ap_return_2;
output  [16:0] ap_return_3;
output  [16:0] ap_return_4;
output  [16:0] ap_return_5;
output  [16:0] ap_return_6;
output  [16:0] ap_return_7;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[16:0] ap_return_0;
reg[16:0] ap_return_1;
reg[16:0] ap_return_2;
reg[16:0] ap_return_3;
reg[16:0] ap_return_4;
reg[16:0] ap_return_5;
reg[16:0] ap_return_6;
reg[16:0] ap_return_7;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln135_fu_1039_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_11001;
wire   [4:0] outidx1_address0;
reg    outidx1_ce0;
wire   [2:0] outidx1_q0;
wire   [4:0] w14_V_address0;
reg    w14_V_ce0;
wire   [6:0] w14_V_q0;
reg   [0:0] do_init_reg_152;
reg   [4:0] w_index34_reg_168;
reg   [31:0] in_index_033_reg_182;
reg   [7:0] p_read35_rewind_reg_197;
reg   [7:0] p_read136_rewind_reg_211;
reg   [7:0] p_read237_rewind_reg_225;
reg   [7:0] p_read338_rewind_reg_239;
reg   [7:0] p_read35_phi_reg_253;
reg   [7:0] p_read136_phi_reg_265;
reg   [7:0] p_read237_phi_reg_277;
reg   [7:0] p_read338_phi_reg_289;
reg   [15:0] p_Val2_32_reg_301;
reg   [15:0] p_Val2_630_reg_315;
reg   [15:0] p_Val2_728_reg_329;
reg   [15:0] p_Val2_826_reg_343;
reg   [15:0] p_Val2_924_reg_357;
reg   [15:0] p_Val2_1022_reg_371;
reg   [15:0] p_Val2_1120_reg_385;
reg   [15:0] p_Val2_1218_reg_399;
reg   [15:0] acc_0_V_016_reg_413;
reg   [15:0] acc_1_V_015_reg_427;
reg   [15:0] acc_2_V_014_reg_441;
reg   [15:0] acc_3_V_013_reg_455;
reg   [15:0] acc_4_V_012_reg_469;
reg   [15:0] acc_5_V_011_reg_483;
reg   [15:0] acc_6_V_010_reg_497;
reg   [15:0] acc_7_V_09_reg_511;
reg   [0:0] ap_phi_mux_do_init_phi_fu_156_p6;
wire   [4:0] w_index_fu_1011_p2;
reg   [4:0] w_index_reg_1283;
wire   [31:0] in_index_fu_1017_p2;
reg   [31:0] in_index_reg_1288;
wire   [0:0] icmp_ln154_fu_1033_p2;
reg   [0:0] icmp_ln154_reg_1293;
reg   [0:0] icmp_ln135_reg_1298;
reg   [0:0] icmp_ln135_reg_1298_pp0_iter1_reg;
reg   [0:0] icmp_ln135_reg_1298_pp0_iter2_reg;
reg   [2:0] out_index_reg_1302;
reg   [2:0] out_index_reg_1302_pp0_iter2_reg;
wire   [7:0] tmp_36_fu_1049_p6;
reg   [7:0] tmp_36_reg_1307;
reg   [6:0] w14_V_load_reg_1312;
wire   [31:0] select_ln154_fu_1063_p3;
reg    ap_enable_reg_pp0_iter1;
reg   [13:0] trunc_ln_reg_1322;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
wire    ap_block_pp0_stage0;
reg   [4:0] ap_phi_mux_w_index34_phi_fu_172_p6;
reg   [31:0] ap_phi_mux_in_index_033_phi_fu_186_p6;
reg   [7:0] ap_phi_mux_p_read35_rewind_phi_fu_201_p6;
reg   [7:0] ap_phi_mux_p_read136_rewind_phi_fu_215_p6;
reg   [7:0] ap_phi_mux_p_read237_rewind_phi_fu_229_p6;
reg   [7:0] ap_phi_mux_p_read338_rewind_phi_fu_243_p6;
reg   [7:0] ap_phi_mux_p_read35_phi_phi_fu_257_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read35_phi_reg_253;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read35_phi_reg_253;
reg   [7:0] ap_phi_mux_p_read136_phi_phi_fu_269_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read136_phi_reg_265;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read136_phi_reg_265;
reg   [7:0] ap_phi_mux_p_read237_phi_phi_fu_281_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read237_phi_reg_277;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read237_phi_reg_277;
reg   [7:0] ap_phi_mux_p_read338_phi_phi_fu_293_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read338_phi_reg_289;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read338_phi_reg_289;
reg   [15:0] ap_phi_mux_p_Val2_s_phi_fu_979_p16;
reg   [15:0] ap_phi_mux_p_Val2_9_phi_fu_949_p16;
reg   [15:0] ap_phi_mux_p_Val2_10_phi_fu_919_p16;
reg   [15:0] ap_phi_mux_p_Val2_11_phi_fu_889_p16;
reg   [15:0] ap_phi_mux_p_Val2_12_phi_fu_859_p16;
reg   [15:0] ap_phi_mux_p_Val2_13_phi_fu_829_p16;
reg   [15:0] ap_phi_mux_p_Val2_14_phi_fu_799_p16;
reg   [15:0] ap_phi_mux_p_Val2_15_phi_fu_769_p16;
reg   [15:0] ap_phi_mux_acc_0_V_1_phi_fu_739_p16;
reg   [15:0] ap_phi_mux_acc_1_V_1_phi_fu_709_p16;
reg   [15:0] ap_phi_mux_acc_2_V_1_phi_fu_679_p16;
reg   [15:0] ap_phi_mux_acc_3_V_1_phi_fu_649_p16;
reg   [15:0] ap_phi_mux_acc_4_V_1_phi_fu_619_p16;
reg   [15:0] ap_phi_mux_acc_5_V_1_phi_fu_589_p16;
reg   [15:0] ap_phi_mux_acc_6_V_1_phi_fu_559_p16;
reg   [15:0] ap_phi_mux_acc_7_V_1_phi_fu_529_p16;
wire   [15:0] acc_0_V_fu_1115_p2;
wire   [15:0] ap_phi_reg_pp0_iter3_acc_7_V_1_reg_525;
wire   [15:0] ap_phi_reg_pp0_iter3_acc_6_V_1_reg_555;
wire   [15:0] ap_phi_reg_pp0_iter3_acc_5_V_1_reg_585;
wire   [15:0] ap_phi_reg_pp0_iter3_acc_4_V_1_reg_615;
wire   [15:0] ap_phi_reg_pp0_iter3_acc_3_V_1_reg_645;
wire   [15:0] ap_phi_reg_pp0_iter3_acc_2_V_1_reg_675;
wire   [15:0] ap_phi_reg_pp0_iter3_acc_1_V_1_reg_705;
wire   [15:0] ap_phi_reg_pp0_iter3_acc_0_V_1_reg_735;
wire   [15:0] ap_phi_reg_pp0_iter3_p_Val2_15_reg_765;
wire   [15:0] ap_phi_reg_pp0_iter3_p_Val2_14_reg_795;
wire   [15:0] ap_phi_reg_pp0_iter3_p_Val2_13_reg_825;
wire   [15:0] ap_phi_reg_pp0_iter3_p_Val2_12_reg_855;
wire   [15:0] ap_phi_reg_pp0_iter3_p_Val2_11_reg_885;
wire   [15:0] ap_phi_reg_pp0_iter3_p_Val2_10_reg_915;
wire   [15:0] ap_phi_reg_pp0_iter3_p_Val2_9_reg_945;
wire   [15:0] ap_phi_reg_pp0_iter3_p_Val2_s_reg_975;
wire   [63:0] zext_ln139_fu_1005_p1;
wire   [29:0] tmp_133_fu_1023_p4;
wire   [1:0] tmp_36_fu_1049_p5;
wire   [7:0] r_V_fu_1075_p0;
wire  signed [6:0] r_V_fu_1075_p1;
wire   [14:0] r_V_fu_1075_p2;
wire   [15:0] tmp_37_fu_1094_p10;
wire  signed [15:0] sext_ln708_fu_1091_p1;
wire   [16:0] res_0_V_write_assign_fu_1137_p3;
wire   [16:0] res_1_V_write_assign_fu_1145_p3;
wire   [16:0] res_2_V_write_assign_fu_1153_p3;
wire   [16:0] res_3_V_write_assign_fu_1161_p3;
wire   [16:0] res_4_V_write_assign_fu_1169_p3;
wire   [16:0] res_5_V_write_assign_fu_1177_p3;
wire   [16:0] res_6_V_write_assign_fu_1185_p3;
wire   [16:0] res_7_V_write_assign_fu_1193_p3;
reg   [16:0] ap_return_0_preg;
reg   [16:0] ap_return_1_preg;
reg   [16:0] ap_return_2_preg;
reg   [16:0] ap_return_3_preg;
reg   [16:0] ap_return_4_preg;
reg   [16:0] ap_return_5_preg;
reg   [16:0] ap_return_6_preg;
reg   [16:0] ap_return_7_preg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to2;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [14:0] r_V_fu_1075_p00;
reg    ap_condition_217;
reg    ap_condition_44;
reg    ap_condition_198;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_return_0_preg = 17'd0;
#0 ap_return_1_preg = 17'd0;
#0 ap_return_2_preg = 17'd0;
#0 ap_return_3_preg = 17'd0;
#0 ap_return_4_preg = 17'd0;
#0 ap_return_5_preg = 17'd0;
#0 ap_return_6_preg = 17'd0;
#0 ap_return_7_preg = 17'd0;
end

dense_resource_rf_gt_nin_rem0_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0_odEe #(
    .DataWidth( 3 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
outidx1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(outidx1_address0),
    .ce0(outidx1_ce0),
    .q0(outidx1_q0)
);

dense_resource_rf_gt_nin_rem0_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0_weOg #(
    .DataWidth( 7 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
w14_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w14_V_address0),
    .ce0(w14_V_ce0),
    .q0(w14_V_q0)
);

myproject_axi_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
myproject_axi_mux_42_8_1_1_U64(
    .din0(ap_phi_mux_p_read35_phi_phi_fu_257_p4),
    .din1(ap_phi_mux_p_read136_phi_phi_fu_269_p4),
    .din2(ap_phi_mux_p_read237_phi_phi_fu_281_p4),
    .din3(ap_phi_mux_p_read338_phi_phi_fu_293_p4),
    .din4(tmp_36_fu_1049_p5),
    .dout(tmp_36_fu_1049_p6)
);

myproject_axi_mux_83_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
myproject_axi_mux_83_16_1_1_U65(
    .din0(acc_0_V_016_reg_413),
    .din1(acc_1_V_015_reg_427),
    .din2(acc_2_V_014_reg_441),
    .din3(acc_3_V_013_reg_455),
    .din4(acc_4_V_012_reg_469),
    .din5(acc_5_V_011_reg_483),
    .din6(acc_6_V_010_reg_497),
    .din7(acc_7_V_09_reg_511),
    .din8(out_index_reg_1302_pp0_iter2_reg),
    .dout(tmp_37_fu_1094_p10)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_0_preg[1] <= 1'b0;
        ap_return_0_preg[2] <= 1'b0;
        ap_return_0_preg[3] <= 1'b0;
        ap_return_0_preg[4] <= 1'b0;
        ap_return_0_preg[5] <= 1'b0;
        ap_return_0_preg[6] <= 1'b0;
        ap_return_0_preg[7] <= 1'b0;
        ap_return_0_preg[8] <= 1'b0;
        ap_return_0_preg[9] <= 1'b0;
        ap_return_0_preg[10] <= 1'b0;
        ap_return_0_preg[11] <= 1'b0;
        ap_return_0_preg[12] <= 1'b0;
        ap_return_0_preg[13] <= 1'b0;
        ap_return_0_preg[14] <= 1'b0;
        ap_return_0_preg[15] <= 1'b0;
        ap_return_0_preg[16] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
                        ap_return_0_preg[16 : 1] <= res_0_V_write_assign_fu_1137_p3[16 : 1];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_1_preg[1] <= 1'b0;
        ap_return_1_preg[2] <= 1'b0;
        ap_return_1_preg[3] <= 1'b0;
        ap_return_1_preg[4] <= 1'b0;
        ap_return_1_preg[5] <= 1'b0;
        ap_return_1_preg[6] <= 1'b0;
        ap_return_1_preg[7] <= 1'b0;
        ap_return_1_preg[8] <= 1'b0;
        ap_return_1_preg[9] <= 1'b0;
        ap_return_1_preg[10] <= 1'b0;
        ap_return_1_preg[11] <= 1'b0;
        ap_return_1_preg[12] <= 1'b0;
        ap_return_1_preg[13] <= 1'b0;
        ap_return_1_preg[14] <= 1'b0;
        ap_return_1_preg[15] <= 1'b0;
        ap_return_1_preg[16] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
                        ap_return_1_preg[16 : 1] <= res_1_V_write_assign_fu_1145_p3[16 : 1];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_2_preg[1] <= 1'b0;
        ap_return_2_preg[2] <= 1'b0;
        ap_return_2_preg[3] <= 1'b0;
        ap_return_2_preg[4] <= 1'b0;
        ap_return_2_preg[5] <= 1'b0;
        ap_return_2_preg[6] <= 1'b0;
        ap_return_2_preg[7] <= 1'b0;
        ap_return_2_preg[8] <= 1'b0;
        ap_return_2_preg[9] <= 1'b0;
        ap_return_2_preg[10] <= 1'b0;
        ap_return_2_preg[11] <= 1'b0;
        ap_return_2_preg[12] <= 1'b0;
        ap_return_2_preg[13] <= 1'b0;
        ap_return_2_preg[14] <= 1'b0;
        ap_return_2_preg[15] <= 1'b0;
        ap_return_2_preg[16] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
                        ap_return_2_preg[16 : 1] <= res_2_V_write_assign_fu_1153_p3[16 : 1];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_3_preg[1] <= 1'b0;
        ap_return_3_preg[2] <= 1'b0;
        ap_return_3_preg[3] <= 1'b0;
        ap_return_3_preg[4] <= 1'b0;
        ap_return_3_preg[5] <= 1'b0;
        ap_return_3_preg[6] <= 1'b0;
        ap_return_3_preg[7] <= 1'b0;
        ap_return_3_preg[8] <= 1'b0;
        ap_return_3_preg[9] <= 1'b0;
        ap_return_3_preg[10] <= 1'b0;
        ap_return_3_preg[11] <= 1'b0;
        ap_return_3_preg[12] <= 1'b0;
        ap_return_3_preg[13] <= 1'b0;
        ap_return_3_preg[14] <= 1'b0;
        ap_return_3_preg[15] <= 1'b0;
        ap_return_3_preg[16] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
                        ap_return_3_preg[16 : 1] <= res_3_V_write_assign_fu_1161_p3[16 : 1];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_4_preg[1] <= 1'b0;
        ap_return_4_preg[2] <= 1'b0;
        ap_return_4_preg[3] <= 1'b0;
        ap_return_4_preg[4] <= 1'b0;
        ap_return_4_preg[5] <= 1'b0;
        ap_return_4_preg[6] <= 1'b0;
        ap_return_4_preg[7] <= 1'b0;
        ap_return_4_preg[8] <= 1'b0;
        ap_return_4_preg[9] <= 1'b0;
        ap_return_4_preg[10] <= 1'b0;
        ap_return_4_preg[11] <= 1'b0;
        ap_return_4_preg[12] <= 1'b0;
        ap_return_4_preg[13] <= 1'b0;
        ap_return_4_preg[14] <= 1'b0;
        ap_return_4_preg[15] <= 1'b0;
        ap_return_4_preg[16] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
                        ap_return_4_preg[16 : 1] <= res_4_V_write_assign_fu_1169_p3[16 : 1];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_5_preg[1] <= 1'b0;
        ap_return_5_preg[2] <= 1'b0;
        ap_return_5_preg[3] <= 1'b0;
        ap_return_5_preg[4] <= 1'b0;
        ap_return_5_preg[5] <= 1'b0;
        ap_return_5_preg[6] <= 1'b0;
        ap_return_5_preg[7] <= 1'b0;
        ap_return_5_preg[8] <= 1'b0;
        ap_return_5_preg[9] <= 1'b0;
        ap_return_5_preg[10] <= 1'b0;
        ap_return_5_preg[11] <= 1'b0;
        ap_return_5_preg[12] <= 1'b0;
        ap_return_5_preg[13] <= 1'b0;
        ap_return_5_preg[14] <= 1'b0;
        ap_return_5_preg[15] <= 1'b0;
        ap_return_5_preg[16] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
                        ap_return_5_preg[16 : 1] <= res_5_V_write_assign_fu_1177_p3[16 : 1];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_6_preg[1] <= 1'b0;
        ap_return_6_preg[2] <= 1'b0;
        ap_return_6_preg[3] <= 1'b0;
        ap_return_6_preg[4] <= 1'b0;
        ap_return_6_preg[5] <= 1'b0;
        ap_return_6_preg[6] <= 1'b0;
        ap_return_6_preg[7] <= 1'b0;
        ap_return_6_preg[8] <= 1'b0;
        ap_return_6_preg[9] <= 1'b0;
        ap_return_6_preg[10] <= 1'b0;
        ap_return_6_preg[11] <= 1'b0;
        ap_return_6_preg[12] <= 1'b0;
        ap_return_6_preg[13] <= 1'b0;
        ap_return_6_preg[14] <= 1'b0;
        ap_return_6_preg[15] <= 1'b0;
        ap_return_6_preg[16] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
                        ap_return_6_preg[16 : 1] <= res_6_V_write_assign_fu_1185_p3[16 : 1];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_7_preg[1] <= 1'b0;
        ap_return_7_preg[2] <= 1'b0;
        ap_return_7_preg[3] <= 1'b0;
        ap_return_7_preg[4] <= 1'b0;
        ap_return_7_preg[5] <= 1'b0;
        ap_return_7_preg[6] <= 1'b0;
        ap_return_7_preg[7] <= 1'b0;
        ap_return_7_preg[8] <= 1'b0;
        ap_return_7_preg[9] <= 1'b0;
        ap_return_7_preg[10] <= 1'b0;
        ap_return_7_preg[11] <= 1'b0;
        ap_return_7_preg[12] <= 1'b0;
        ap_return_7_preg[13] <= 1'b0;
        ap_return_7_preg[14] <= 1'b0;
        ap_return_7_preg[15] <= 1'b0;
        ap_return_7_preg[16] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
                        ap_return_7_preg[16 : 1] <= res_7_V_write_assign_fu_1193_p3[16 : 1];
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd0))) begin
        acc_0_V_016_reg_413 <= ap_phi_mux_acc_0_V_1_phi_fu_739_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_0_V_016_reg_413 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd0))) begin
        acc_1_V_015_reg_427 <= ap_phi_mux_acc_1_V_1_phi_fu_709_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_1_V_015_reg_427 <= 16'd65376;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd0))) begin
        acc_2_V_014_reg_441 <= ap_phi_mux_acc_2_V_1_phi_fu_679_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_2_V_014_reg_441 <= 16'd65504;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd0))) begin
        acc_3_V_013_reg_455 <= ap_phi_mux_acc_3_V_1_phi_fu_649_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_3_V_013_reg_455 <= 16'd224;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd0))) begin
        acc_4_V_012_reg_469 <= ap_phi_mux_acc_4_V_1_phi_fu_619_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_4_V_012_reg_469 <= 16'd576;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd0))) begin
        acc_5_V_011_reg_483 <= ap_phi_mux_acc_5_V_1_phi_fu_589_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_5_V_011_reg_483 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd0))) begin
        acc_6_V_010_reg_497 <= ap_phi_mux_acc_6_V_1_phi_fu_559_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_6_V_010_reg_497 <= 16'd65344;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd0))) begin
        acc_7_V_09_reg_511 <= ap_phi_mux_acc_7_V_1_phi_fu_529_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_7_V_09_reg_511 <= 16'd65344;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_44)) begin
        if ((ap_phi_mux_do_init_phi_fu_156_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read136_phi_reg_265 <= p_read1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read136_phi_reg_265 <= ap_phi_reg_pp0_iter0_p_read136_phi_reg_265;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_44)) begin
        if ((ap_phi_mux_do_init_phi_fu_156_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read237_phi_reg_277 <= p_read2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read237_phi_reg_277 <= ap_phi_reg_pp0_iter0_p_read237_phi_reg_277;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_44)) begin
        if ((ap_phi_mux_do_init_phi_fu_156_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read338_phi_reg_289 <= p_read3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read338_phi_reg_289 <= ap_phi_reg_pp0_iter0_p_read338_phi_reg_289;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_44)) begin
        if ((ap_phi_mux_do_init_phi_fu_156_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read35_phi_reg_253 <= p_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read35_phi_reg_253 <= ap_phi_reg_pp0_iter0_p_read35_phi_reg_253;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln135_reg_1298 == 1'd0))) begin
        do_init_reg_152 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        do_init_reg_152 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln135_reg_1298 == 1'd0))) begin
        in_index_033_reg_182 <= select_ln154_fu_1063_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_index_033_reg_182 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd0))) begin
        p_Val2_1022_reg_371 <= ap_phi_mux_p_Val2_13_phi_fu_829_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_1022_reg_371 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd0))) begin
        p_Val2_1120_reg_385 <= ap_phi_mux_p_Val2_14_phi_fu_799_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_1120_reg_385 <= 16'd65344;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd0))) begin
        p_Val2_1218_reg_399 <= ap_phi_mux_p_Val2_15_phi_fu_769_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_1218_reg_399 <= 16'd65344;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd0))) begin
        p_Val2_32_reg_301 <= ap_phi_mux_p_Val2_s_phi_fu_979_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_32_reg_301 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd0))) begin
        p_Val2_630_reg_315 <= ap_phi_mux_p_Val2_9_phi_fu_949_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_630_reg_315 <= 16'd65376;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd0))) begin
        p_Val2_728_reg_329 <= ap_phi_mux_p_Val2_10_phi_fu_919_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_728_reg_329 <= 16'd65504;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd0))) begin
        p_Val2_826_reg_343 <= ap_phi_mux_p_Val2_11_phi_fu_889_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_826_reg_343 <= 16'd224;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd0))) begin
        p_Val2_924_reg_357 <= ap_phi_mux_p_Val2_12_phi_fu_859_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_Val2_924_reg_357 <= 16'd576;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_198)) begin
        if ((do_init_reg_152 == 1'd0)) begin
            p_read136_phi_reg_265 <= ap_phi_mux_p_read136_rewind_phi_fu_215_p6;
        end else if ((1'b1 == 1'b1)) begin
            p_read136_phi_reg_265 <= ap_phi_reg_pp0_iter1_p_read136_phi_reg_265;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_198)) begin
        if ((do_init_reg_152 == 1'd0)) begin
            p_read237_phi_reg_277 <= ap_phi_mux_p_read237_rewind_phi_fu_229_p6;
        end else if ((1'b1 == 1'b1)) begin
            p_read237_phi_reg_277 <= ap_phi_reg_pp0_iter1_p_read237_phi_reg_277;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_198)) begin
        if ((do_init_reg_152 == 1'd0)) begin
            p_read338_phi_reg_289 <= ap_phi_mux_p_read338_rewind_phi_fu_243_p6;
        end else if ((1'b1 == 1'b1)) begin
            p_read338_phi_reg_289 <= ap_phi_reg_pp0_iter1_p_read338_phi_reg_289;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_198)) begin
        if ((do_init_reg_152 == 1'd0)) begin
            p_read35_phi_reg_253 <= ap_phi_mux_p_read35_rewind_phi_fu_201_p6;
        end else if ((1'b1 == 1'b1)) begin
            p_read35_phi_reg_253 <= ap_phi_reg_pp0_iter1_p_read35_phi_reg_253;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln135_reg_1298 == 1'd0))) begin
        w_index34_reg_168 <= w_index_reg_1283;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        w_index34_reg_168 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln135_reg_1298 <= icmp_ln135_fu_1039_p2;
        icmp_ln135_reg_1298_pp0_iter1_reg <= icmp_ln135_reg_1298;
        icmp_ln154_reg_1293 <= icmp_ln154_fu_1033_p2;
        in_index_reg_1288 <= in_index_fu_1017_p2;
        out_index_reg_1302 <= outidx1_q0;
        tmp_36_reg_1307 <= tmp_36_fu_1049_p6;
        w14_V_load_reg_1312 <= w14_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln135_reg_1298_pp0_iter2_reg <= icmp_ln135_reg_1298_pp0_iter1_reg;
        out_index_reg_1302_pp0_iter2_reg <= out_index_reg_1302;
        trunc_ln_reg_1322 <= {{r_V_fu_1075_p2[14:1]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1298_pp0_iter1_reg == 1'd0))) begin
        p_read136_rewind_reg_211 <= p_read136_phi_reg_265;
        p_read237_rewind_reg_225 <= p_read237_phi_reg_277;
        p_read338_rewind_reg_239 <= p_read338_phi_reg_289;
        p_read35_rewind_reg_197 <= p_read35_phi_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_index_reg_1283 <= w_index_fu_1011_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if ((out_index_reg_1302_pp0_iter2_reg == 3'd0)) begin
        ap_phi_mux_acc_0_V_1_phi_fu_739_p16 = acc_0_V_fu_1115_p2;
    end else if (((out_index_reg_1302_pp0_iter2_reg == 3'd1) | (out_index_reg_1302_pp0_iter2_reg == 3'd2) | (out_index_reg_1302_pp0_iter2_reg == 3'd3) | (out_index_reg_1302_pp0_iter2_reg == 3'd4) | (out_index_reg_1302_pp0_iter2_reg == 3'd5) | (out_index_reg_1302_pp0_iter2_reg == 3'd6) | (out_index_reg_1302_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_0_V_1_phi_fu_739_p16 = acc_0_V_016_reg_413;
    end else begin
        ap_phi_mux_acc_0_V_1_phi_fu_739_p16 = ap_phi_reg_pp0_iter3_acc_0_V_1_reg_735;
    end
end

always @ (*) begin
    if ((out_index_reg_1302_pp0_iter2_reg == 3'd1)) begin
        ap_phi_mux_acc_1_V_1_phi_fu_709_p16 = acc_0_V_fu_1115_p2;
    end else if (((out_index_reg_1302_pp0_iter2_reg == 3'd0) | (out_index_reg_1302_pp0_iter2_reg == 3'd2) | (out_index_reg_1302_pp0_iter2_reg == 3'd3) | (out_index_reg_1302_pp0_iter2_reg == 3'd4) | (out_index_reg_1302_pp0_iter2_reg == 3'd5) | (out_index_reg_1302_pp0_iter2_reg == 3'd6) | (out_index_reg_1302_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_1_V_1_phi_fu_709_p16 = acc_1_V_015_reg_427;
    end else begin
        ap_phi_mux_acc_1_V_1_phi_fu_709_p16 = ap_phi_reg_pp0_iter3_acc_1_V_1_reg_705;
    end
end

always @ (*) begin
    if ((out_index_reg_1302_pp0_iter2_reg == 3'd2)) begin
        ap_phi_mux_acc_2_V_1_phi_fu_679_p16 = acc_0_V_fu_1115_p2;
    end else if (((out_index_reg_1302_pp0_iter2_reg == 3'd0) | (out_index_reg_1302_pp0_iter2_reg == 3'd1) | (out_index_reg_1302_pp0_iter2_reg == 3'd3) | (out_index_reg_1302_pp0_iter2_reg == 3'd4) | (out_index_reg_1302_pp0_iter2_reg == 3'd5) | (out_index_reg_1302_pp0_iter2_reg == 3'd6) | (out_index_reg_1302_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_2_V_1_phi_fu_679_p16 = acc_2_V_014_reg_441;
    end else begin
        ap_phi_mux_acc_2_V_1_phi_fu_679_p16 = ap_phi_reg_pp0_iter3_acc_2_V_1_reg_675;
    end
end

always @ (*) begin
    if ((out_index_reg_1302_pp0_iter2_reg == 3'd3)) begin
        ap_phi_mux_acc_3_V_1_phi_fu_649_p16 = acc_0_V_fu_1115_p2;
    end else if (((out_index_reg_1302_pp0_iter2_reg == 3'd0) | (out_index_reg_1302_pp0_iter2_reg == 3'd1) | (out_index_reg_1302_pp0_iter2_reg == 3'd2) | (out_index_reg_1302_pp0_iter2_reg == 3'd4) | (out_index_reg_1302_pp0_iter2_reg == 3'd5) | (out_index_reg_1302_pp0_iter2_reg == 3'd6) | (out_index_reg_1302_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_3_V_1_phi_fu_649_p16 = acc_3_V_013_reg_455;
    end else begin
        ap_phi_mux_acc_3_V_1_phi_fu_649_p16 = ap_phi_reg_pp0_iter3_acc_3_V_1_reg_645;
    end
end

always @ (*) begin
    if ((out_index_reg_1302_pp0_iter2_reg == 3'd4)) begin
        ap_phi_mux_acc_4_V_1_phi_fu_619_p16 = acc_0_V_fu_1115_p2;
    end else if (((out_index_reg_1302_pp0_iter2_reg == 3'd0) | (out_index_reg_1302_pp0_iter2_reg == 3'd1) | (out_index_reg_1302_pp0_iter2_reg == 3'd2) | (out_index_reg_1302_pp0_iter2_reg == 3'd3) | (out_index_reg_1302_pp0_iter2_reg == 3'd5) | (out_index_reg_1302_pp0_iter2_reg == 3'd6) | (out_index_reg_1302_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_4_V_1_phi_fu_619_p16 = acc_4_V_012_reg_469;
    end else begin
        ap_phi_mux_acc_4_V_1_phi_fu_619_p16 = ap_phi_reg_pp0_iter3_acc_4_V_1_reg_615;
    end
end

always @ (*) begin
    if ((out_index_reg_1302_pp0_iter2_reg == 3'd5)) begin
        ap_phi_mux_acc_5_V_1_phi_fu_589_p16 = acc_0_V_fu_1115_p2;
    end else if (((out_index_reg_1302_pp0_iter2_reg == 3'd0) | (out_index_reg_1302_pp0_iter2_reg == 3'd1) | (out_index_reg_1302_pp0_iter2_reg == 3'd2) | (out_index_reg_1302_pp0_iter2_reg == 3'd3) | (out_index_reg_1302_pp0_iter2_reg == 3'd4) | (out_index_reg_1302_pp0_iter2_reg == 3'd6) | (out_index_reg_1302_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_5_V_1_phi_fu_589_p16 = acc_5_V_011_reg_483;
    end else begin
        ap_phi_mux_acc_5_V_1_phi_fu_589_p16 = ap_phi_reg_pp0_iter3_acc_5_V_1_reg_585;
    end
end

always @ (*) begin
    if ((out_index_reg_1302_pp0_iter2_reg == 3'd6)) begin
        ap_phi_mux_acc_6_V_1_phi_fu_559_p16 = acc_0_V_fu_1115_p2;
    end else if (((out_index_reg_1302_pp0_iter2_reg == 3'd0) | (out_index_reg_1302_pp0_iter2_reg == 3'd1) | (out_index_reg_1302_pp0_iter2_reg == 3'd2) | (out_index_reg_1302_pp0_iter2_reg == 3'd3) | (out_index_reg_1302_pp0_iter2_reg == 3'd4) | (out_index_reg_1302_pp0_iter2_reg == 3'd5) | (out_index_reg_1302_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_6_V_1_phi_fu_559_p16 = acc_6_V_010_reg_497;
    end else begin
        ap_phi_mux_acc_6_V_1_phi_fu_559_p16 = ap_phi_reg_pp0_iter3_acc_6_V_1_reg_555;
    end
end

always @ (*) begin
    if (((out_index_reg_1302_pp0_iter2_reg == 3'd0) | (out_index_reg_1302_pp0_iter2_reg == 3'd1) | (out_index_reg_1302_pp0_iter2_reg == 3'd2) | (out_index_reg_1302_pp0_iter2_reg == 3'd3) | (out_index_reg_1302_pp0_iter2_reg == 3'd4) | (out_index_reg_1302_pp0_iter2_reg == 3'd5) | (out_index_reg_1302_pp0_iter2_reg == 3'd6))) begin
        ap_phi_mux_acc_7_V_1_phi_fu_529_p16 = acc_7_V_09_reg_511;
    end else if ((out_index_reg_1302_pp0_iter2_reg == 3'd7)) begin
        ap_phi_mux_acc_7_V_1_phi_fu_529_p16 = acc_0_V_fu_1115_p2;
    end else begin
        ap_phi_mux_acc_7_V_1_phi_fu_529_p16 = ap_phi_reg_pp0_iter3_acc_7_V_1_reg_525;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_217)) begin
        if ((icmp_ln135_reg_1298 == 1'd1)) begin
            ap_phi_mux_do_init_phi_fu_156_p6 = 1'd1;
        end else if ((icmp_ln135_reg_1298 == 1'd0)) begin
            ap_phi_mux_do_init_phi_fu_156_p6 = 1'd0;
        end else begin
            ap_phi_mux_do_init_phi_fu_156_p6 = do_init_reg_152;
        end
    end else begin
        ap_phi_mux_do_init_phi_fu_156_p6 = do_init_reg_152;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_217)) begin
        if ((icmp_ln135_reg_1298 == 1'd1)) begin
            ap_phi_mux_in_index_033_phi_fu_186_p6 = 32'd0;
        end else if ((icmp_ln135_reg_1298 == 1'd0)) begin
            ap_phi_mux_in_index_033_phi_fu_186_p6 = select_ln154_fu_1063_p3;
        end else begin
            ap_phi_mux_in_index_033_phi_fu_186_p6 = in_index_033_reg_182;
        end
    end else begin
        ap_phi_mux_in_index_033_phi_fu_186_p6 = in_index_033_reg_182;
    end
end

always @ (*) begin
    if ((out_index_reg_1302_pp0_iter2_reg == 3'd2)) begin
        ap_phi_mux_p_Val2_10_phi_fu_919_p16 = acc_0_V_fu_1115_p2;
    end else if (((out_index_reg_1302_pp0_iter2_reg == 3'd0) | (out_index_reg_1302_pp0_iter2_reg == 3'd1) | (out_index_reg_1302_pp0_iter2_reg == 3'd3) | (out_index_reg_1302_pp0_iter2_reg == 3'd4) | (out_index_reg_1302_pp0_iter2_reg == 3'd5) | (out_index_reg_1302_pp0_iter2_reg == 3'd6) | (out_index_reg_1302_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_p_Val2_10_phi_fu_919_p16 = p_Val2_728_reg_329;
    end else begin
        ap_phi_mux_p_Val2_10_phi_fu_919_p16 = ap_phi_reg_pp0_iter3_p_Val2_10_reg_915;
    end
end

always @ (*) begin
    if ((out_index_reg_1302_pp0_iter2_reg == 3'd3)) begin
        ap_phi_mux_p_Val2_11_phi_fu_889_p16 = acc_0_V_fu_1115_p2;
    end else if (((out_index_reg_1302_pp0_iter2_reg == 3'd0) | (out_index_reg_1302_pp0_iter2_reg == 3'd1) | (out_index_reg_1302_pp0_iter2_reg == 3'd2) | (out_index_reg_1302_pp0_iter2_reg == 3'd4) | (out_index_reg_1302_pp0_iter2_reg == 3'd5) | (out_index_reg_1302_pp0_iter2_reg == 3'd6) | (out_index_reg_1302_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_p_Val2_11_phi_fu_889_p16 = p_Val2_826_reg_343;
    end else begin
        ap_phi_mux_p_Val2_11_phi_fu_889_p16 = ap_phi_reg_pp0_iter3_p_Val2_11_reg_885;
    end
end

always @ (*) begin
    if ((out_index_reg_1302_pp0_iter2_reg == 3'd4)) begin
        ap_phi_mux_p_Val2_12_phi_fu_859_p16 = acc_0_V_fu_1115_p2;
    end else if (((out_index_reg_1302_pp0_iter2_reg == 3'd0) | (out_index_reg_1302_pp0_iter2_reg == 3'd1) | (out_index_reg_1302_pp0_iter2_reg == 3'd2) | (out_index_reg_1302_pp0_iter2_reg == 3'd3) | (out_index_reg_1302_pp0_iter2_reg == 3'd5) | (out_index_reg_1302_pp0_iter2_reg == 3'd6) | (out_index_reg_1302_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_p_Val2_12_phi_fu_859_p16 = p_Val2_924_reg_357;
    end else begin
        ap_phi_mux_p_Val2_12_phi_fu_859_p16 = ap_phi_reg_pp0_iter3_p_Val2_12_reg_855;
    end
end

always @ (*) begin
    if ((out_index_reg_1302_pp0_iter2_reg == 3'd5)) begin
        ap_phi_mux_p_Val2_13_phi_fu_829_p16 = acc_0_V_fu_1115_p2;
    end else if (((out_index_reg_1302_pp0_iter2_reg == 3'd0) | (out_index_reg_1302_pp0_iter2_reg == 3'd1) | (out_index_reg_1302_pp0_iter2_reg == 3'd2) | (out_index_reg_1302_pp0_iter2_reg == 3'd3) | (out_index_reg_1302_pp0_iter2_reg == 3'd4) | (out_index_reg_1302_pp0_iter2_reg == 3'd6) | (out_index_reg_1302_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_p_Val2_13_phi_fu_829_p16 = p_Val2_1022_reg_371;
    end else begin
        ap_phi_mux_p_Val2_13_phi_fu_829_p16 = ap_phi_reg_pp0_iter3_p_Val2_13_reg_825;
    end
end

always @ (*) begin
    if ((out_index_reg_1302_pp0_iter2_reg == 3'd6)) begin
        ap_phi_mux_p_Val2_14_phi_fu_799_p16 = acc_0_V_fu_1115_p2;
    end else if (((out_index_reg_1302_pp0_iter2_reg == 3'd0) | (out_index_reg_1302_pp0_iter2_reg == 3'd1) | (out_index_reg_1302_pp0_iter2_reg == 3'd2) | (out_index_reg_1302_pp0_iter2_reg == 3'd3) | (out_index_reg_1302_pp0_iter2_reg == 3'd4) | (out_index_reg_1302_pp0_iter2_reg == 3'd5) | (out_index_reg_1302_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_p_Val2_14_phi_fu_799_p16 = p_Val2_1120_reg_385;
    end else begin
        ap_phi_mux_p_Val2_14_phi_fu_799_p16 = ap_phi_reg_pp0_iter3_p_Val2_14_reg_795;
    end
end

always @ (*) begin
    if (((out_index_reg_1302_pp0_iter2_reg == 3'd0) | (out_index_reg_1302_pp0_iter2_reg == 3'd1) | (out_index_reg_1302_pp0_iter2_reg == 3'd2) | (out_index_reg_1302_pp0_iter2_reg == 3'd3) | (out_index_reg_1302_pp0_iter2_reg == 3'd4) | (out_index_reg_1302_pp0_iter2_reg == 3'd5) | (out_index_reg_1302_pp0_iter2_reg == 3'd6))) begin
        ap_phi_mux_p_Val2_15_phi_fu_769_p16 = p_Val2_1218_reg_399;
    end else if ((out_index_reg_1302_pp0_iter2_reg == 3'd7)) begin
        ap_phi_mux_p_Val2_15_phi_fu_769_p16 = acc_0_V_fu_1115_p2;
    end else begin
        ap_phi_mux_p_Val2_15_phi_fu_769_p16 = ap_phi_reg_pp0_iter3_p_Val2_15_reg_765;
    end
end

always @ (*) begin
    if ((out_index_reg_1302_pp0_iter2_reg == 3'd1)) begin
        ap_phi_mux_p_Val2_9_phi_fu_949_p16 = acc_0_V_fu_1115_p2;
    end else if (((out_index_reg_1302_pp0_iter2_reg == 3'd0) | (out_index_reg_1302_pp0_iter2_reg == 3'd2) | (out_index_reg_1302_pp0_iter2_reg == 3'd3) | (out_index_reg_1302_pp0_iter2_reg == 3'd4) | (out_index_reg_1302_pp0_iter2_reg == 3'd5) | (out_index_reg_1302_pp0_iter2_reg == 3'd6) | (out_index_reg_1302_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_p_Val2_9_phi_fu_949_p16 = p_Val2_630_reg_315;
    end else begin
        ap_phi_mux_p_Val2_9_phi_fu_949_p16 = ap_phi_reg_pp0_iter3_p_Val2_9_reg_945;
    end
end

always @ (*) begin
    if ((out_index_reg_1302_pp0_iter2_reg == 3'd0)) begin
        ap_phi_mux_p_Val2_s_phi_fu_979_p16 = acc_0_V_fu_1115_p2;
    end else if (((out_index_reg_1302_pp0_iter2_reg == 3'd1) | (out_index_reg_1302_pp0_iter2_reg == 3'd2) | (out_index_reg_1302_pp0_iter2_reg == 3'd3) | (out_index_reg_1302_pp0_iter2_reg == 3'd4) | (out_index_reg_1302_pp0_iter2_reg == 3'd5) | (out_index_reg_1302_pp0_iter2_reg == 3'd6) | (out_index_reg_1302_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_p_Val2_s_phi_fu_979_p16 = p_Val2_32_reg_301;
    end else begin
        ap_phi_mux_p_Val2_s_phi_fu_979_p16 = ap_phi_reg_pp0_iter3_p_Val2_s_reg_975;
    end
end

always @ (*) begin
    if ((do_init_reg_152 == 1'd0)) begin
        ap_phi_mux_p_read136_phi_phi_fu_269_p4 = ap_phi_mux_p_read136_rewind_phi_fu_215_p6;
    end else begin
        ap_phi_mux_p_read136_phi_phi_fu_269_p4 = ap_phi_reg_pp0_iter1_p_read136_phi_reg_265;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1298_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_p_read136_rewind_phi_fu_215_p6 = p_read136_phi_reg_265;
    end else begin
        ap_phi_mux_p_read136_rewind_phi_fu_215_p6 = p_read136_rewind_reg_211;
    end
end

always @ (*) begin
    if ((do_init_reg_152 == 1'd0)) begin
        ap_phi_mux_p_read237_phi_phi_fu_281_p4 = ap_phi_mux_p_read237_rewind_phi_fu_229_p6;
    end else begin
        ap_phi_mux_p_read237_phi_phi_fu_281_p4 = ap_phi_reg_pp0_iter1_p_read237_phi_reg_277;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1298_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_p_read237_rewind_phi_fu_229_p6 = p_read237_phi_reg_277;
    end else begin
        ap_phi_mux_p_read237_rewind_phi_fu_229_p6 = p_read237_rewind_reg_225;
    end
end

always @ (*) begin
    if ((do_init_reg_152 == 1'd0)) begin
        ap_phi_mux_p_read338_phi_phi_fu_293_p4 = ap_phi_mux_p_read338_rewind_phi_fu_243_p6;
    end else begin
        ap_phi_mux_p_read338_phi_phi_fu_293_p4 = ap_phi_reg_pp0_iter1_p_read338_phi_reg_289;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1298_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_p_read338_rewind_phi_fu_243_p6 = p_read338_phi_reg_289;
    end else begin
        ap_phi_mux_p_read338_rewind_phi_fu_243_p6 = p_read338_rewind_reg_239;
    end
end

always @ (*) begin
    if ((do_init_reg_152 == 1'd0)) begin
        ap_phi_mux_p_read35_phi_phi_fu_257_p4 = ap_phi_mux_p_read35_rewind_phi_fu_201_p6;
    end else begin
        ap_phi_mux_p_read35_phi_phi_fu_257_p4 = ap_phi_reg_pp0_iter1_p_read35_phi_reg_253;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln135_reg_1298_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_p_read35_rewind_phi_fu_201_p6 = p_read35_phi_reg_253;
    end else begin
        ap_phi_mux_p_read35_rewind_phi_fu_201_p6 = p_read35_rewind_reg_197;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_217)) begin
        if ((icmp_ln135_reg_1298 == 1'd1)) begin
            ap_phi_mux_w_index34_phi_fu_172_p6 = 5'd0;
        end else if ((icmp_ln135_reg_1298 == 1'd0)) begin
            ap_phi_mux_w_index34_phi_fu_172_p6 = w_index_reg_1283;
        end else begin
            ap_phi_mux_w_index34_phi_fu_172_p6 = w_index34_reg_168;
        end
    end else begin
        ap_phi_mux_w_index34_phi_fu_172_p6 = w_index34_reg_168;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_fu_1039_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_0 = res_0_V_write_assign_fu_1137_p3;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_1 = res_1_V_write_assign_fu_1145_p3;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_2 = res_2_V_write_assign_fu_1153_p3;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_3 = res_3_V_write_assign_fu_1161_p3;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_4 = res_4_V_write_assign_fu_1169_p3;
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_5 = res_5_V_write_assign_fu_1177_p3;
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_6 = res_6_V_write_assign_fu_1185_p3;
    end else begin
        ap_return_6 = ap_return_6_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1298_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_7 = res_7_V_write_assign_fu_1193_p3;
    end else begin
        ap_return_7 = ap_return_7_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        outidx1_ce0 = 1'b1;
    end else begin
        outidx1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w14_V_ce0 = 1'b1;
    end else begin
        w14_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_0_V_fu_1115_p2 = ($signed(tmp_37_fu_1094_p10) + $signed(sext_ln708_fu_1091_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_198 = ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_217 = ((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_44 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_p_read136_phi_reg_265 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read237_phi_reg_277 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read338_phi_reg_289 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read35_phi_reg_253 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_0_V_1_reg_735 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_1_V_1_reg_705 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_2_V_1_reg_675 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_3_V_1_reg_645 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_4_V_1_reg_615 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_5_V_1_reg_585 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_6_V_1_reg_555 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_7_V_1_reg_525 = 'bx;

assign ap_phi_reg_pp0_iter3_p_Val2_10_reg_915 = 'bx;

assign ap_phi_reg_pp0_iter3_p_Val2_11_reg_885 = 'bx;

assign ap_phi_reg_pp0_iter3_p_Val2_12_reg_855 = 'bx;

assign ap_phi_reg_pp0_iter3_p_Val2_13_reg_825 = 'bx;

assign ap_phi_reg_pp0_iter3_p_Val2_14_reg_795 = 'bx;

assign ap_phi_reg_pp0_iter3_p_Val2_15_reg_765 = 'bx;

assign ap_phi_reg_pp0_iter3_p_Val2_9_reg_945 = 'bx;

assign ap_phi_reg_pp0_iter3_p_Val2_s_reg_975 = 'bx;

assign icmp_ln135_fu_1039_p2 = ((ap_phi_mux_w_index34_phi_fu_172_p6 == 5'd31) ? 1'b1 : 1'b0);

assign icmp_ln154_fu_1033_p2 = (($signed(tmp_133_fu_1023_p4) > $signed(30'd0)) ? 1'b1 : 1'b0);

assign in_index_fu_1017_p2 = (ap_phi_mux_in_index_033_phi_fu_186_p6 + 32'd1);

assign outidx1_address0 = zext_ln139_fu_1005_p1;

assign r_V_fu_1075_p0 = r_V_fu_1075_p00;

assign r_V_fu_1075_p00 = tmp_36_reg_1307;

assign r_V_fu_1075_p1 = w14_V_load_reg_1312;

assign r_V_fu_1075_p2 = ($signed({{1'b0}, {r_V_fu_1075_p0}}) * $signed(r_V_fu_1075_p1));

assign res_0_V_write_assign_fu_1137_p3 = {{ap_phi_mux_p_Val2_s_phi_fu_979_p16}, {1'd0}};

assign res_1_V_write_assign_fu_1145_p3 = {{ap_phi_mux_p_Val2_9_phi_fu_949_p16}, {1'd0}};

assign res_2_V_write_assign_fu_1153_p3 = {{ap_phi_mux_p_Val2_10_phi_fu_919_p16}, {1'd0}};

assign res_3_V_write_assign_fu_1161_p3 = {{ap_phi_mux_p_Val2_11_phi_fu_889_p16}, {1'd0}};

assign res_4_V_write_assign_fu_1169_p3 = {{ap_phi_mux_p_Val2_12_phi_fu_859_p16}, {1'd0}};

assign res_5_V_write_assign_fu_1177_p3 = {{ap_phi_mux_p_Val2_13_phi_fu_829_p16}, {1'd0}};

assign res_6_V_write_assign_fu_1185_p3 = {{ap_phi_mux_p_Val2_14_phi_fu_799_p16}, {1'd0}};

assign res_7_V_write_assign_fu_1193_p3 = {{ap_phi_mux_p_Val2_15_phi_fu_769_p16}, {1'd0}};

assign select_ln154_fu_1063_p3 = ((icmp_ln154_reg_1293[0:0] === 1'b1) ? 32'd0 : in_index_reg_1288);

assign sext_ln708_fu_1091_p1 = $signed(trunc_ln_reg_1322);

assign tmp_133_fu_1023_p4 = {{in_index_fu_1017_p2[31:2]}};

assign tmp_36_fu_1049_p5 = in_index_033_reg_182[1:0];

assign w14_V_address0 = zext_ln139_fu_1005_p1;

assign w_index_fu_1011_p2 = (5'd1 + ap_phi_mux_w_index34_phi_fu_172_p6);

assign zext_ln139_fu_1005_p1 = ap_phi_mux_w_index34_phi_fu_172_p6;

always @ (posedge ap_clk) begin
    ap_return_0_preg[0] <= 1'b0;
    ap_return_1_preg[0] <= 1'b0;
    ap_return_2_preg[0] <= 1'b0;
    ap_return_3_preg[0] <= 1'b0;
    ap_return_4_preg[0] <= 1'b0;
    ap_return_5_preg[0] <= 1'b0;
    ap_return_6_preg[0] <= 1'b0;
    ap_return_7_preg[0] <= 1'b0;
end

endmodule //dense_resource_rf_gt_nin_rem0_ap_ufixed_ap_fixed_config14_0_0_0_0_0_0_0_0_0
